# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.organisations_api import OrganisationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrganisationsApi(unittest.TestCase):
    """OrganisationsApi unit test stubs"""

    def setUp(self):
        self.api = OrganisationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_of_organisations_counts_organisations_v1_get(self):
        """Test case for count_of_organisations_counts_organisations_v1_get

        Count Of Organisations  # noqa: E501
        """
        pass

    def test_list_organisations_organisations_v1_get(self):
        """Test case for list_organisations_organisations_v1_get

        List Organisations  # noqa: E501
        """
        pass

    def test_list_organisations_platforms_platform_organisations_v1_get(self):
        """Test case for list_organisations_platforms_platform_organisations_v1_get

        List Organisations  # noqa: E501
        """
        pass

    def test_organisation_organisations_v1_identifier_delete(self):
        """Test case for organisation_organisations_v1_identifier_delete

        Organisation  # noqa: E501
        """
        pass

    def test_organisation_organisations_v1_identifier_get(self):
        """Test case for organisation_organisations_v1_identifier_get

        Organisation  # noqa: E501
        """
        pass

    def test_organisation_organisations_v1_identifier_put(self):
        """Test case for organisation_organisations_v1_identifier_put

        Organisation  # noqa: E501
        """
        pass

    def test_organisation_organisations_v1_post(self):
        """Test case for organisation_organisations_v1_post

        Organisation  # noqa: E501
        """
        pass

    def test_organisation_platforms_platform_organisations_v1_identifier_get(self):
        """Test case for organisation_platforms_platform_organisations_v1_identifier_get

        Organisation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
