# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.case_studies_api import CaseStudiesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCaseStudiesApi(unittest.TestCase):
    """CaseStudiesApi unit test stubs"""

    def setUp(self):
        self.api = CaseStudiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_case_study_case_studies_v1_identifier_content_distribution_idx_get(self):
        """Test case for case_study_case_studies_v1_identifier_content_distribution_idx_get

        Case Study  # noqa: E501
        """
        pass

    def test_case_study_case_studies_v1_identifier_content_get(self):
        """Test case for case_study_case_studies_v1_identifier_content_get

        Case Study  # noqa: E501
        """
        pass

    def test_case_study_case_studies_v1_identifier_delete(self):
        """Test case for case_study_case_studies_v1_identifier_delete

        Case Study  # noqa: E501
        """
        pass

    def test_case_study_case_studies_v1_identifier_get(self):
        """Test case for case_study_case_studies_v1_identifier_get

        Case Study  # noqa: E501
        """
        pass

    def test_case_study_case_studies_v1_identifier_put(self):
        """Test case for case_study_case_studies_v1_identifier_put

        Case Study  # noqa: E501
        """
        pass

    def test_case_study_case_studies_v1_post(self):
        """Test case for case_study_case_studies_v1_post

        Case Study  # noqa: E501
        """
        pass

    def test_case_study_platforms_platform_case_studies_v1_identifier_get(self):
        """Test case for case_study_platforms_platform_case_studies_v1_identifier_get

        Case Study  # noqa: E501
        """
        pass

    def test_count_of_case_studies_counts_case_studies_v1_get(self):
        """Test case for count_of_case_studies_counts_case_studies_v1_get

        Count Of Case Studies  # noqa: E501
        """
        pass

    def test_list_case_studies_case_studies_v1_get(self):
        """Test case for list_case_studies_case_studies_v1_get

        List Case Studies  # noqa: E501
        """
        pass

    def test_list_case_studies_platforms_platform_case_studies_v1_get(self):
        """Test case for list_case_studies_platforms_platform_case_studies_v1_get

        List Case Studies  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
