# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.educational_resources_api import EducationalResourcesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEducationalResourcesApi(unittest.TestCase):
    """EducationalResourcesApi unit test stubs"""

    def setUp(self):
        self.api = EducationalResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_of_educational_resources_counts_educational_resources_v1_get(self):
        """Test case for count_of_educational_resources_counts_educational_resources_v1_get

        Count Of Educational Resources  # noqa: E501
        """
        pass

    def test_educational_resource_educational_resources_v1_identifier_delete(self):
        """Test case for educational_resource_educational_resources_v1_identifier_delete

        Educational Resource  # noqa: E501
        """
        pass

    def test_educational_resource_educational_resources_v1_identifier_get(self):
        """Test case for educational_resource_educational_resources_v1_identifier_get

        Educational Resource  # noqa: E501
        """
        pass

    def test_educational_resource_educational_resources_v1_identifier_put(self):
        """Test case for educational_resource_educational_resources_v1_identifier_put

        Educational Resource  # noqa: E501
        """
        pass

    def test_educational_resource_educational_resources_v1_post(self):
        """Test case for educational_resource_educational_resources_v1_post

        Educational Resource  # noqa: E501
        """
        pass

    def test_educational_resource_platforms_platform_educational_resources_v1_identifier_get(self):
        """Test case for educational_resource_platforms_platform_educational_resources_v1_identifier_get

        Educational Resource  # noqa: E501
        """
        pass

    def test_list_educational_resources_educational_resources_v1_get(self):
        """Test case for list_educational_resources_educational_resources_v1_get

        List Educational Resources  # noqa: E501
        """
        pass

    def test_list_educational_resources_platforms_platform_educational_resources_v1_get(self):
        """Test case for list_educational_resources_platforms_platform_educational_resources_v1_get

        List Educational Resources  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
