# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.persons_api import PersonsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPersonsApi(unittest.TestCase):
    """PersonsApi unit test stubs"""

    def setUp(self):
        self.api = PersonsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_of_persons_counts_persons_v1_get(self):
        """Test case for count_of_persons_counts_persons_v1_get

        Count Of Persons  # noqa: E501
        """
        pass

    def test_list_persons_persons_v1_get(self):
        """Test case for list_persons_persons_v1_get

        List Persons  # noqa: E501
        """
        pass

    def test_list_persons_platforms_platform_persons_v1_get(self):
        """Test case for list_persons_platforms_platform_persons_v1_get

        List Persons  # noqa: E501
        """
        pass

    def test_person_persons_v1_identifier_delete(self):
        """Test case for person_persons_v1_identifier_delete

        Person  # noqa: E501
        """
        pass

    def test_person_persons_v1_identifier_get(self):
        """Test case for person_persons_v1_identifier_get

        Person  # noqa: E501
        """
        pass

    def test_person_persons_v1_identifier_put(self):
        """Test case for person_persons_v1_identifier_put

        Person  # noqa: E501
        """
        pass

    def test_person_persons_v1_post(self):
        """Test case for person_persons_v1_post

        Person  # noqa: E501
        """
        pass

    def test_person_platforms_platform_persons_v1_identifier_get(self):
        """Test case for person_platforms_platform_persons_v1_identifier_get

        Person  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
