# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.person_read import PersonRead  # noqa: E501
from swagger_client.rest import ApiException


class TestPersonRead(unittest.TestCase):
    """PersonRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersonRead(self):
        """Test PersonRead"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.person_read.PersonRead()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
