# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.computational_assets_api import ComputationalAssetsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComputationalAssetsApi(unittest.TestCase):
    """ComputationalAssetsApi unit test stubs"""

    def setUp(self):
        self.api = ComputationalAssetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_computational_asset_computational_assets_v1_identifier_delete(self):
        """Test case for computational_asset_computational_assets_v1_identifier_delete

        Computational Asset  # noqa: E501
        """
        pass

    def test_computational_asset_computational_assets_v1_identifier_get(self):
        """Test case for computational_asset_computational_assets_v1_identifier_get

        Computational Asset  # noqa: E501
        """
        pass

    def test_computational_asset_computational_assets_v1_identifier_put(self):
        """Test case for computational_asset_computational_assets_v1_identifier_put

        Computational Asset  # noqa: E501
        """
        pass

    def test_computational_asset_computational_assets_v1_post(self):
        """Test case for computational_asset_computational_assets_v1_post

        Computational Asset  # noqa: E501
        """
        pass

    def test_computational_asset_platforms_platform_computational_assets_v1_identifier_get(self):
        """Test case for computational_asset_platforms_platform_computational_assets_v1_identifier_get

        Computational Asset  # noqa: E501
        """
        pass

    def test_count_of_computational_assets_counts_computational_assets_v1_get(self):
        """Test case for count_of_computational_assets_counts_computational_assets_v1_get

        Count Of Computational Assets  # noqa: E501
        """
        pass

    def test_list_computational_assets_computational_assets_v1_get(self):
        """Test case for list_computational_assets_computational_assets_v1_get

        List Computational Assets  # noqa: E501
        """
        pass

    def test_list_computational_assets_platforms_platform_computational_assets_v1_get(self):
        """Test case for list_computational_assets_platforms_platform_computational_assets_v1_get

        List Computational Assets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
