# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.events_api import EventsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_of_events_counts_events_v1_get(self):
        """Test case for count_of_events_counts_events_v1_get

        Count Of Events  # noqa: E501
        """
        pass

    def test_event_events_v1_identifier_delete(self):
        """Test case for event_events_v1_identifier_delete

        Event  # noqa: E501
        """
        pass

    def test_event_events_v1_identifier_get(self):
        """Test case for event_events_v1_identifier_get

        Event  # noqa: E501
        """
        pass

    def test_event_events_v1_identifier_put(self):
        """Test case for event_events_v1_identifier_put

        Event  # noqa: E501
        """
        pass

    def test_event_events_v1_post(self):
        """Test case for event_events_v1_post

        Event  # noqa: E501
        """
        pass

    def test_event_platforms_platform_events_v1_identifier_get(self):
        """Test case for event_platforms_platform_events_v1_identifier_get

        Event  # noqa: E501
        """
        pass

    def test_list_events_events_v1_get(self):
        """Test case for list_events_events_v1_get

        List Events  # noqa: E501
        """
        pass

    def test_list_events_platforms_platform_events_v1_get(self):
        """Test case for list_events_platforms_platform_events_v1_get

        List Events  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
