# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.contacts_api import ContactsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self):
        self.api = ContactsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contact_contacts_v1_identifier_delete(self):
        """Test case for contact_contacts_v1_identifier_delete

        Contact  # noqa: E501
        """
        pass

    def test_contact_contacts_v1_identifier_get(self):
        """Test case for contact_contacts_v1_identifier_get

        Contact  # noqa: E501
        """
        pass

    def test_contact_contacts_v1_identifier_put(self):
        """Test case for contact_contacts_v1_identifier_put

        Contact  # noqa: E501
        """
        pass

    def test_contact_contacts_v1_post(self):
        """Test case for contact_contacts_v1_post

        Contact  # noqa: E501
        """
        pass

    def test_contact_platforms_platform_contacts_v1_identifier_get(self):
        """Test case for contact_platforms_platform_contacts_v1_identifier_get

        Contact  # noqa: E501
        """
        pass

    def test_count_of_contacts_counts_contacts_v1_get(self):
        """Test case for count_of_contacts_counts_contacts_v1_get

        Count Of Contacts  # noqa: E501
        """
        pass

    def test_list_contacts_contacts_v1_get(self):
        """Test case for list_contacts_contacts_v1_get

        List Contacts  # noqa: E501
        """
        pass

    def test_list_contacts_platforms_platform_contacts_v1_get(self):
        """Test case for list_contacts_platforms_platform_contacts_v1_get

        List Contacts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
