# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.projects_api import ProjectsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_of_projects_counts_projects_v1_get(self):
        """Test case for count_of_projects_counts_projects_v1_get

        Count Of Projects  # noqa: E501
        """
        pass

    def test_list_projects_platforms_platform_projects_v1_get(self):
        """Test case for list_projects_platforms_platform_projects_v1_get

        List Projects  # noqa: E501
        """
        pass

    def test_list_projects_projects_v1_get(self):
        """Test case for list_projects_projects_v1_get

        List Projects  # noqa: E501
        """
        pass

    def test_project_platforms_platform_projects_v1_identifier_get(self):
        """Test case for project_platforms_platform_projects_v1_identifier_get

        Project  # noqa: E501
        """
        pass

    def test_project_projects_v1_identifier_delete(self):
        """Test case for project_projects_v1_identifier_delete

        Project  # noqa: E501
        """
        pass

    def test_project_projects_v1_identifier_get(self):
        """Test case for project_projects_v1_identifier_get

        Project  # noqa: E501
        """
        pass

    def test_project_projects_v1_identifier_put(self):
        """Test case for project_projects_v1_identifier_put

        Project  # noqa: E501
        """
        pass

    def test_project_projects_v1_post(self):
        """Test case for project_projects_v1_post

        Project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
