# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.parents_api import ParentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestParentsApi(unittest.TestCase):
    """ParentsApi unit test stubs"""

    def setUp(self):
        self.api = ParentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_agent_agents_v1_identifier_get(self):
        """Test case for agent_agents_v1_identifier_get

        Agent  # noqa: E501
        """
        pass

    def test_ai_asset_ai_assets_v1_identifier_get(self):
        """Test case for ai_asset_ai_assets_v1_identifier_get

        Ai Asset  # noqa: E501
        """
        pass

    def test_ai_resource_ai_resources_v1_identifier_get(self):
        """Test case for ai_resource_ai_resources_v1_identifier_get

        Ai Resource  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
