# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_home_get(self):
        """Test case for home_get

        Home  # noqa: E501
        """
        pass

    def test_test_authorization_authorization_test_get(self):
        """Test case for test_authorization_authorization_test_get

        Test Authorization  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
