"""Sklearn transformer."""

from aiod.models.apis import _ModelPkgTransformer


class AiodPkg__SklearnTransformers(_ModelPkgTransformer):
    _tags = {
        "pkg_id": "__multiple",
        "python_dependencies": "scikit-learn",
        "pkg_pypi_name": "scikit-learn",
    }

    _obj_dict = {
        'AdditiveChi2Sampler': 'sklearn.kernel_approximation.AdditiveChi2Sampler',
        'BernoulliRBM': 'sklearn.neural_network._rbm.BernoulliRBM',
        'Binarizer': 'sklearn.preprocessing._data.Binarizer',
        'Birch': 'sklearn.cluster._birch.Birch',
        'BisectingKMeans': 'sklearn.cluster._bisect_k_means.BisectingKMeans',
        'CCA': 'sklearn.cross_decomposition._pls.CCA',
        'ColumnTransformer': 'sklearn.compose._column_transformer.ColumnTransformer',
        'DictVectorizer': 'sklearn.feature_extraction._dict_vectorizer.DictVectorizer',
        'DictionaryLearning': 'sklearn.decomposition._dict_learning.DictionaryLearning',
        'FactorAnalysis': 'sklearn.decomposition._factor_analysis.FactorAnalysis',
        'FastICA': 'sklearn.decomposition._fastica.FastICA',
        'FeatureAgglomeration': 'sklearn.cluster._agglomerative.FeatureAgglomeration',
        'FeatureHasher': 'sklearn.feature_extraction._hash.FeatureHasher',
        'FeatureUnion': 'sklearn.pipeline.FeatureUnion',
        'FunctionTransformer': 'sklearn.preprocessing._function_transformer.FunctionTransformer',
        'GaussianRandomProjection': 'sklearn.random_projection.GaussianRandomProjection',
        'GenericUnivariateSelect': 'sklearn.feature_selection._univariate_selection.GenericUnivariateSelect',
        'HashingVectorizer': 'sklearn.feature_extraction.text.HashingVectorizer',
        'IncrementalPCA': 'sklearn.decomposition._incremental_pca.IncrementalPCA',
        'Isomap': 'sklearn.manifold._isomap.Isomap',
        'IsotonicRegression': 'sklearn.isotonic.IsotonicRegression',
        'KBinsDiscretizer': 'sklearn.preprocessing._discretization.KBinsDiscretizer',
        'KMeans': 'sklearn.cluster._kmeans.KMeans',
        'KNNImputer': 'sklearn.impute._knn.KNNImputer',
        'KNeighborsTransformer': 'sklearn.neighbors._graph.KNeighborsTransformer',
        'KernelCenterer': 'sklearn.preprocessing._data.KernelCenterer',
        'KernelPCA': 'sklearn.decomposition._kernel_pca.KernelPCA',
        'LabelBinarizer': 'sklearn.preprocessing._label.LabelBinarizer',
        'LabelEncoder': 'sklearn.preprocessing._label.LabelEncoder',
        'LatentDirichletAllocation': 'sklearn.decomposition._lda.LatentDirichletAllocation',
        'LinearDiscriminantAnalysis': 'sklearn.discriminant_analysis.LinearDiscriminantAnalysis',
        'LocallyLinearEmbedding': 'sklearn.manifold._locally_linear.LocallyLinearEmbedding',
        'MaxAbsScaler': 'sklearn.preprocessing._data.MaxAbsScaler',
        'MinMaxScaler': 'sklearn.preprocessing._data.MinMaxScaler',
        'MiniBatchDictionaryLearning': 'sklearn.decomposition._dict_learning.MiniBatchDictionaryLearning',
        'MiniBatchKMeans': 'sklearn.cluster._kmeans.MiniBatchKMeans',
        'MiniBatchNMF': 'sklearn.decomposition._nmf.MiniBatchNMF',
        'MiniBatchSparsePCA': 'sklearn.decomposition._sparse_pca.MiniBatchSparsePCA',
        'MissingIndicator': 'sklearn.impute._base.MissingIndicator',
        'MultiLabelBinarizer': 'sklearn.preprocessing._label.MultiLabelBinarizer',
        'NMF': 'sklearn.decomposition._nmf.NMF',
        'NeighborhoodComponentsAnalysis': 'sklearn.neighbors._nca.NeighborhoodComponentsAnalysis',
        'Normalizer': 'sklearn.preprocessing._data.Normalizer',
        'Nystroem': 'sklearn.kernel_approximation.Nystroem',
        'OneHotEncoder': 'sklearn.preprocessing._encoders.OneHotEncoder',
        'OrdinalEncoder': 'sklearn.preprocessing._encoders.OrdinalEncoder',
        'PCA': 'sklearn.decomposition._pca.PCA',
        'PLSCanonical': 'sklearn.cross_decomposition._pls.PLSCanonical',
        'PLSRegression': 'sklearn.cross_decomposition._pls.PLSRegression',
        'PLSSVD': 'sklearn.cross_decomposition._pls.PLSSVD',
        'PatchExtractor': 'sklearn.feature_extraction.image.PatchExtractor',
        'PolynomialCountSketch': 'sklearn.kernel_approximation.PolynomialCountSketch',
        'PolynomialFeatures': 'sklearn.preprocessing._polynomial.PolynomialFeatures',
        'PowerTransformer': 'sklearn.preprocessing._data.PowerTransformer',
        'QuantileTransformer': 'sklearn.preprocessing._data.QuantileTransformer',
        'RBFSampler': 'sklearn.kernel_approximation.RBFSampler',
        'RFE': 'sklearn.feature_selection._rfe.RFE',
        'RFECV': 'sklearn.feature_selection._rfe.RFECV',
        'RadiusNeighborsTransformer': 'sklearn.neighbors._graph.RadiusNeighborsTransformer',
        'RandomTreesEmbedding': 'sklearn.ensemble._forest.RandomTreesEmbedding',
        'RobustScaler': 'sklearn.preprocessing._data.RobustScaler',
        'SelectFdr': 'sklearn.feature_selection._univariate_selection.SelectFdr',
        'SelectFpr': 'sklearn.feature_selection._univariate_selection.SelectFpr',
        'SelectFromModel': 'sklearn.feature_selection._from_model.SelectFromModel',
        'SelectFwe': 'sklearn.feature_selection._univariate_selection.SelectFwe',
        'SelectKBest': 'sklearn.feature_selection._univariate_selection.SelectKBest',
        'SelectPercentile': 'sklearn.feature_selection._univariate_selection.SelectPercentile',
        'SequentialFeatureSelector': 'sklearn.feature_selection._sequential.SequentialFeatureSelector',
        'SimpleImputer': 'sklearn.impute._base.SimpleImputer',
        'SkewedChi2Sampler': 'sklearn.kernel_approximation.SkewedChi2Sampler',
        'SparseCoder': 'sklearn.decomposition._dict_learning.SparseCoder',
        'SparsePCA': 'sklearn.decomposition._sparse_pca.SparsePCA',
        'SparseRandomProjection': 'sklearn.random_projection.SparseRandomProjection',
        'SplineTransformer': 'sklearn.preprocessing._polynomial.SplineTransformer',
        'StackingClassifier': 'sklearn.ensemble._stacking.StackingClassifier',
        'StackingRegressor': 'sklearn.ensemble._stacking.StackingRegressor',
        'StandardScaler': 'sklearn.preprocessing._data.StandardScaler',
        'TSNE': 'sklearn.manifold._t_sne.TSNE',
        'TargetEncoder': 'sklearn.preprocessing._target_encoder.TargetEncoder',
        'TfidfTransformer': 'sklearn.feature_extraction.text.TfidfTransformer',
        'TruncatedSVD': 'sklearn.decomposition._truncated_svd.TruncatedSVD',
        'VarianceThreshold': 'sklearn.feature_selection._variance_threshold.VarianceThreshold',
        'VotingClassifier': 'sklearn.ensemble._voting.VotingClassifier',
        'VotingRegressor': 'sklearn.ensemble._voting.VotingRegressor'
    }