# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DctPeriodOfTime(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'type': 'object',
        'dcatstart_date': 'XSDDateTime',
        'dcatend_date': 'XSDDateTime'
    }

    attribute_map = {
        'id': '@id',
        'type': '@type',
        'dcatstart_date': 'dcat:startDate',
        'dcatend_date': 'dcat:endDate'
    }

    def __init__(self, id=None, type=None, dcatstart_date=None, dcatend_date=None):  # noqa: E501
        """DctPeriodOfTime - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._type = None
        self._dcatstart_date = None
        self._dcatend_date = None
        self.discriminator = None
        self.id = id
        if type is not None:
            self.type = type
        if dcatstart_date is not None:
            self.dcatstart_date = dcatstart_date
        if dcatend_date is not None:
            self.dcatend_date = dcatend_date

    @property
    def id(self):
        """Gets the id of this DctPeriodOfTime.  # noqa: E501


        :return: The id of this DctPeriodOfTime.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DctPeriodOfTime.


        :param id: The id of this DctPeriodOfTime.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def type(self):
        """Gets the type of this DctPeriodOfTime.  # noqa: E501


        :return: The type of this DctPeriodOfTime.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DctPeriodOfTime.


        :param type: The type of this DctPeriodOfTime.  # noqa: E501
        :type: object
        """

        self._type = type

    @property
    def dcatstart_date(self):
        """Gets the dcatstart_date of this DctPeriodOfTime.  # noqa: E501


        :return: The dcatstart_date of this DctPeriodOfTime.  # noqa: E501
        :rtype: XSDDateTime
        """
        return self._dcatstart_date

    @dcatstart_date.setter
    def dcatstart_date(self, dcatstart_date):
        """Sets the dcatstart_date of this DctPeriodOfTime.


        :param dcatstart_date: The dcatstart_date of this DctPeriodOfTime.  # noqa: E501
        :type: XSDDateTime
        """

        self._dcatstart_date = dcatstart_date

    @property
    def dcatend_date(self):
        """Gets the dcatend_date of this DctPeriodOfTime.  # noqa: E501


        :return: The dcatend_date of this DctPeriodOfTime.  # noqa: E501
        :rtype: XSDDateTime
        """
        return self._dcatend_date

    @dcatend_date.setter
    def dcatend_date(self, dcatend_date):
        """Sets the dcatend_date of this DctPeriodOfTime.


        :param dcatend_date: The dcatend_date of this DctPeriodOfTime.  # noqa: E501
        :type: XSDDateTime
        """

        self._dcatend_date = dcatend_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DctPeriodOfTime, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DctPeriodOfTime):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
