# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PersonRead(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'platform': 'object',
        'platform_resource_identifier': 'object',
        'name': 'object',
        'date_published': 'object',
        'same_as': 'object',
        'given_name': 'object',
        'surname': 'object',
        'price_per_hour_euro': 'object',
        'wants_to_be_contacted': 'object',
        'agent_identifier': 'object',
        'ai_resource_identifier': 'object',
        'aiod_entry': 'AIoDEntryRead',
        'alternate_name': 'object',
        'application_area': 'object',
        'contact': 'object',
        'contact_details': 'object',
        'creator': 'object',
        'description': 'Text',
        'expertise': 'object',
        'has_part': 'object',
        'industrial_sector': 'object',
        'is_part_of': 'object',
        'keyword': 'object',
        'language': 'object',
        'media': 'object',
        'note': 'object',
        'relevant_link': 'object',
        'relevant_resource': 'object',
        'relevant_to': 'object',
        'research_area': 'object',
        'scientific_domain': 'object',
        'identifier': 'object'
    }

    attribute_map = {
        'platform': 'platform',
        'platform_resource_identifier': 'platform_resource_identifier',
        'name': 'name',
        'date_published': 'date_published',
        'same_as': 'same_as',
        'given_name': 'given_name',
        'surname': 'surname',
        'price_per_hour_euro': 'price_per_hour_euro',
        'wants_to_be_contacted': 'wants_to_be_contacted',
        'agent_identifier': 'agent_identifier',
        'ai_resource_identifier': 'ai_resource_identifier',
        'aiod_entry': 'aiod_entry',
        'alternate_name': 'alternate_name',
        'application_area': 'application_area',
        'contact': 'contact',
        'contact_details': 'contact_details',
        'creator': 'creator',
        'description': 'description',
        'expertise': 'expertise',
        'has_part': 'has_part',
        'industrial_sector': 'industrial_sector',
        'is_part_of': 'is_part_of',
        'keyword': 'keyword',
        'language': 'language',
        'media': 'media',
        'note': 'note',
        'relevant_link': 'relevant_link',
        'relevant_resource': 'relevant_resource',
        'relevant_to': 'relevant_to',
        'research_area': 'research_area',
        'scientific_domain': 'scientific_domain',
        'identifier': 'identifier'
    }

    def __init__(self, platform=None, platform_resource_identifier=None, name=None, date_published=None, same_as=None, given_name=None, surname=None, price_per_hour_euro=None, wants_to_be_contacted=None, agent_identifier=None, ai_resource_identifier=None, aiod_entry=None, alternate_name=None, application_area=None, contact=None, contact_details=None, creator=None, description=None, expertise=None, has_part=None, industrial_sector=None, is_part_of=None, keyword=None, language=None, media=None, note=None, relevant_link=None, relevant_resource=None, relevant_to=None, research_area=None, scientific_domain=None, identifier=None):  # noqa: E501
        """PersonRead - a model defined in Swagger"""  # noqa: E501
        self._platform = None
        self._platform_resource_identifier = None
        self._name = None
        self._date_published = None
        self._same_as = None
        self._given_name = None
        self._surname = None
        self._price_per_hour_euro = None
        self._wants_to_be_contacted = None
        self._agent_identifier = None
        self._ai_resource_identifier = None
        self._aiod_entry = None
        self._alternate_name = None
        self._application_area = None
        self._contact = None
        self._contact_details = None
        self._creator = None
        self._description = None
        self._expertise = None
        self._has_part = None
        self._industrial_sector = None
        self._is_part_of = None
        self._keyword = None
        self._language = None
        self._media = None
        self._note = None
        self._relevant_link = None
        self._relevant_resource = None
        self._relevant_to = None
        self._research_area = None
        self._scientific_domain = None
        self._identifier = None
        self.discriminator = None
        if platform is not None:
            self.platform = platform
        if platform_resource_identifier is not None:
            self.platform_resource_identifier = platform_resource_identifier
        self.name = name
        if date_published is not None:
            self.date_published = date_published
        if same_as is not None:
            self.same_as = same_as
        if given_name is not None:
            self.given_name = given_name
        if surname is not None:
            self.surname = surname
        if price_per_hour_euro is not None:
            self.price_per_hour_euro = price_per_hour_euro
        if wants_to_be_contacted is not None:
            self.wants_to_be_contacted = wants_to_be_contacted
        if agent_identifier is not None:
            self.agent_identifier = agent_identifier
        if ai_resource_identifier is not None:
            self.ai_resource_identifier = ai_resource_identifier
        if aiod_entry is not None:
            self.aiod_entry = aiod_entry
        if alternate_name is not None:
            self.alternate_name = alternate_name
        if application_area is not None:
            self.application_area = application_area
        if contact is not None:
            self.contact = contact
        if contact_details is not None:
            self.contact_details = contact_details
        if creator is not None:
            self.creator = creator
        if description is not None:
            self.description = description
        if expertise is not None:
            self.expertise = expertise
        if has_part is not None:
            self.has_part = has_part
        if industrial_sector is not None:
            self.industrial_sector = industrial_sector
        if is_part_of is not None:
            self.is_part_of = is_part_of
        if keyword is not None:
            self.keyword = keyword
        if language is not None:
            self.language = language
        if media is not None:
            self.media = media
        if note is not None:
            self.note = note
        if relevant_link is not None:
            self.relevant_link = relevant_link
        if relevant_resource is not None:
            self.relevant_resource = relevant_resource
        if relevant_to is not None:
            self.relevant_to = relevant_to
        if research_area is not None:
            self.research_area = research_area
        if scientific_domain is not None:
            self.scientific_domain = scientific_domain
        self.identifier = identifier

    @property
    def platform(self):
        """Gets the platform of this PersonRead.  # noqa: E501

        The external platform from which this resource originates. Leave empty if this item originates from AIoD. If platform is not None, the platform_resource_identifier should be set as well.  # noqa: E501

        :return: The platform of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._platform

    @platform.setter
    def platform(self, platform):
        """Sets the platform of this PersonRead.

        The external platform from which this resource originates. Leave empty if this item originates from AIoD. If platform is not None, the platform_resource_identifier should be set as well.  # noqa: E501

        :param platform: The platform of this PersonRead.  # noqa: E501
        :type: object
        """

        self._platform = platform

    @property
    def platform_resource_identifier(self):
        """Gets the platform_resource_identifier of this PersonRead.  # noqa: E501

        A unique identifier issued by the external platform that's specified in 'platform'. Leave empty if this item is not part of an external platform.  # noqa: E501

        :return: The platform_resource_identifier of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._platform_resource_identifier

    @platform_resource_identifier.setter
    def platform_resource_identifier(self, platform_resource_identifier):
        """Sets the platform_resource_identifier of this PersonRead.

        A unique identifier issued by the external platform that's specified in 'platform'. Leave empty if this item is not part of an external platform.  # noqa: E501

        :param platform_resource_identifier: The platform_resource_identifier of this PersonRead.  # noqa: E501
        :type: object
        """

        self._platform_resource_identifier = platform_resource_identifier

    @property
    def name(self):
        """Gets the name of this PersonRead.  # noqa: E501


        :return: The name of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PersonRead.


        :param name: The name of this PersonRead.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def date_published(self):
        """Gets the date_published of this PersonRead.  # noqa: E501

        The datetime (utc) on which this resource was first published on an external platform. Note the difference between `.aiod_entry.date_created` and `.date_published`: the former is automatically set to the datetime the resource was created on AIoD, while the latter can optionally be set to an earlier datetime that the resource was published on an external platform.  # noqa: E501

        :return: The date_published of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._date_published

    @date_published.setter
    def date_published(self, date_published):
        """Sets the date_published of this PersonRead.

        The datetime (utc) on which this resource was first published on an external platform. Note the difference between `.aiod_entry.date_created` and `.date_published`: the former is automatically set to the datetime the resource was created on AIoD, while the latter can optionally be set to an earlier datetime that the resource was published on an external platform.  # noqa: E501

        :param date_published: The date_published of this PersonRead.  # noqa: E501
        :type: object
        """

        self._date_published = date_published

    @property
    def same_as(self):
        """Gets the same_as of this PersonRead.  # noqa: E501

        Url of a reference Web page that unambiguously indicates this resource's identity.  # noqa: E501

        :return: The same_as of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._same_as

    @same_as.setter
    def same_as(self, same_as):
        """Sets the same_as of this PersonRead.

        Url of a reference Web page that unambiguously indicates this resource's identity.  # noqa: E501

        :param same_as: The same_as of this PersonRead.  # noqa: E501
        :type: object
        """

        self._same_as = same_as

    @property
    def given_name(self):
        """Gets the given_name of this PersonRead.  # noqa: E501

        Also known as forename or first name. The part of the personal name that identifies a person, potentially with a middle name as well.  # noqa: E501

        :return: The given_name of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._given_name

    @given_name.setter
    def given_name(self, given_name):
        """Sets the given_name of this PersonRead.

        Also known as forename or first name. The part of the personal name that identifies a person, potentially with a middle name as well.  # noqa: E501

        :param given_name: The given_name of this PersonRead.  # noqa: E501
        :type: object
        """

        self._given_name = given_name

    @property
    def surname(self):
        """Gets the surname of this PersonRead.  # noqa: E501

        Also known as last name or family name. The mostly hereditary part of the personal name.  # noqa: E501

        :return: The surname of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._surname

    @surname.setter
    def surname(self, surname):
        """Sets the surname of this PersonRead.

        Also known as last name or family name. The mostly hereditary part of the personal name.  # noqa: E501

        :param surname: The surname of this PersonRead.  # noqa: E501
        :type: object
        """

        self._surname = surname

    @property
    def price_per_hour_euro(self):
        """Gets the price_per_hour_euro of this PersonRead.  # noqa: E501

        A ballpark figure of the per hour cost to hire this person.  # noqa: E501

        :return: The price_per_hour_euro of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._price_per_hour_euro

    @price_per_hour_euro.setter
    def price_per_hour_euro(self, price_per_hour_euro):
        """Sets the price_per_hour_euro of this PersonRead.

        A ballpark figure of the per hour cost to hire this person.  # noqa: E501

        :param price_per_hour_euro: The price_per_hour_euro of this PersonRead.  # noqa: E501
        :type: object
        """

        self._price_per_hour_euro = price_per_hour_euro

    @property
    def wants_to_be_contacted(self):
        """Gets the wants_to_be_contacted of this PersonRead.  # noqa: E501

        Does this person want to be contacted about new opportunities relating their expertise?  # noqa: E501

        :return: The wants_to_be_contacted of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._wants_to_be_contacted

    @wants_to_be_contacted.setter
    def wants_to_be_contacted(self, wants_to_be_contacted):
        """Sets the wants_to_be_contacted of this PersonRead.

        Does this person want to be contacted about new opportunities relating their expertise?  # noqa: E501

        :param wants_to_be_contacted: The wants_to_be_contacted of this PersonRead.  # noqa: E501
        :type: object
        """

        self._wants_to_be_contacted = wants_to_be_contacted

    @property
    def agent_identifier(self):
        """Gets the agent_identifier of this PersonRead.  # noqa: E501


        :return: The agent_identifier of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._agent_identifier

    @agent_identifier.setter
    def agent_identifier(self, agent_identifier):
        """Sets the agent_identifier of this PersonRead.


        :param agent_identifier: The agent_identifier of this PersonRead.  # noqa: E501
        :type: object
        """

        self._agent_identifier = agent_identifier

    @property
    def ai_resource_identifier(self):
        """Gets the ai_resource_identifier of this PersonRead.  # noqa: E501

        This resource can be identified by its own identifier, but also by the resource_identifier.  # noqa: E501

        :return: The ai_resource_identifier of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._ai_resource_identifier

    @ai_resource_identifier.setter
    def ai_resource_identifier(self, ai_resource_identifier):
        """Sets the ai_resource_identifier of this PersonRead.

        This resource can be identified by its own identifier, but also by the resource_identifier.  # noqa: E501

        :param ai_resource_identifier: The ai_resource_identifier of this PersonRead.  # noqa: E501
        :type: object
        """

        self._ai_resource_identifier = ai_resource_identifier

    @property
    def aiod_entry(self):
        """Gets the aiod_entry of this PersonRead.  # noqa: E501


        :return: The aiod_entry of this PersonRead.  # noqa: E501
        :rtype: AIoDEntryRead
        """
        return self._aiod_entry

    @aiod_entry.setter
    def aiod_entry(self, aiod_entry):
        """Sets the aiod_entry of this PersonRead.


        :param aiod_entry: The aiod_entry of this PersonRead.  # noqa: E501
        :type: AIoDEntryRead
        """

        self._aiod_entry = aiod_entry

    @property
    def alternate_name(self):
        """Gets the alternate_name of this PersonRead.  # noqa: E501

        An alias for the item, commonly used for the resource instead of the name.  # noqa: E501

        :return: The alternate_name of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._alternate_name

    @alternate_name.setter
    def alternate_name(self, alternate_name):
        """Sets the alternate_name of this PersonRead.

        An alias for the item, commonly used for the resource instead of the name.  # noqa: E501

        :param alternate_name: The alternate_name of this PersonRead.  # noqa: E501
        :type: object
        """

        self._alternate_name = alternate_name

    @property
    def application_area(self):
        """Gets the application_area of this PersonRead.  # noqa: E501

        The objective of this AI resource.  # noqa: E501

        :return: The application_area of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._application_area

    @application_area.setter
    def application_area(self, application_area):
        """Sets the application_area of this PersonRead.

        The objective of this AI resource.  # noqa: E501

        :param application_area: The application_area of this PersonRead.  # noqa: E501
        :type: object
        """

        self._application_area = application_area

    @property
    def contact(self):
        """Gets the contact of this PersonRead.  # noqa: E501

        Contact information of persons/organisations that can be contacted about this resource.  # noqa: E501

        :return: The contact of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this PersonRead.

        Contact information of persons/organisations that can be contacted about this resource.  # noqa: E501

        :param contact: The contact of this PersonRead.  # noqa: E501
        :type: object
        """

        self._contact = contact

    @property
    def contact_details(self):
        """Gets the contact_details of this PersonRead.  # noqa: E501

        The contact details by which this person can be reached  # noqa: E501

        :return: The contact_details of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._contact_details

    @contact_details.setter
    def contact_details(self, contact_details):
        """Sets the contact_details of this PersonRead.

        The contact details by which this person can be reached  # noqa: E501

        :param contact_details: The contact_details of this PersonRead.  # noqa: E501
        :type: object
        """

        self._contact_details = contact_details

    @property
    def creator(self):
        """Gets the creator of this PersonRead.  # noqa: E501

        Contact information of persons/organisations that created this resource.  # noqa: E501

        :return: The creator of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this PersonRead.

        Contact information of persons/organisations that created this resource.  # noqa: E501

        :param creator: The creator of this PersonRead.  # noqa: E501
        :type: object
        """

        self._creator = creator

    @property
    def description(self):
        """Gets the description of this PersonRead.  # noqa: E501


        :return: The description of this PersonRead.  # noqa: E501
        :rtype: Text
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PersonRead.


        :param description: The description of this PersonRead.  # noqa: E501
        :type: Text
        """

        self._description = description

    @property
    def expertise(self):
        """Gets the expertise of this PersonRead.  # noqa: E501

        A skill this person masters.  # noqa: E501

        :return: The expertise of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._expertise

    @expertise.setter
    def expertise(self, expertise):
        """Sets the expertise of this PersonRead.

        A skill this person masters.  # noqa: E501

        :param expertise: The expertise of this PersonRead.  # noqa: E501
        :type: object
        """

        self._expertise = expertise

    @property
    def has_part(self):
        """Gets the has_part of this PersonRead.  # noqa: E501


        :return: The has_part of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._has_part

    @has_part.setter
    def has_part(self, has_part):
        """Sets the has_part of this PersonRead.


        :param has_part: The has_part of this PersonRead.  # noqa: E501
        :type: object
        """

        self._has_part = has_part

    @property
    def industrial_sector(self):
        """Gets the industrial_sector of this PersonRead.  # noqa: E501

        A business domain where a resource is or can be used.  # noqa: E501

        :return: The industrial_sector of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._industrial_sector

    @industrial_sector.setter
    def industrial_sector(self, industrial_sector):
        """Sets the industrial_sector of this PersonRead.

        A business domain where a resource is or can be used.  # noqa: E501

        :param industrial_sector: The industrial_sector of this PersonRead.  # noqa: E501
        :type: object
        """

        self._industrial_sector = industrial_sector

    @property
    def is_part_of(self):
        """Gets the is_part_of of this PersonRead.  # noqa: E501


        :return: The is_part_of of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._is_part_of

    @is_part_of.setter
    def is_part_of(self, is_part_of):
        """Sets the is_part_of of this PersonRead.


        :param is_part_of: The is_part_of of this PersonRead.  # noqa: E501
        :type: object
        """

        self._is_part_of = is_part_of

    @property
    def keyword(self):
        """Gets the keyword of this PersonRead.  # noqa: E501

        Keywords or tags used to describe this resource, providing additional context.  # noqa: E501

        :return: The keyword of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._keyword

    @keyword.setter
    def keyword(self, keyword):
        """Sets the keyword of this PersonRead.

        Keywords or tags used to describe this resource, providing additional context.  # noqa: E501

        :param keyword: The keyword of this PersonRead.  # noqa: E501
        :type: object
        """

        self._keyword = keyword

    @property
    def language(self):
        """Gets the language of this PersonRead.  # noqa: E501

        A language this person masters, in ISO639-3  # noqa: E501

        :return: The language of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this PersonRead.

        A language this person masters, in ISO639-3  # noqa: E501

        :param language: The language of this PersonRead.  # noqa: E501
        :type: object
        """

        self._language = language

    @property
    def media(self):
        """Gets the media of this PersonRead.  # noqa: E501

        Images or videos depicting the resource or associated with it.   # noqa: E501

        :return: The media of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._media

    @media.setter
    def media(self, media):
        """Sets the media of this PersonRead.

        Images or videos depicting the resource or associated with it.   # noqa: E501

        :param media: The media of this PersonRead.  # noqa: E501
        :type: object
        """

        self._media = media

    @property
    def note(self):
        """Gets the note of this PersonRead.  # noqa: E501

        Notes on this AI resource.  # noqa: E501

        :return: The note of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this PersonRead.

        Notes on this AI resource.  # noqa: E501

        :param note: The note of this PersonRead.  # noqa: E501
        :type: object
        """

        self._note = note

    @property
    def relevant_link(self):
        """Gets the relevant_link of this PersonRead.  # noqa: E501

        URLs of relevant resources. These resources should not be part of AIoD (use relevant_resource otherwise). This field should only be used if there is no more specific field.  # noqa: E501

        :return: The relevant_link of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._relevant_link

    @relevant_link.setter
    def relevant_link(self, relevant_link):
        """Sets the relevant_link of this PersonRead.

        URLs of relevant resources. These resources should not be part of AIoD (use relevant_resource otherwise). This field should only be used if there is no more specific field.  # noqa: E501

        :param relevant_link: The relevant_link of this PersonRead.  # noqa: E501
        :type: object
        """

        self._relevant_link = relevant_link

    @property
    def relevant_resource(self):
        """Gets the relevant_resource of this PersonRead.  # noqa: E501


        :return: The relevant_resource of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._relevant_resource

    @relevant_resource.setter
    def relevant_resource(self, relevant_resource):
        """Sets the relevant_resource of this PersonRead.


        :param relevant_resource: The relevant_resource of this PersonRead.  # noqa: E501
        :type: object
        """

        self._relevant_resource = relevant_resource

    @property
    def relevant_to(self):
        """Gets the relevant_to of this PersonRead.  # noqa: E501


        :return: The relevant_to of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._relevant_to

    @relevant_to.setter
    def relevant_to(self, relevant_to):
        """Sets the relevant_to of this PersonRead.


        :param relevant_to: The relevant_to of this PersonRead.  # noqa: E501
        :type: object
        """

        self._relevant_to = relevant_to

    @property
    def research_area(self):
        """Gets the research_area of this PersonRead.  # noqa: E501

        The research area is similar to the scientific_domain, but more high-level.  # noqa: E501

        :return: The research_area of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._research_area

    @research_area.setter
    def research_area(self, research_area):
        """Sets the research_area of this PersonRead.

        The research area is similar to the scientific_domain, but more high-level.  # noqa: E501

        :param research_area: The research_area of this PersonRead.  # noqa: E501
        :type: object
        """

        self._research_area = research_area

    @property
    def scientific_domain(self):
        """Gets the scientific_domain of this PersonRead.  # noqa: E501

        The scientific domain is related to the methods with which an objective is reached.  # noqa: E501

        :return: The scientific_domain of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._scientific_domain

    @scientific_domain.setter
    def scientific_domain(self, scientific_domain):
        """Sets the scientific_domain of this PersonRead.

        The scientific domain is related to the methods with which an objective is reached.  # noqa: E501

        :param scientific_domain: The scientific_domain of this PersonRead.  # noqa: E501
        :type: object
        """

        self._scientific_domain = scientific_domain

    @property
    def identifier(self):
        """Gets the identifier of this PersonRead.  # noqa: E501


        :return: The identifier of this PersonRead.  # noqa: E501
        :rtype: object
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this PersonRead.


        :param identifier: The identifier of this PersonRead.  # noqa: E501
        :type: object
        """
        if identifier is None:
            raise ValueError("Invalid value for `identifier`, must not be `None`")  # noqa: E501

        self._identifier = identifier

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PersonRead, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PersonRead):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
