# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'platform': 'object',
        'platform_resource_identifier': 'object',
        'name': 'object',
        'date_published': 'object',
        'same_as': 'object',
        'start_date': 'object',
        'end_date': 'object',
        'total_cost_euro': 'object',
        'aiod_entry': 'AIoDEntryCreate',
        'alternate_name': 'object',
        'application_area': 'object',
        'contact': 'object',
        'coordinator': 'object',
        'creator': 'object',
        'description': 'Text',
        'funder': 'object',
        'has_part': 'object',
        'industrial_sector': 'object',
        'is_part_of': 'object',
        'keyword': 'object',
        'media': 'object',
        'note': 'object',
        'participant': 'object',
        'produced': 'object',
        'relevant_link': 'object',
        'relevant_resource': 'object',
        'relevant_to': 'object',
        'research_area': 'object',
        'scientific_domain': 'object',
        'used': 'object'
    }

    attribute_map = {
        'platform': 'platform',
        'platform_resource_identifier': 'platform_resource_identifier',
        'name': 'name',
        'date_published': 'date_published',
        'same_as': 'same_as',
        'start_date': 'start_date',
        'end_date': 'end_date',
        'total_cost_euro': 'total_cost_euro',
        'aiod_entry': 'aiod_entry',
        'alternate_name': 'alternate_name',
        'application_area': 'application_area',
        'contact': 'contact',
        'coordinator': 'coordinator',
        'creator': 'creator',
        'description': 'description',
        'funder': 'funder',
        'has_part': 'has_part',
        'industrial_sector': 'industrial_sector',
        'is_part_of': 'is_part_of',
        'keyword': 'keyword',
        'media': 'media',
        'note': 'note',
        'participant': 'participant',
        'produced': 'produced',
        'relevant_link': 'relevant_link',
        'relevant_resource': 'relevant_resource',
        'relevant_to': 'relevant_to',
        'research_area': 'research_area',
        'scientific_domain': 'scientific_domain',
        'used': 'used'
    }

    def __init__(self, platform=None, platform_resource_identifier=None, name=None, date_published=None, same_as=None, start_date=None, end_date=None, total_cost_euro=None, aiod_entry=None, alternate_name=None, application_area=None, contact=None, coordinator=None, creator=None, description=None, funder=None, has_part=None, industrial_sector=None, is_part_of=None, keyword=None, media=None, note=None, participant=None, produced=None, relevant_link=None, relevant_resource=None, relevant_to=None, research_area=None, scientific_domain=None, used=None):  # noqa: E501
        """ProjectCreate - a model defined in Swagger"""  # noqa: E501
        self._platform = None
        self._platform_resource_identifier = None
        self._name = None
        self._date_published = None
        self._same_as = None
        self._start_date = None
        self._end_date = None
        self._total_cost_euro = None
        self._aiod_entry = None
        self._alternate_name = None
        self._application_area = None
        self._contact = None
        self._coordinator = None
        self._creator = None
        self._description = None
        self._funder = None
        self._has_part = None
        self._industrial_sector = None
        self._is_part_of = None
        self._keyword = None
        self._media = None
        self._note = None
        self._participant = None
        self._produced = None
        self._relevant_link = None
        self._relevant_resource = None
        self._relevant_to = None
        self._research_area = None
        self._scientific_domain = None
        self._used = None
        self.discriminator = None
        if platform is not None:
            self.platform = platform
        if platform_resource_identifier is not None:
            self.platform_resource_identifier = platform_resource_identifier
        self.name = name
        if date_published is not None:
            self.date_published = date_published
        if same_as is not None:
            self.same_as = same_as
        if start_date is not None:
            self.start_date = start_date
        if end_date is not None:
            self.end_date = end_date
        if total_cost_euro is not None:
            self.total_cost_euro = total_cost_euro
        if aiod_entry is not None:
            self.aiod_entry = aiod_entry
        if alternate_name is not None:
            self.alternate_name = alternate_name
        if application_area is not None:
            self.application_area = application_area
        if contact is not None:
            self.contact = contact
        if coordinator is not None:
            self.coordinator = coordinator
        if creator is not None:
            self.creator = creator
        if description is not None:
            self.description = description
        if funder is not None:
            self.funder = funder
        if has_part is not None:
            self.has_part = has_part
        if industrial_sector is not None:
            self.industrial_sector = industrial_sector
        if is_part_of is not None:
            self.is_part_of = is_part_of
        if keyword is not None:
            self.keyword = keyword
        if media is not None:
            self.media = media
        if note is not None:
            self.note = note
        if participant is not None:
            self.participant = participant
        if produced is not None:
            self.produced = produced
        if relevant_link is not None:
            self.relevant_link = relevant_link
        if relevant_resource is not None:
            self.relevant_resource = relevant_resource
        if relevant_to is not None:
            self.relevant_to = relevant_to
        if research_area is not None:
            self.research_area = research_area
        if scientific_domain is not None:
            self.scientific_domain = scientific_domain
        if used is not None:
            self.used = used

    @property
    def platform(self):
        """Gets the platform of this ProjectCreate.  # noqa: E501

        The external platform from which this resource originates. Leave empty if this item originates from AIoD. If platform is not None, the platform_resource_identifier should be set as well.  # noqa: E501

        :return: The platform of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._platform

    @platform.setter
    def platform(self, platform):
        """Sets the platform of this ProjectCreate.

        The external platform from which this resource originates. Leave empty if this item originates from AIoD. If platform is not None, the platform_resource_identifier should be set as well.  # noqa: E501

        :param platform: The platform of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._platform = platform

    @property
    def platform_resource_identifier(self):
        """Gets the platform_resource_identifier of this ProjectCreate.  # noqa: E501

        A unique identifier issued by the external platform that's specified in 'platform'. Leave empty if this item is not part of an external platform.  # noqa: E501

        :return: The platform_resource_identifier of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._platform_resource_identifier

    @platform_resource_identifier.setter
    def platform_resource_identifier(self, platform_resource_identifier):
        """Sets the platform_resource_identifier of this ProjectCreate.

        A unique identifier issued by the external platform that's specified in 'platform'. Leave empty if this item is not part of an external platform.  # noqa: E501

        :param platform_resource_identifier: The platform_resource_identifier of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._platform_resource_identifier = platform_resource_identifier

    @property
    def name(self):
        """Gets the name of this ProjectCreate.  # noqa: E501


        :return: The name of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectCreate.


        :param name: The name of this ProjectCreate.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def date_published(self):
        """Gets the date_published of this ProjectCreate.  # noqa: E501

        The datetime (utc) on which this resource was first published on an external platform. Note the difference between `.aiod_entry.date_created` and `.date_published`: the former is automatically set to the datetime the resource was created on AIoD, while the latter can optionally be set to an earlier datetime that the resource was published on an external platform.  # noqa: E501

        :return: The date_published of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._date_published

    @date_published.setter
    def date_published(self, date_published):
        """Sets the date_published of this ProjectCreate.

        The datetime (utc) on which this resource was first published on an external platform. Note the difference between `.aiod_entry.date_created` and `.date_published`: the former is automatically set to the datetime the resource was created on AIoD, while the latter can optionally be set to an earlier datetime that the resource was published on an external platform.  # noqa: E501

        :param date_published: The date_published of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._date_published = date_published

    @property
    def same_as(self):
        """Gets the same_as of this ProjectCreate.  # noqa: E501

        Url of a reference Web page that unambiguously indicates this resource's identity.  # noqa: E501

        :return: The same_as of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._same_as

    @same_as.setter
    def same_as(self, same_as):
        """Sets the same_as of this ProjectCreate.

        Url of a reference Web page that unambiguously indicates this resource's identity.  # noqa: E501

        :param same_as: The same_as of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._same_as = same_as

    @property
    def start_date(self):
        """Gets the start_date of this ProjectCreate.  # noqa: E501

        The start date and time of the project as ISO 8601.  # noqa: E501

        :return: The start_date of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this ProjectCreate.

        The start date and time of the project as ISO 8601.  # noqa: E501

        :param start_date: The start_date of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this ProjectCreate.  # noqa: E501

        The end date and time of the project as ISO 8601.  # noqa: E501

        :return: The end_date of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this ProjectCreate.

        The end date and time of the project as ISO 8601.  # noqa: E501

        :param end_date: The end_date of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._end_date = end_date

    @property
    def total_cost_euro(self):
        """Gets the total_cost_euro of this ProjectCreate.  # noqa: E501

        The total budget of the project in euros.  # noqa: E501

        :return: The total_cost_euro of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._total_cost_euro

    @total_cost_euro.setter
    def total_cost_euro(self, total_cost_euro):
        """Sets the total_cost_euro of this ProjectCreate.

        The total budget of the project in euros.  # noqa: E501

        :param total_cost_euro: The total_cost_euro of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._total_cost_euro = total_cost_euro

    @property
    def aiod_entry(self):
        """Gets the aiod_entry of this ProjectCreate.  # noqa: E501


        :return: The aiod_entry of this ProjectCreate.  # noqa: E501
        :rtype: AIoDEntryCreate
        """
        return self._aiod_entry

    @aiod_entry.setter
    def aiod_entry(self, aiod_entry):
        """Sets the aiod_entry of this ProjectCreate.


        :param aiod_entry: The aiod_entry of this ProjectCreate.  # noqa: E501
        :type: AIoDEntryCreate
        """

        self._aiod_entry = aiod_entry

    @property
    def alternate_name(self):
        """Gets the alternate_name of this ProjectCreate.  # noqa: E501

        An alias for the item, commonly used for the resource instead of the name.  # noqa: E501

        :return: The alternate_name of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._alternate_name

    @alternate_name.setter
    def alternate_name(self, alternate_name):
        """Sets the alternate_name of this ProjectCreate.

        An alias for the item, commonly used for the resource instead of the name.  # noqa: E501

        :param alternate_name: The alternate_name of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._alternate_name = alternate_name

    @property
    def application_area(self):
        """Gets the application_area of this ProjectCreate.  # noqa: E501

        The objective of this AI resource.  # noqa: E501

        :return: The application_area of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._application_area

    @application_area.setter
    def application_area(self, application_area):
        """Sets the application_area of this ProjectCreate.

        The objective of this AI resource.  # noqa: E501

        :param application_area: The application_area of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._application_area = application_area

    @property
    def contact(self):
        """Gets the contact of this ProjectCreate.  # noqa: E501

        Contact information of persons/organisations that can be contacted about this resource.  # noqa: E501

        :return: The contact of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this ProjectCreate.

        Contact information of persons/organisations that can be contacted about this resource.  # noqa: E501

        :param contact: The contact of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._contact = contact

    @property
    def coordinator(self):
        """Gets the coordinator of this ProjectCreate.  # noqa: E501

        The coordinating organisation of this project.  # noqa: E501

        :return: The coordinator of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._coordinator

    @coordinator.setter
    def coordinator(self, coordinator):
        """Sets the coordinator of this ProjectCreate.

        The coordinating organisation of this project.  # noqa: E501

        :param coordinator: The coordinator of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._coordinator = coordinator

    @property
    def creator(self):
        """Gets the creator of this ProjectCreate.  # noqa: E501

        Contact information of persons/organisations that created this resource.  # noqa: E501

        :return: The creator of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this ProjectCreate.

        Contact information of persons/organisations that created this resource.  # noqa: E501

        :param creator: The creator of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._creator = creator

    @property
    def description(self):
        """Gets the description of this ProjectCreate.  # noqa: E501


        :return: The description of this ProjectCreate.  # noqa: E501
        :rtype: Text
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ProjectCreate.


        :param description: The description of this ProjectCreate.  # noqa: E501
        :type: Text
        """

        self._description = description

    @property
    def funder(self):
        """Gets the funder of this ProjectCreate.  # noqa: E501

        Identifiers of organizations that support this project through some kind of financial contribution.   # noqa: E501

        :return: The funder of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._funder

    @funder.setter
    def funder(self, funder):
        """Sets the funder of this ProjectCreate.

        Identifiers of organizations that support this project through some kind of financial contribution.   # noqa: E501

        :param funder: The funder of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._funder = funder

    @property
    def has_part(self):
        """Gets the has_part of this ProjectCreate.  # noqa: E501


        :return: The has_part of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._has_part

    @has_part.setter
    def has_part(self, has_part):
        """Sets the has_part of this ProjectCreate.


        :param has_part: The has_part of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._has_part = has_part

    @property
    def industrial_sector(self):
        """Gets the industrial_sector of this ProjectCreate.  # noqa: E501

        A business domain where a resource is or can be used.  # noqa: E501

        :return: The industrial_sector of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._industrial_sector

    @industrial_sector.setter
    def industrial_sector(self, industrial_sector):
        """Sets the industrial_sector of this ProjectCreate.

        A business domain where a resource is or can be used.  # noqa: E501

        :param industrial_sector: The industrial_sector of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._industrial_sector = industrial_sector

    @property
    def is_part_of(self):
        """Gets the is_part_of of this ProjectCreate.  # noqa: E501


        :return: The is_part_of of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._is_part_of

    @is_part_of.setter
    def is_part_of(self, is_part_of):
        """Sets the is_part_of of this ProjectCreate.


        :param is_part_of: The is_part_of of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._is_part_of = is_part_of

    @property
    def keyword(self):
        """Gets the keyword of this ProjectCreate.  # noqa: E501

        Keywords or tags used to describe this resource, providing additional context.  # noqa: E501

        :return: The keyword of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._keyword

    @keyword.setter
    def keyword(self, keyword):
        """Sets the keyword of this ProjectCreate.

        Keywords or tags used to describe this resource, providing additional context.  # noqa: E501

        :param keyword: The keyword of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._keyword = keyword

    @property
    def media(self):
        """Gets the media of this ProjectCreate.  # noqa: E501

        Images or videos depicting the resource or associated with it.   # noqa: E501

        :return: The media of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._media

    @media.setter
    def media(self, media):
        """Sets the media of this ProjectCreate.

        Images or videos depicting the resource or associated with it.   # noqa: E501

        :param media: The media of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._media = media

    @property
    def note(self):
        """Gets the note of this ProjectCreate.  # noqa: E501

        Notes on this AI resource.  # noqa: E501

        :return: The note of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this ProjectCreate.

        Notes on this AI resource.  # noqa: E501

        :param note: The note of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._note = note

    @property
    def participant(self):
        """Gets the participant of this ProjectCreate.  # noqa: E501

        Identifiers of members of this project.   # noqa: E501

        :return: The participant of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._participant

    @participant.setter
    def participant(self, participant):
        """Sets the participant of this ProjectCreate.

        Identifiers of members of this project.   # noqa: E501

        :param participant: The participant of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._participant = participant

    @property
    def produced(self):
        """Gets the produced of this ProjectCreate.  # noqa: E501

        Identifiers of AIAssets that are created in this project.  # noqa: E501

        :return: The produced of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._produced

    @produced.setter
    def produced(self, produced):
        """Sets the produced of this ProjectCreate.

        Identifiers of AIAssets that are created in this project.  # noqa: E501

        :param produced: The produced of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._produced = produced

    @property
    def relevant_link(self):
        """Gets the relevant_link of this ProjectCreate.  # noqa: E501

        URLs of relevant resources. These resources should not be part of AIoD (use relevant_resource otherwise). This field should only be used if there is no more specific field.  # noqa: E501

        :return: The relevant_link of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._relevant_link

    @relevant_link.setter
    def relevant_link(self, relevant_link):
        """Sets the relevant_link of this ProjectCreate.

        URLs of relevant resources. These resources should not be part of AIoD (use relevant_resource otherwise). This field should only be used if there is no more specific field.  # noqa: E501

        :param relevant_link: The relevant_link of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._relevant_link = relevant_link

    @property
    def relevant_resource(self):
        """Gets the relevant_resource of this ProjectCreate.  # noqa: E501


        :return: The relevant_resource of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._relevant_resource

    @relevant_resource.setter
    def relevant_resource(self, relevant_resource):
        """Sets the relevant_resource of this ProjectCreate.


        :param relevant_resource: The relevant_resource of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._relevant_resource = relevant_resource

    @property
    def relevant_to(self):
        """Gets the relevant_to of this ProjectCreate.  # noqa: E501


        :return: The relevant_to of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._relevant_to

    @relevant_to.setter
    def relevant_to(self, relevant_to):
        """Sets the relevant_to of this ProjectCreate.


        :param relevant_to: The relevant_to of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._relevant_to = relevant_to

    @property
    def research_area(self):
        """Gets the research_area of this ProjectCreate.  # noqa: E501

        The research area is similar to the scientific_domain, but more high-level.  # noqa: E501

        :return: The research_area of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._research_area

    @research_area.setter
    def research_area(self, research_area):
        """Sets the research_area of this ProjectCreate.

        The research area is similar to the scientific_domain, but more high-level.  # noqa: E501

        :param research_area: The research_area of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._research_area = research_area

    @property
    def scientific_domain(self):
        """Gets the scientific_domain of this ProjectCreate.  # noqa: E501

        The scientific domain is related to the methods with which an objective is reached.  # noqa: E501

        :return: The scientific_domain of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._scientific_domain

    @scientific_domain.setter
    def scientific_domain(self, scientific_domain):
        """Sets the scientific_domain of this ProjectCreate.

        The scientific domain is related to the methods with which an objective is reached.  # noqa: E501

        :param scientific_domain: The scientific_domain of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._scientific_domain = scientific_domain

    @property
    def used(self):
        """Gets the used of this ProjectCreate.  # noqa: E501

        Identifiers of AIAssets that are used (but not created) in this project.  # noqa: E501

        :return: The used of this ProjectCreate.  # noqa: E501
        :rtype: object
        """
        return self._used

    @used.setter
    def used(self, used):
        """Sets the used of this ProjectCreate.

        Identifiers of AIAssets that are used (but not created) in this project.  # noqa: E501

        :param used: The used of this ProjectCreate.  # noqa: E501
        :type: object
        """

        self._used = used

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
