# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SchemaDotOrgContext(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vocab': 'object'
    }

    attribute_map = {
        'vocab': '@vocab'
    }

    def __init__(self, vocab=None):  # noqa: E501
        """SchemaDotOrgContext - a model defined in Swagger"""  # noqa: E501
        self._vocab = None
        self.discriminator = None
        if vocab is not None:
            self.vocab = vocab

    @property
    def vocab(self):
        """Gets the vocab of this SchemaDotOrgContext.  # noqa: E501


        :return: The vocab of this SchemaDotOrgContext.  # noqa: E501
        :rtype: object
        """
        return self._vocab

    @vocab.setter
    def vocab(self, vocab):
        """Sets the vocab of this SchemaDotOrgContext.


        :param vocab: The vocab of this SchemaDotOrgContext.  # noqa: E501
        :type: object
        """

        self._vocab = vocab

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SchemaDotOrgContext, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SchemaDotOrgContext):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
