"""Sklearn regressor."""

from aiod.models.apis import _ModelPkgRegressor


class AiodPkg__SklearnRegressors(_ModelPkgRegressor):
    _tags = {
        "pkg_id": "__multiple",
        "python_dependencies": "scikit-learn",
        "pkg_pypi_name": "scikit-learn",
    }

    _obj_dict = {
        'ARDRegression': 'sklearn.linear_model._bayes.ARDRegression',
        'AdaBoostRegressor': 'sklearn.ensemble._weight_boosting.AdaBoostRegressor',
        'BaggingRegressor': 'sklearn.ensemble._bagging.BaggingRegressor',
        'BayesianRidge': 'sklearn.linear_model._bayes.BayesianRidge',
        'CCA': 'sklearn.cross_decomposition._pls.CCA',
        'DecisionTreeRegressor': 'sklearn.tree._classes.DecisionTreeRegressor',
        'DummyRegressor': 'sklearn.dummy.DummyRegressor',
        'ElasticNet': 'sklearn.linear_model._coordinate_descent.ElasticNet',
        'ElasticNetCV': 'sklearn.linear_model._coordinate_descent.ElasticNetCV',
        'ExtraTreeRegressor': 'sklearn.tree._classes.ExtraTreeRegressor',
        'ExtraTreesRegressor': 'sklearn.ensemble._forest.ExtraTreesRegressor',
        'GammaRegressor': 'sklearn.linear_model._glm.glm.GammaRegressor',
        'GaussianProcessRegressor': 'sklearn.gaussian_process._gpr.GaussianProcessRegressor',
        'GradientBoostingRegressor': 'sklearn.ensemble._gb.GradientBoostingRegressor',
        'HistGradientBoostingRegressor': 'sklearn.ensemble._hist_gradient_boosting.gradient_boosting.HistGradientBoostingRegressor',
        'HuberRegressor': 'sklearn.linear_model._huber.HuberRegressor',
        'IsotonicRegression': 'sklearn.isotonic.IsotonicRegression',
        'KNeighborsRegressor': 'sklearn.neighbors._regression.KNeighborsRegressor',
        'KernelRidge': 'sklearn.kernel_ridge.KernelRidge',
        'Lars': 'sklearn.linear_model._least_angle.Lars',
        'LarsCV': 'sklearn.linear_model._least_angle.LarsCV',
        'Lasso': 'sklearn.linear_model._coordinate_descent.Lasso',
        'LassoCV': 'sklearn.linear_model._coordinate_descent.LassoCV',
        'LassoLars': 'sklearn.linear_model._least_angle.LassoLars',
        'LassoLarsCV': 'sklearn.linear_model._least_angle.LassoLarsCV',
        'LassoLarsIC': 'sklearn.linear_model._least_angle.LassoLarsIC',
        'LinearRegression': 'sklearn.linear_model._base.LinearRegression',
        'LinearSVR': 'sklearn.svm._classes.LinearSVR',
        'MLPRegressor': 'sklearn.neural_network._multilayer_perceptron.MLPRegressor',
        'MultiOutputRegressor': 'sklearn.multioutput.MultiOutputRegressor',
        'MultiTaskElasticNet': 'sklearn.linear_model._coordinate_descent.MultiTaskElasticNet',
        'MultiTaskElasticNetCV': 'sklearn.linear_model._coordinate_descent.MultiTaskElasticNetCV',
        'MultiTaskLasso': 'sklearn.linear_model._coordinate_descent.MultiTaskLasso',
        'MultiTaskLassoCV': 'sklearn.linear_model._coordinate_descent.MultiTaskLassoCV',
        'NuSVR': 'sklearn.svm._classes.NuSVR',
        'OrthogonalMatchingPursuit': 'sklearn.linear_model._omp.OrthogonalMatchingPursuit',
        'OrthogonalMatchingPursuitCV': 'sklearn.linear_model._omp.OrthogonalMatchingPursuitCV',
        'PLSCanonical': 'sklearn.cross_decomposition._pls.PLSCanonical',
        'PLSRegression': 'sklearn.cross_decomposition._pls.PLSRegression',
        'PassiveAggressiveRegressor': 'sklearn.linear_model._passive_aggressive.PassiveAggressiveRegressor',
        'PoissonRegressor': 'sklearn.linear_model._glm.glm.PoissonRegressor',
        'QuantileRegressor': 'sklearn.linear_model._quantile.QuantileRegressor',
        'RANSACRegressor': 'sklearn.linear_model._ransac.RANSACRegressor',
        'RadiusNeighborsRegressor': 'sklearn.neighbors._regression.RadiusNeighborsRegressor',
        'RandomForestRegressor': 'sklearn.ensemble._forest.RandomForestRegressor',
        'RegressorChain': 'sklearn.multioutput.RegressorChain',
        'Ridge': 'sklearn.linear_model._ridge.Ridge',
        'RidgeCV': 'sklearn.linear_model._ridge.RidgeCV',
        'SGDRegressor': 'sklearn.linear_model._stochastic_gradient.SGDRegressor',
        'SVR': 'sklearn.svm._classes.SVR',
        'StackingRegressor': 'sklearn.ensemble._stacking.StackingRegressor',
        'TheilSenRegressor': 'sklearn.linear_model._theil_sen.TheilSenRegressor',
        'TransformedTargetRegressor': 'sklearn.compose._target.TransformedTargetRegressor',
        'TweedieRegressor': 'sklearn.linear_model._glm.glm.TweedieRegressor',
        'VotingRegressor': 'sklearn.ensemble._voting.VotingRegressor'
    }