# ruff: noqa: E501
"""Feature-engine model package."""

from aiod.models.apis import _ModelPkgSklearnEstimator


class AiodPkg__FeatureEngine(_ModelPkgSklearnEstimator):
    _tags = {
        "pkg_id": "__multiple",
        "python_dependencies": "feature_engine",
        "pkg_pypi_name": "feature-engine",
        "object_types": ["transformer", "classifier", "regressor"],
    }

    _obj_dict = {
        "AddMissingIndicator": "feature_engine.imputation.missing_indicator.AddMissingIndicator",
        "ArbitraryDiscretiser": "feature_engine.discretisation.arbitrary.ArbitraryDiscretiser",
        "ArbitraryNumberImputer": "feature_engine.imputation.arbitrary_number.ArbitraryNumberImputer",
        "ArbitraryOutlierCapper": "feature_engine.outliers.artbitrary.ArbitraryOutlierCapper",
        "ArcSinhTransformer": "feature_engine.transformation.arcsinh.ArcSinhTransformer",
        "ArcsinTransformer": "feature_engine.transformation.arcsin.ArcsinTransformer",
        "BoxCoxTransformer": "feature_engine.transformation.boxcox.BoxCoxTransformer",
        "CategoricalImputer": "feature_engine.imputation.categorical.CategoricalImputer",
        "CountFrequencyEncoder": "feature_engine.encoding.count_frequency.CountFrequencyEncoder",
        "CyclicalFeatures": "feature_engine.creation.cyclical_features.CyclicalFeatures",
        "DatetimeFeatures": "feature_engine.datetime.datetime.DatetimeFeatures",
        "DatetimeOrdinal": "feature_engine.datetime.datetime_ordinal.DatetimeOrdinal",
        "DatetimeSubtraction": "feature_engine.datetime.datetime_subtraction.DatetimeSubtraction",
        "DecisionTreeDiscretiser": "feature_engine.discretisation.decision_tree.DecisionTreeDiscretiser",
        "DecisionTreeEncoder": "feature_engine.encoding.decision_tree.DecisionTreeEncoder",
        "DecisionTreeFeatures": "feature_engine.creation.decision_tree_features.DecisionTreeFeatures",
        "DropConstantFeatures": "feature_engine.selection.drop_constant_features.DropConstantFeatures",
        "DropCorrelatedFeatures": "feature_engine.selection.drop_correlated_features.DropCorrelatedFeatures",
        "DropDuplicateFeatures": "feature_engine.selection.drop_duplicate_features.DropDuplicateFeatures",
        "DropFeatures": "feature_engine.selection.drop_features.DropFeatures",
        "DropHighPSIFeatures": "feature_engine.selection.drop_psi_features.DropHighPSIFeatures",
        "DropMissingData": "feature_engine.imputation.drop_missing_data.DropMissingData",
        "EndTailImputer": "feature_engine.imputation.end_tail.EndTailImputer",
        "EqualFrequencyDiscretiser": "feature_engine.discretisation.equal_frequency.EqualFrequencyDiscretiser",
        "EqualWidthDiscretiser": "feature_engine.discretisation.equal_width.EqualWidthDiscretiser",
        "ExpandingWindowFeatures": "feature_engine.timeseries.forecasting.expanding_window_features.ExpandingWindowFeatures",
        "GeoDistanceFeatures": "feature_engine.creation.geo_features.GeoDistanceFeatures",
        "GeometricWidthDiscretiser": "feature_engine.discretisation.geometric_width.GeometricWidthDiscretiser",
        "LagFeatures": "feature_engine.timeseries.forecasting.lag_features.LagFeatures",
        "LogCpTransformer": "feature_engine.transformation.log.LogCpTransformer",
        "LogTransformer": "feature_engine.transformation.log.LogTransformer",
        "MRMR": "feature_engine.selection.mrmr.MRMR",
        "MatchCategories": "feature_engine.preprocessing.match_categories.MatchCategories",
        "MatchVariables": "feature_engine.preprocessing.match_columns.MatchVariables",
        "MathFeatures": "feature_engine.creation.math_features.MathFeatures",
        "MeanEncoder": "feature_engine.encoding.mean_encoding.MeanEncoder",
        "MeanMedianImputer": "feature_engine.imputation.mean_median.MeanMedianImputer",
        "MeanNormalizationScaler": "feature_engine.scaling.mean_normalization.MeanNormalizationScaler",
        "OneHotEncoder": "feature_engine.encoding.one_hot.OneHotEncoder",
        "OrdinalEncoder": "feature_engine.encoding.ordinal.OrdinalEncoder",
        "OutlierTrimmer": "feature_engine.outliers.trimmer.OutlierTrimmer",
        "FeatureEnginePipeline": "feature_engine.pipeline.Pipeline",
        "PowerTransformer": "feature_engine.transformation.power.PowerTransformer",
        "ProbeFeatureSelection": "feature_engine.selection.probe_feature_selection.ProbeFeatureSelection",
        "RandomSampleImputer": "feature_engine.imputation.random_sample.RandomSampleImputer",
        "RareLabelEncoder": "feature_engine.encoding.rare_label.RareLabelEncoder",
        "ReciprocalTransformer": "feature_engine.transformation.reciprocal.ReciprocalTransformer",
        "RecursiveFeatureAddition": "feature_engine.selection.recursive_feature_addition.RecursiveFeatureAddition",
        "RecursiveFeatureElimination": "feature_engine.selection.recursive_feature_elimination.RecursiveFeatureElimination",
        "RelativeFeatures": "feature_engine.creation.relative_features.RelativeFeatures",
        "SelectByInformationValue": "feature_engine.selection.information_value.SelectByInformationValue",
        "SelectByShuffling": "feature_engine.selection.shuffle_features.SelectByShuffling",
        "SelectBySingleFeaturePerformance": "feature_engine.selection.single_feature_performance.SelectBySingleFeaturePerformance",
        "SelectByTargetMeanPerformance": "feature_engine.selection.target_mean_selection.SelectByTargetMeanPerformance",
        "SklearnTransformerWrapper": "feature_engine.wrappers.wrappers.SklearnTransformerWrapper",
        "SmartCorrelatedSelection": "feature_engine.selection.smart_correlation_selection.SmartCorrelatedSelection",
        "StringSimilarityEncoder": "feature_engine.encoding.similarity_encoder.StringSimilarityEncoder",
        "TargetMeanClassifier": "feature_engine.encoding.target_mean.TargetMeanClassifier",
        "TargetMeanRegressor": "feature_engine.encoding.target_mean.TargetMeanRegressor",
        "TextFeatures": "feature_engine.text.text_features.TextFeatures",
        "WindowFeatures": "feature_engine.timeseries.forecasting.window_features.WindowFeatures",
        "Winsorizer": "feature_engine.outliers.winsorizer.Winsorizer",
        "WoEEncoder": "feature_engine.encoding.woe.WoEEncoder",
        "YeoJohnsonTransformer": "feature_engine.transformation.yeojohnson.YeoJohnsonTransformer",
    }

    _type_of_objs = {
        "AddMissingIndicator": "transformer",
        "ArbitraryDiscretiser": "transformer",
        "ArbitraryNumberImputer": "transformer",
        "ArbitraryOutlierCapper": "transformer",
        "ArcSinhTransformer": "transformer",
        "ArcsinTransformer": "transformer",
        "BoxCoxTransformer": "transformer",
        "CategoricalImputer": "transformer",
        "CountFrequencyEncoder": "transformer",
        "CyclicalFeatures": "transformer",
        "DatetimeFeatures": "transformer",
        "DatetimeOrdinal": "transformer",
        "DatetimeSubtraction": "transformer",
        "DecisionTreeDiscretiser": "transformer",
        "DecisionTreeEncoder": "transformer",
        "DecisionTreeFeatures": "transformer",
        "DropConstantFeatures": "transformer",
        "DropCorrelatedFeatures": "transformer",
        "DropDuplicateFeatures": "transformer",
        "DropFeatures": "transformer",
        "DropHighPSIFeatures": "transformer",
        "DropMissingData": "transformer",
        "EndTailImputer": "transformer",
        "EqualFrequencyDiscretiser": "transformer",
        "EqualWidthDiscretiser": "transformer",
        "ExpandingWindowFeatures": "transformer",
        "GeoDistanceFeatures": "transformer",
        "GeometricWidthDiscretiser": "transformer",
        "LagFeatures": "transformer",
        "LogCpTransformer": "transformer",
        "LogTransformer": "transformer",
        "MRMR": "transformer",
        "MatchCategories": "transformer",
        "MatchVariables": "transformer",
        "MathFeatures": "transformer",
        "MeanEncoder": "transformer",
        "MeanMedianImputer": "transformer",
        "MeanNormalizationScaler": "transformer",
        "OneHotEncoder": "transformer",
        "OrdinalEncoder": "transformer",
        "OutlierTrimmer": "transformer",
        "Pipeline": [
            "regressor",
            "outlier_detector",
            "clusterer",
            "transformer",
            "classifier",
        ],
        "PowerTransformer": "transformer",
        "ProbeFeatureSelection": "transformer",
        "RandomSampleImputer": "transformer",
        "RareLabelEncoder": "transformer",
        "ReciprocalTransformer": "transformer",
        "RecursiveFeatureAddition": "transformer",
        "RecursiveFeatureElimination": "transformer",
        "RelativeFeatures": "transformer",
        "SelectByInformationValue": "transformer",
        "SelectByShuffling": "transformer",
        "SelectBySingleFeaturePerformance": "transformer",
        "SelectByTargetMeanPerformance": "transformer",
        "SklearnTransformerWrapper": "transformer",
        "SmartCorrelatedSelection": "transformer",
        "StringSimilarityEncoder": "transformer",
        "TargetMeanClassifier": "classifier",
        "TargetMeanRegressor": "regressor",
        "TextFeatures": "transformer",
        "WindowFeatures": "transformer",
        "Winsorizer": "transformer",
        "WoEEncoder": "transformer",
        "YeoJohnsonTransformer": "transformer",
    }

    _objs_by_type = {
        "transformer": [
            "AddMissingIndicator",
            "ArbitraryDiscretiser",
            "ArbitraryNumberImputer",
            "ArbitraryOutlierCapper",
            "ArcSinhTransformer",
            "ArcsinTransformer",
            "BoxCoxTransformer",
            "CategoricalImputer",
            "CountFrequencyEncoder",
            "CyclicalFeatures",
            "DatetimeFeatures",
            "DatetimeOrdinal",
            "DatetimeSubtraction",
            "DecisionTreeDiscretiser",
            "DecisionTreeEncoder",
            "DecisionTreeFeatures",
            "DropConstantFeatures",
            "DropCorrelatedFeatures",
            "DropDuplicateFeatures",
            "DropFeatures",
            "DropHighPSIFeatures",
            "DropMissingData",
            "EndTailImputer",
            "EqualFrequencyDiscretiser",
            "EqualWidthDiscretiser",
            "ExpandingWindowFeatures",
            "GeoDistanceFeatures",
            "GeometricWidthDiscretiser",
            "LagFeatures",
            "LogCpTransformer",
            "LogTransformer",
            "MRMR",
            "MatchCategories",
            "MatchVariables",
            "MathFeatures",
            "MeanEncoder",
            "MeanMedianImputer",
            "MeanNormalizationScaler",
            "OneHotEncoder",
            "OrdinalEncoder",
            "OutlierTrimmer",
            "Pipeline",
            "PowerTransformer",
            "ProbeFeatureSelection",
            "RandomSampleImputer",
            "RareLabelEncoder",
            "ReciprocalTransformer",
            "RecursiveFeatureAddition",
            "RecursiveFeatureElimination",
            "RelativeFeatures",
            "SelectByInformationValue",
            "SelectByShuffling",
            "SelectBySingleFeaturePerformance",
            "SelectByTargetMeanPerformance",
            "SklearnTransformerWrapper",
            "SmartCorrelatedSelection",
            "StringSimilarityEncoder",
            "TextFeatures",
            "WindowFeatures",
            "Winsorizer",
            "WoEEncoder",
            "YeoJohnsonTransformer",
        ],
        "classifier": [
            "Pipeline",
            "TargetMeanClassifier",
        ],
        "regressor": [
            "Pipeline",
            "TargetMeanRegressor",
        ],
        "outlier_detector": [
            "Pipeline",
        ],
        "clusterer": [
            "Pipeline",
        ],
    }
