# ruff: noqa: E501
"""Auto-sklearn Estimators."""

from aiod.models.apis import _ModelPkgSklearnEstimator


class AiodPkg__Sklearn(_ModelPkgSklearnEstimator):
    _tags = {
        "pkg_id": "__multiple",
        "python_dependencies": "scikit-learn",
        "pkg_pypi_name": "sklearn",
        "object_types": [
            "classifier",
            "regressor",
            "transformer",
            "cluster",
            "meta_estimator",
            "bicluster",
            "density",
            "outlier_detector",
            "manifold",
            "covariance",
        ],
    }

    # obtained via utils._indexing._preindex_sklearn
    # todo: automate generation
    # todo: include version bounds for availability
    # todo: test generated index against actual index
    _obj_dict = {
        "CalibratedClassifierCV": "sklearn.calibration.CalibratedClassifierCV",
        "FrozenEstimator": "sklearn.frozen.FrozenEstimator",
        "IsotonicRegression": "sklearn.isotonic.IsotonicRegression",
        "LabelEncoder": "sklearn.preprocessing.LabelEncoder",
        "LinearSVC": "sklearn.svm.LinearSVC",
        "AffinityPropagation": "sklearn.cluster.AffinityPropagation",
        "AgglomerativeClustering": "sklearn.cluster.AgglomerativeClustering",
        "Birch": "sklearn.cluster.Birch",
        "BisectingKMeans": "sklearn.cluster.BisectingKMeans",
        "DBSCAN": "sklearn.cluster.DBSCAN",
        "FeatureAgglomeration": "sklearn.cluster.FeatureAgglomeration",
        "HDBSCAN": "sklearn.cluster.HDBSCAN",
        "KMeans": "sklearn.cluster.KMeans",
        "MeanShift": "sklearn.cluster.MeanShift",
        "MiniBatchKMeans": "sklearn.cluster.MiniBatchKMeans",
        "OPTICS": "sklearn.cluster.OPTICS",
        "SpectralBiclustering": "sklearn.cluster.SpectralBiclustering",
        "SpectralClustering": "sklearn.cluster.SpectralClustering",
        "SpectralCoclustering": "sklearn.cluster.SpectralCoclustering",
        "ColumnTransformer": "sklearn.compose.ColumnTransformer",
        "TransformedTargetRegressor": "sklearn.compose.TransformedTargetRegressor",
        "FunctionTransformer": "sklearn.preprocessing.FunctionTransformer",
        "LinearRegression": "sklearn.linear_model.LinearRegression",
        "EllipticEnvelope": "sklearn.covariance.EllipticEnvelope",
        "EmpiricalCovariance": "sklearn.covariance.EmpiricalCovariance",
        "GraphicalLasso": "sklearn.covariance.GraphicalLasso",
        "GraphicalLassoCV": "sklearn.covariance.GraphicalLassoCV",
        "LedoitWolf": "sklearn.covariance.LedoitWolf",
        "MinCovDet": "sklearn.covariance.MinCovDet",
        "OAS": "sklearn.covariance.OAS",
        "ShrunkCovariance": "sklearn.covariance.ShrunkCovariance",
        "CCA": "sklearn.cross_decomposition.CCA",
        "PLSCanonical": "sklearn.cross_decomposition.PLSCanonical",
        "PLSRegression": "sklearn.cross_decomposition.PLSRegression",
        "PLSSVD": "sklearn.cross_decomposition.PLSSVD",
        "MultiLabelBinarizer": "sklearn.preprocessing.MultiLabelBinarizer",
        "CountVectorizer": "sklearn.feature_extraction.text.CountVectorizer",
        "DictionaryLearning": "sklearn.decomposition.DictionaryLearning",
        "FactorAnalysis": "sklearn.decomposition.FactorAnalysis",
        "FastICA": "sklearn.decomposition.FastICA",
        "IncrementalPCA": "sklearn.decomposition.IncrementalPCA",
        "KernelPCA": "sklearn.decomposition.KernelPCA",
        "LatentDirichletAllocation": "sklearn.decomposition.LatentDirichletAllocation",
        "MiniBatchDictionaryLearning": "sklearn.decomposition.MiniBatchDictionaryLearning",
        "MiniBatchNMF": "sklearn.decomposition.MiniBatchNMF",
        "MiniBatchSparsePCA": "sklearn.decomposition.MiniBatchSparsePCA",
        "NMF": "sklearn.decomposition.NMF",
        "PCA": "sklearn.decomposition.PCA",
        "SparseCoder": "sklearn.decomposition.SparseCoder",
        "SparsePCA": "sklearn.decomposition.SparsePCA",
        "TruncatedSVD": "sklearn.decomposition.TruncatedSVD",
        "Lars": "sklearn.linear_model.Lars",
        "Lasso": "sklearn.linear_model.Lasso",
        "LassoLars": "sklearn.linear_model.LassoLars",
        "KernelCenterer": "sklearn.preprocessing.KernelCenterer",
        "LinearDiscriminantAnalysis": "sklearn.discriminant_analysis.LinearDiscriminantAnalysis",
        "QuadraticDiscriminantAnalysis": "sklearn.discriminant_analysis.QuadraticDiscriminantAnalysis",
        "StandardScaler": "sklearn.preprocessing.StandardScaler",
        "DummyClassifier": "sklearn.dummy.DummyClassifier",
        "DummyRegressor": "sklearn.dummy.DummyRegressor",
        "AdaBoostClassifier": "sklearn.ensemble.AdaBoostClassifier",
        "AdaBoostRegressor": "sklearn.ensemble.AdaBoostRegressor",
        "BaggingClassifier": "sklearn.ensemble.BaggingClassifier",
        "BaggingRegressor": "sklearn.ensemble.BaggingRegressor",
        "ExtraTreesClassifier": "sklearn.ensemble.ExtraTreesClassifier",
        "ExtraTreesRegressor": "sklearn.ensemble.ExtraTreesRegressor",
        "GradientBoostingClassifier": "sklearn.ensemble.GradientBoostingClassifier",
        "GradientBoostingRegressor": "sklearn.ensemble.GradientBoostingRegressor",
        "HistGradientBoostingClassifier": "sklearn.ensemble.HistGradientBoostingClassifier",
        "HistGradientBoostingRegressor": "sklearn.ensemble.HistGradientBoostingRegressor",
        "IsolationForest": "sklearn.ensemble.IsolationForest",
        "RandomForestClassifier": "sklearn.ensemble.RandomForestClassifier",
        "RandomForestRegressor": "sklearn.ensemble.RandomForestRegressor",
        "RandomTreesEmbedding": "sklearn.ensemble.RandomTreesEmbedding",
        "StackingClassifier": "sklearn.ensemble.StackingClassifier",
        "StackingRegressor": "sklearn.ensemble.StackingRegressor",
        "VotingClassifier": "sklearn.ensemble.VotingClassifier",
        "VotingRegressor": "sklearn.ensemble.VotingRegressor",
        "DecisionTreeClassifier": "sklearn.tree.DecisionTreeClassifier",
        "DecisionTreeRegressor": "sklearn.tree.DecisionTreeRegressor",
        "ExtraTreeClassifier": "sklearn.tree.ExtraTreeClassifier",
        "ExtraTreeRegressor": "sklearn.tree.ExtraTreeRegressor",
        "OneHotEncoder": "sklearn.preprocessing.OneHotEncoder",
        "OrdinalEncoder": "sklearn.preprocessing.OrdinalEncoder",
        "LogisticRegression": "sklearn.linear_model.LogisticRegression",
        "RidgeCV": "sklearn.linear_model.RidgeCV",
        "DictVectorizer": "sklearn.feature_extraction.DictVectorizer",
        "FeatureHasher": "sklearn.feature_extraction.FeatureHasher",
        "PatchExtractor": "sklearn.feature_extraction.image.PatchExtractor",
        "HashingVectorizer": "sklearn.feature_extraction.text.HashingVectorizer",
        "TfidfTransformer": "sklearn.feature_extraction.text.TfidfTransformer",
        "TfidfVectorizer": "sklearn.feature_extraction.text.TfidfVectorizer",
        "GenericUnivariateSelect": "sklearn.feature_selection.GenericUnivariateSelect",
        "RFE": "sklearn.feature_selection.RFE",
        "RFECV": "sklearn.feature_selection.RFECV",
        "SelectFdr": "sklearn.feature_selection.SelectFdr",
        "SelectFpr": "sklearn.feature_selection.SelectFpr",
        "SelectFromModel": "sklearn.feature_selection.SelectFromModel",
        "SelectFwe": "sklearn.feature_selection.SelectFwe",
        "SelectKBest": "sklearn.feature_selection.SelectKBest",
        "SelectPercentile": "sklearn.feature_selection.SelectPercentile",
        "SequentialFeatureSelector": "sklearn.feature_selection.SequentialFeatureSelector",
        "VarianceThreshold": "sklearn.feature_selection.VarianceThreshold",
        "LabelBinarizer": "sklearn.preprocessing.LabelBinarizer",
        "GaussianProcessClassifier": "sklearn.gaussian_process.GaussianProcessClassifier",
        "GaussianProcessRegressor": "sklearn.gaussian_process.GaussianProcessRegressor",
        "OneVsOneClassifier": "sklearn.multiclass.OneVsOneClassifier",
        "OneVsRestClassifier": "sklearn.multiclass.OneVsRestClassifier",
        "KNNImputer": "sklearn.impute.KNNImputer",
        "MissingIndicator": "sklearn.impute.MissingIndicator",
        "SimpleImputer": "sklearn.impute.SimpleImputer",
        "IterativeImputer": "sklearn.impute.IterativeImputer",
        "AdditiveChi2Sampler": "sklearn.kernel_approximation.AdditiveChi2Sampler",
        "Nystroem": "sklearn.kernel_approximation.Nystroem",
        "PolynomialCountSketch": "sklearn.kernel_approximation.PolynomialCountSketch",
        "RBFSampler": "sklearn.kernel_approximation.RBFSampler",
        "SkewedChi2Sampler": "sklearn.kernel_approximation.SkewedChi2Sampler",
        "KernelRidge": "sklearn.kernel_ridge.KernelRidge",
        "ARDRegression": "sklearn.linear_model.ARDRegression",
        "BayesianRidge": "sklearn.linear_model.BayesianRidge",
        "ElasticNet": "sklearn.linear_model.ElasticNet",
        "ElasticNetCV": "sklearn.linear_model.ElasticNetCV",
        "GammaRegressor": "sklearn.linear_model.GammaRegressor",
        "HuberRegressor": "sklearn.linear_model.HuberRegressor",
        "LarsCV": "sklearn.linear_model.LarsCV",
        "LassoCV": "sklearn.linear_model.LassoCV",
        "LassoLarsCV": "sklearn.linear_model.LassoLarsCV",
        "LassoLarsIC": "sklearn.linear_model.LassoLarsIC",
        "LogisticRegressionCV": "sklearn.linear_model.LogisticRegressionCV",
        "MultiTaskElasticNet": "sklearn.linear_model.MultiTaskElasticNet",
        "MultiTaskElasticNetCV": "sklearn.linear_model.MultiTaskElasticNetCV",
        "MultiTaskLasso": "sklearn.linear_model.MultiTaskLasso",
        "MultiTaskLassoCV": "sklearn.linear_model.MultiTaskLassoCV",
        "OrthogonalMatchingPursuit": "sklearn.linear_model.OrthogonalMatchingPursuit",
        "OrthogonalMatchingPursuitCV": "sklearn.linear_model.OrthogonalMatchingPursuitCV",
        "PassiveAggressiveClassifier": "sklearn.linear_model.PassiveAggressiveClassifier",
        "PassiveAggressiveRegressor": "sklearn.linear_model.PassiveAggressiveRegressor",
        "Perceptron": "sklearn.linear_model.Perceptron",
        "PoissonRegressor": "sklearn.linear_model.PoissonRegressor",
        "QuantileRegressor": "sklearn.linear_model.QuantileRegressor",
        "RANSACRegressor": "sklearn.linear_model.RANSACRegressor",
        "Ridge": "sklearn.linear_model.Ridge",
        "RidgeClassifier": "sklearn.linear_model.RidgeClassifier",
        "RidgeClassifierCV": "sklearn.linear_model.RidgeClassifierCV",
        "SGDClassifier": "sklearn.linear_model.SGDClassifier",
        "SGDOneClassSVM": "sklearn.linear_model.SGDOneClassSVM",
        "SGDRegressor": "sklearn.linear_model.SGDRegressor",
        "TheilSenRegressor": "sklearn.linear_model.TheilSenRegressor",
        "TweedieRegressor": "sklearn.linear_model.TweedieRegressor",
        "GridSearchCV": "sklearn.model_selection.GridSearchCV",
        "ClassicalMDS": "sklearn.manifold.ClassicalMDS",
        "Isomap": "sklearn.manifold.Isomap",
        "LocallyLinearEmbedding": "sklearn.manifold.LocallyLinearEmbedding",
        "MDS": "sklearn.manifold.MDS",
        "SpectralEmbedding": "sklearn.manifold.SpectralEmbedding",
        "TSNE": "sklearn.manifold.TSNE",
        "BayesianGaussianMixture": "sklearn.mixture.BayesianGaussianMixture",
        "GaussianMixture": "sklearn.mixture.GaussianMixture",
        "FixedThresholdClassifier": "sklearn.model_selection.FixedThresholdClassifier",
        "RandomizedSearchCV": "sklearn.model_selection.RandomizedSearchCV",
        "TunedThresholdClassifierCV": "sklearn.model_selection.TunedThresholdClassifierCV",
        "HalvingGridSearchCV": "sklearn.model_selection.HalvingGridSearchCV",
        "HalvingRandomSearchCV": "sklearn.model_selection.HalvingRandomSearchCV",
        "OutputCodeClassifier": "sklearn.multiclass.OutputCodeClassifier",
        "ClassifierChain": "sklearn.multioutput.ClassifierChain",
        "MultiOutputClassifier": "sklearn.multioutput.MultiOutputClassifier",
        "MultiOutputRegressor": "sklearn.multioutput.MultiOutputRegressor",
        "RegressorChain": "sklearn.multioutput.RegressorChain",
        "BernoulliNB": "sklearn.naive_bayes.BernoulliNB",
        "CategoricalNB": "sklearn.naive_bayes.CategoricalNB",
        "ComplementNB": "sklearn.naive_bayes.ComplementNB",
        "GaussianNB": "sklearn.naive_bayes.GaussianNB",
        "MultinomialNB": "sklearn.naive_bayes.MultinomialNB",
        "KNeighborsClassifier": "sklearn.neighbors.KNeighborsClassifier",
        "KNeighborsRegressor": "sklearn.neighbors.KNeighborsRegressor",
        "KNeighborsTransformer": "sklearn.neighbors.KNeighborsTransformer",
        "KernelDensity": "sklearn.neighbors.KernelDensity",
        "LocalOutlierFactor": "sklearn.neighbors.LocalOutlierFactor",
        "NearestCentroid": "sklearn.neighbors.NearestCentroid",
        "NeighborhoodComponentsAnalysis": "sklearn.neighbors.NeighborhoodComponentsAnalysis",
        "RadiusNeighborsClassifier": "sklearn.neighbors.RadiusNeighborsClassifier",
        "RadiusNeighborsRegressor": "sklearn.neighbors.RadiusNeighborsRegressor",
        "RadiusNeighborsTransformer": "sklearn.neighbors.RadiusNeighborsTransformer",
        "BernoulliRBM": "sklearn.neural_network.BernoulliRBM",
        "MLPClassifier": "sklearn.neural_network.MLPClassifier",
        "MLPRegressor": "sklearn.neural_network.MLPRegressor",
        "FeatureUnion": "sklearn.pipeline.FeatureUnion",
        "Pipeline": "sklearn.pipeline.Pipeline",
        "Binarizer": "sklearn.preprocessing.Binarizer",
        "KBinsDiscretizer": "sklearn.preprocessing.KBinsDiscretizer",
        "MaxAbsScaler": "sklearn.preprocessing.MaxAbsScaler",
        "MinMaxScaler": "sklearn.preprocessing.MinMaxScaler",
        "Normalizer": "sklearn.preprocessing.Normalizer",
        "PolynomialFeatures": "sklearn.preprocessing.PolynomialFeatures",
        "PowerTransformer": "sklearn.preprocessing.PowerTransformer",
        "QuantileTransformer": "sklearn.preprocessing.QuantileTransformer",
        "RobustScaler": "sklearn.preprocessing.RobustScaler",
        "SplineTransformer": "sklearn.preprocessing.SplineTransformer",
        "TargetEncoder": "sklearn.preprocessing.TargetEncoder",
        "GaussianRandomProjection": "sklearn.random_projection.GaussianRandomProjection",
        "SparseRandomProjection": "sklearn.random_projection.SparseRandomProjection",
        "LabelPropagation": "sklearn.semi_supervised.LabelPropagation",
        "LabelSpreading": "sklearn.semi_supervised.LabelSpreading",
        "SelfTrainingClassifier": "sklearn.semi_supervised.SelfTrainingClassifier",
        "LinearSVR": "sklearn.svm.LinearSVR",
        "NuSVC": "sklearn.svm.NuSVC",
        "NuSVR": "sklearn.svm.NuSVR",
        "OneClassSVM": "sklearn.svm.OneClassSVM",
        "SVC": "sklearn.svm.SVC",
        "SVR": "sklearn.svm.SVR",
        "CheckingClassifier": "sklearn.utils.CheckingClassifier",
    }

    # todo - needs to be generated, for this a new util needs to be written
    # important: polymorphic objects like Pipeline or GridSearchCV
    # should be handled with care, as inheritance etc does not reflect the polymorphism
    # this may need manual curation for start, which should also be automated later
    _type_of_objs = {
        "CalibratedClassifierCV": ["classifier", "meta_estimator"],
        "FrozenEstimator": [
            "classifier",
            "regressor",
            "transformer",
            "cluster",
            "meta_estimator",
            "bicluster",
            "density",
            "outlier_detector",
            "manifold",
            "covariance",
        ],
        "IsotonicRegression": ["regressor", "transformer"],
        "LabelEncoder": "transformer",
        "LinearSVC": "classifier",
        "AffinityPropagation": "cluster",
        "AgglomerativeClustering": "cluster",
        "Birch": ["cluster", "transformer"],
        "BisectingKMeans": ["transformer", "cluster"],
        "DBSCAN": "cluster",
        "FeatureAgglomeration": ["transformer", "cluster"],
        "HDBSCAN": "cluster",
        "KMeans": ["transformer", "cluster"],
        "MeanShift": "cluster",
        "MiniBatchKMeans": ["transformer", "cluster"],
        "OPTICS": "cluster",
        "SpectralBiclustering": "bicluster",
        "SpectralClustering": "cluster",
        "SpectralCoclustering": "bicluster",
        "ColumnTransformer": "transformer",
        "TransformedTargetRegressor": "regressor",
        "FunctionTransformer": "transformer",
        "LinearRegression": "regressor",
        "EllipticEnvelope": ["outlier_detector", "covariance"],
        "EmpiricalCovariance": "covariance",
        "GraphicalLasso": "covariance",
        "GraphicalLassoCV": "covariance",
        "LedoitWolf": "covariance",
        "MinCovDet": "covariance",
        "OAS": "covariance",
        "ShrunkCovariance": "covariance",
        "CCA": ["transformer", "regressor"],
        "PLSCanonical": ["transformer", "regressor"],
        "PLSRegression": ["transformer", "regressor"],
        "PLSSVD": "transformer",
        "MultiLabelBinarizer": "transformer",
        "CountVectorizer": "transformer",
        "DictionaryLearning": "transformer",
        "FactorAnalysis": "transformer",
        "FastICA": "transformer",
        "IncrementalPCA": "transformer",
        "KernelPCA": "transformer",
        "LatentDirichletAllocation": "transformer",
        "MiniBatchDictionaryLearning": "transformer",
        "MiniBatchNMF": "transformer",
        "MiniBatchSparsePCA": "transformer",
        "NMF": "transformer",
        "PCA": "transformer",
        "SparseCoder": "transformer",
        "SparsePCA": "transformer",
        "TruncatedSVD": "transformer",
        "Lars": "regressor",
        "Lasso": "regressor",
        "LassoLars": "regressor",
        "KernelCenterer": "transformer",
        "LinearDiscriminantAnalysis": ["classifier", "transformer"],
        "QuadraticDiscriminantAnalysis": "classifier",
        "StandardScaler": "transformer",
        "DummyClassifier": "classifier",
        "DummyRegressor": "regressor",
        "AdaBoostClassifier": ["classifier", "meta_estimator"],
        "AdaBoostRegressor": ["regressor", "meta_estimator"],
        "BaggingClassifier": ["classifier", "meta_estimator"],
        "BaggingRegressor": ["regressor", "meta_estimator"],
        "ExtraTreesClassifier": ["classifier", "meta_estimator"],
        "ExtraTreesRegressor": ["regressor", "meta_estimator"],
        "GradientBoostingClassifier": ["classifier", "meta_estimator"],
        "GradientBoostingRegressor": ["regressor", "meta_estimator"],
        "HistGradientBoostingClassifier": "classifier",
        "HistGradientBoostingRegressor": "regressor",
        "IsolationForest": ["outlier_detector", "meta_estimator"],
        "RandomForestClassifier": ["classifier", "meta_estimator"],
        "RandomForestRegressor": ["regressor", "meta_estimator"],
        "RandomTreesEmbedding": ["transformer", "meta_estimator"],
        "StackingClassifier": ["classifier", "transformer", "meta_estimator"],
        "StackingRegressor": ["regressor", "transformer", "meta_estimator"],
        "VotingClassifier": ["classifier", "transformer", "meta_estimator"],
        "VotingRegressor": ["regressor", "transformer", "meta_estimator"],
        "DecisionTreeClassifier": "classifier",
        "DecisionTreeRegressor": "regressor",
        "ExtraTreeClassifier": "classifier",
        "ExtraTreeRegressor": "regressor",
        "OneHotEncoder": "transformer",
        "OrdinalEncoder": "transformer",
        "LogisticRegression": "classifier",
        "RidgeCV": "regressor",
        "DictVectorizer": "transformer",
        "FeatureHasher": "transformer",
        "PatchExtractor": "transformer",
        "HashingVectorizer": "transformer",
        "TfidfTransformer": "transformer",
        "TfidfVectorizer": "transformer",
        "GenericUnivariateSelect": "transformer",
        "RFE": ["transformer", "meta_estimator"],
        "RFECV": ["transformer", "meta_estimator"],
        "SelectFdr": "transformer",
        "SelectFpr": "transformer",
        "SelectFromModel": ["meta_estimator", "transformer"],
        "SelectFwe": "transformer",
        "SelectKBest": "transformer",
        "SelectPercentile": "transformer",
        "SequentialFeatureSelector": ["transformer", "meta_estimator"],
        "VarianceThreshold": "transformer",
        "LabelBinarizer": "transformer",
        "GaussianProcessClassifier": "classifier",
        "GaussianProcessRegressor": "regressor",
        "OneVsOneClassifier": ["meta_estimator", "classifier"],
        "OneVsRestClassifier": ["classifier", "meta_estimator"],
        "KNNImputer": "transformer",
        "MissingIndicator": "transformer",
        "SimpleImputer": "transformer",
        "IterativeImputer": "transformer",
        "AdditiveChi2Sampler": "transformer",
        "Nystroem": "transformer",
        "PolynomialCountSketch": "transformer",
        "RBFSampler": "transformer",
        "SkewedChi2Sampler": "transformer",
        "KernelRidge": "regressor",
        "ARDRegression": "regressor",
        "BayesianRidge": "regressor",
        "ElasticNet": "regressor",
        "ElasticNetCV": "regressor",
        "GammaRegressor": "regressor",
        "HuberRegressor": "regressor",
        "LarsCV": "regressor",
        "LassoCV": "regressor",
        "LassoLarsCV": "regressor",
        "LassoLarsIC": "regressor",
        "LogisticRegressionCV": "classifier",
        "MultiTaskElasticNet": "regressor",
        "MultiTaskElasticNetCV": "regressor",
        "MultiTaskLasso": "regressor",
        "MultiTaskLassoCV": "regressor",
        "OrthogonalMatchingPursuit": "regressor",
        "OrthogonalMatchingPursuitCV": "regressor",
        "PassiveAggressiveClassifier": "classifier",
        "PassiveAggressiveRegressor": "regressor",
        "Perceptron": "classifier",
        "PoissonRegressor": "regressor",
        "QuantileRegressor": "regressor",
        "RANSACRegressor": ["meta_estimator", "regressor"],
        "Ridge": "regressor",
        "RidgeClassifier": "classifier",
        "RidgeClassifierCV": "classifier",
        "SGDClassifier": "classifier",
        "SGDOneClassSVM": "outlier_detector",
        "SGDRegressor": "regressor",
        "TheilSenRegressor": "regressor",
        "TweedieRegressor": "regressor",
        "GridSearchCV": [
            "classifier",
            "regressor",
            "transformer",
            "cluster",
            "meta_estimator",
            "bicluster",
            "density",
            "outlier_detector",
            "manifold",
            "covariance",
        ],
        "ClassicalMDS": "manifold",
        "Isomap": ["transformer", "manifold"],
        "LocallyLinearEmbedding": ["transformer", "manifold"],
        "MDS": "manifold",
        "SpectralEmbedding": "manifold",
        "TSNE": ["transformer", "manifold"],
        "BayesianGaussianMixture": "density",
        "GaussianMixture": "density",
        "FixedThresholdClassifier": ["classifier", "meta_estimator"],
        "RandomizedSearchCV": [
            "classifier",
            "regressor",
            "transformer",
            "cluster",
            "meta_estimator",
            "bicluster",
            "density",
            "outlier_detector",
            "manifold",
            "covariance",
        ],
        "TunedThresholdClassifierCV": ["classifier", "meta_estimator"],
        "HalvingGridSearchCV": "meta_estimator",
        "HalvingRandomSearchCV": "meta_estimator",
        "OutputCodeClassifier": ["meta_estimator", "classifier"],
        "ClassifierChain": ["meta_estimator", "classifier"],
        "MultiOutputClassifier": ["classifier", "meta_estimator"],
        "MultiOutputRegressor": ["regressor", "meta_estimator"],
        "RegressorChain": ["meta_estimator", "regressor"],
        "BernoulliNB": "classifier",
        "CategoricalNB": "classifier",
        "ComplementNB": "classifier",
        "GaussianNB": "classifier",
        "MultinomialNB": "classifier",
        "KNeighborsClassifier": "classifier",
        "KNeighborsRegressor": "regressor",
        "KNeighborsTransformer": "transformer",
        "KernelDensity": "density",
        "LocalOutlierFactor": "outlier_detector",
        "NearestCentroid": "classifier",
        "NeighborhoodComponentsAnalysis": "transformer",
        "RadiusNeighborsClassifier": "classifier",
        "RadiusNeighborsRegressor": "regressor",
        "RadiusNeighborsTransformer": "transformer",
        "BernoulliRBM": "transformer",
        "MLPClassifier": "classifier",
        "MLPRegressor": "regressor",
        "FeatureUnion": "transformer",
        "Pipeline": [
            "classifier",
            "regressor",
            "transformer",
            "cluster",
            "meta_estimator",
            "bicluster",
            "density",
            "outlier_detector",
            "manifold",
            "covariance",
        ],
        "Binarizer": "transformer",
        "KBinsDiscretizer": "transformer",
        "MaxAbsScaler": "transformer",
        "MinMaxScaler": "transformer",
        "Normalizer": "transformer",
        "PolynomialFeatures": "transformer",
        "PowerTransformer": "transformer",
        "QuantileTransformer": "transformer",
        "RobustScaler": "transformer",
        "SplineTransformer": "transformer",
        "TargetEncoder": "transformer",
        "GaussianRandomProjection": "transformer",
        "SparseRandomProjection": "transformer",
        "LabelPropagation": "classifier",
        "LabelSpreading": "classifier",
        "SelfTrainingClassifier": ["classifier", "meta_estimator"],
        "LinearSVR": "regressor",
        "NuSVC": "classifier",
        "NuSVR": "regressor",
        "OneClassSVM": "outlier_detector",
        "SVC": "classifier",
        "SVR": "regressor",
        "CheckingClassifier": "classifier",
    }

    # todo: this also should be preindexed. can be generated from _type_of_objs
    # important to be mindful of objects with multiple types, e.g., Pipeline
    _objs_by_type = {
        "classifier": [
            "CalibratedClassifierCV",
            "FrozenEstimator",
            "LinearSVC",
            "LinearDiscriminantAnalysis",
            "QuadraticDiscriminantAnalysis",
            "DummyClassifier",
            "AdaBoostClassifier",
            "BaggingClassifier",
            "ExtraTreesClassifier",
            "GradientBoostingClassifier",
            "HistGradientBoostingClassifier",
            "RandomForestClassifier",
            "StackingClassifier",
            "VotingClassifier",
            "DecisionTreeClassifier",
            "ExtraTreeClassifier",
            "LogisticRegression",
            "GaussianProcessClassifier",
            "OneVsOneClassifier",
            "OneVsRestClassifier",
            "LogisticRegressionCV",
            "PassiveAggressiveClassifier",
            "Perceptron",
            "RidgeClassifier",
            "RidgeClassifierCV",
            "SGDClassifier",
            "GridSearchCV",
            "FixedThresholdClassifier",
            "RandomizedSearchCV",
            "TunedThresholdClassifierCV",
            "OutputCodeClassifier",
            "ClassifierChain",
            "MultiOutputClassifier",
            "BernoulliNB",
            "CategoricalNB",
            "ComplementNB",
            "GaussianNB",
            "MultinomialNB",
            "KNeighborsClassifier",
            "NearestCentroid",
            "RadiusNeighborsClassifier",
            "MLPClassifier",
            "Pipeline",
            "LabelPropagation",
            "LabelSpreading",
            "SelfTrainingClassifier",
            "NuSVC",
            "SVC",
            "CheckingClassifier",
        ],
        "meta_estimator": [
            "CalibratedClassifierCV",
            "FrozenEstimator",
            "AdaBoostClassifier",
            "AdaBoostRegressor",
            "BaggingClassifier",
            "BaggingRegressor",
            "ExtraTreesClassifier",
            "ExtraTreesRegressor",
            "GradientBoostingClassifier",
            "GradientBoostingRegressor",
            "IsolationForest",
            "RandomForestClassifier",
            "RandomForestRegressor",
            "RandomTreesEmbedding",
            "StackingClassifier",
            "StackingRegressor",
            "VotingClassifier",
            "VotingRegressor",
            "RFE",
            "RFECV",
            "SelectFromModel",
            "SequentialFeatureSelector",
            "OneVsOneClassifier",
            "OneVsRestClassifier",
            "RANSACRegressor",
            "GridSearchCV",
            "FixedThresholdClassifier",
            "HalvingGridSearchCV",
            "HalvingRandomSearchCV",
            "RandomizedSearchCV",
            "TunedThresholdClassifierCV",
            "OutputCodeClassifier",
            "ClassifierChain",
            "MultiOutputClassifier",
            "MultiOutputRegressor",
            "RegressorChain",
            "Pipeline",
            "SelfTrainingClassifier",
        ],
        "regressor": [
            "FrozenEstimator",
            "IsotonicRegression",
            "TransformedTargetRegressor",
            "LinearRegression",
            "CCA",
            "PLSCanonical",
            "PLSRegression",
            "Lars",
            "Lasso",
            "LassoLars",
            "DummyRegressor",
            "AdaBoostRegressor",
            "BaggingRegressor",
            "ExtraTreesRegressor",
            "GradientBoostingRegressor",
            "HistGradientBoostingRegressor",
            "RandomForestRegressor",
            "StackingRegressor",
            "VotingRegressor",
            "DecisionTreeRegressor",
            "ExtraTreeRegressor",
            "RidgeCV",
            "GaussianProcessRegressor",
            "KernelRidge",
            "ARDRegression",
            "BayesianRidge",
            "ElasticNet",
            "ElasticNetCV",
            "GammaRegressor",
            "HuberRegressor",
            "LarsCV",
            "LassoCV",
            "LassoLarsCV",
            "LassoLarsIC",
            "MultiTaskElasticNet",
            "MultiTaskElasticNetCV",
            "MultiTaskLasso",
            "MultiTaskLassoCV",
            "OrthogonalMatchingPursuit",
            "OrthogonalMatchingPursuitCV",
            "PassiveAggressiveRegressor",
            "PoissonRegressor",
            "QuantileRegressor",
            "RANSACRegressor",
            "Ridge",
            "SGDRegressor",
            "TheilSenRegressor",
            "TweedieRegressor",
            "GridSearchCV",
            "RandomizedSearchCV",
            "MultiOutputRegressor",
            "RegressorChain",
            "KNeighborsRegressor",
            "RadiusNeighborsRegressor",
            "MLPRegressor",
            "Pipeline",
            "LinearSVR",
            "NuSVR",
            "SVR",
        ],
        "transformer": [
            "FrozenEstimator",
            "IsotonicRegression",
            "LabelEncoder",
            "Birch",
            "BisectingKMeans",
            "FeatureAgglomeration",
            "KMeans",
            "MiniBatchKMeans",
            "ColumnTransformer",
            "FunctionTransformer",
            "CCA",
            "PLSCanonical",
            "PLSRegression",
            "PLSSVD",
            "MultiLabelBinarizer",
            "CountVectorizer",
            "DictionaryLearning",
            "FactorAnalysis",
            "FastICA",
            "IncrementalPCA",
            "KernelPCA",
            "LatentDirichletAllocation",
            "MiniBatchDictionaryLearning",
            "MiniBatchNMF",
            "MiniBatchSparsePCA",
            "NMF",
            "PCA",
            "SparseCoder",
            "SparsePCA",
            "TruncatedSVD",
            "KernelCenterer",
            "LinearDiscriminantAnalysis",
            "StandardScaler",
            "RandomTreesEmbedding",
            "StackingClassifier",
            "StackingRegressor",
            "VotingClassifier",
            "VotingRegressor",
            "OneHotEncoder",
            "OrdinalEncoder",
            "DictVectorizer",
            "FeatureHasher",
            "PatchExtractor",
            "HashingVectorizer",
            "TfidfTransformer",
            "TfidfVectorizer",
            "GenericUnivariateSelect",
            "RFE",
            "RFECV",
            "SelectFdr",
            "SelectFpr",
            "SelectFromModel",
            "SelectFwe",
            "SelectKBest",
            "SelectPercentile",
            "SequentialFeatureSelector",
            "VarianceThreshold",
            "LabelBinarizer",
            "KNNImputer",
            "MissingIndicator",
            "SimpleImputer",
            "IterativeImputer",
            "AdditiveChi2Sampler",
            "Nystroem",
            "PolynomialCountSketch",
            "RBFSampler",
            "SkewedChi2Sampler",
            "GridSearchCV",
            "Isomap",
            "LocallyLinearEmbedding",
            "TSNE",
            "RandomizedSearchCV",
            "KNeighborsTransformer",
            "NeighborhoodComponentsAnalysis",
            "RadiusNeighborsTransformer",
            "BernoulliRBM",
            "FeatureUnion",
            "Pipeline",
            "Binarizer",
            "KBinsDiscretizer",
            "MaxAbsScaler",
            "MinMaxScaler",
            "Normalizer",
            "PolynomialFeatures",
            "PowerTransformer",
            "QuantileTransformer",
            "RobustScaler",
            "SplineTransformer",
            "TargetEncoder",
            "GaussianRandomProjection",
            "SparseRandomProjection",
        ],
        "cluster": [
            "FrozenEstimator",
            "AffinityPropagation",
            "AgglomerativeClustering",
            "Birch",
            "BisectingKMeans",
            "DBSCAN",
            "FeatureAgglomeration",
            "HDBSCAN",
            "KMeans",
            "MeanShift",
            "MiniBatchKMeans",
            "OPTICS",
            "SpectralClustering",
            "GridSearchCV",
            "RandomizedSearchCV",
            "Pipeline",
        ],
        "bicluster": [
            "FrozenEstimator",
            "SpectralBiclustering",
            "SpectralCoclustering",
            "GridSearchCV",
            "RandomizedSearchCV",
            "Pipeline",
        ],
        "density": [
            "FrozenEstimator",
            "GridSearchCV",
            "BayesianGaussianMixture",
            "GaussianMixture",
            "RandomizedSearchCV",
            "KernelDensity",
            "Pipeline",
        ],
        "outlier_detector": [
            "FrozenEstimator",
            "EllipticEnvelope",
            "IsolationForest",
            "SGDOneClassSVM",
            "GridSearchCV",
            "RandomizedSearchCV",
            "LocalOutlierFactor",
            "Pipeline",
            "OneClassSVM",
        ],
        "manifold": [
            "FrozenEstimator",
            "GridSearchCV",
            "ClassicalMDS",
            "Isomap",
            "LocallyLinearEmbedding",
            "MDS",
            "SpectralEmbedding",
            "TSNE",
            "RandomizedSearchCV",
            "Pipeline",
        ],
        "covariance": [
            "FrozenEstimator",
            "EllipticEnvelope",
            "EmpiricalCovariance",
            "GraphicalLasso",
            "GraphicalLassoCV",
            "LedoitWolf",
            "MinCovDet",
            "OAS",
            "ShrunkCovariance",
            "GridSearchCV",
            "RandomizedSearchCV",
            "Pipeline",
        ],
    }
