# ruff: noqa: E501
"""Auto-sklearn classifier."""

from aiod.models.apis import _ModelPkgSklearnEstimator


class AiodPkg__Sklearn(_ModelPkgSklearnEstimator):
    _tags = {
        "pkg_id": "__multiple",
        "python_dependencies": "scikit-learn",
        "pkg_pypi_name": "scikit-learn",
        "object_types": ["classifier", "regressor"],
    }

    # obtained via utils._indexing._preindex_sklearn
    # todo: automate generation
    # todo: include version bounds for availability
    # todo: test generated index against actual index
    _obj_dict = {
        "ARDRegression": "sklearn.linear_model.ARDRegression",
        "AdaBoostClassifier": "sklearn.ensemble.AdaBoostClassifier",
        "AdaBoostRegressor": "sklearn.ensemble.AdaBoostRegressor",
        "AdditiveChi2Sampler": "sklearn.kernel_approximation.AdditiveChi2Sampler",
        "AffinityPropagation": "sklearn.cluster.AffinityPropagation",
        "AgglomerativeClustering": "sklearn.cluster.AgglomerativeClustering",
        "BaggingClassifier": "sklearn.ensemble.BaggingClassifier",
        "BaggingRegressor": "sklearn.ensemble.BaggingRegressor",
        "BayesianGaussianMixture": "sklearn.mixture.BayesianGaussianMixture",
        "BayesianRidge": "sklearn.linear_model.BayesianRidge",
        "BernoulliNB": "sklearn.naive_bayes.BernoulliNB",
        "BernoulliRBM": "sklearn.neural_network.BernoulliRBM",
        "Binarizer": "sklearn.preprocessing.Binarizer",
        "Birch": "sklearn.cluster.Birch",
        "BisectingKMeans": "sklearn.cluster.BisectingKMeans",
        "CCA": "sklearn.cross_decomposition.CCA",
        "CalibratedClassifierCV": "sklearn.calibration.CalibratedClassifierCV",
        "CategoricalNB": "sklearn.naive_bayes.CategoricalNB",
        "ClassicalMDS": "sklearn.manifold.ClassicalMDS",
        "ClassifierChain": "sklearn.multioutput.ClassifierChain",
        "ColumnTransformer": "sklearn.compose.ColumnTransformer",
        "ComplementNB": "sklearn.naive_bayes.ComplementNB",
        "CountVectorizer": "sklearn.feature_extraction.text.CountVectorizer",
        "DBSCAN": "sklearn.cluster.DBSCAN",
        "DecisionTreeClassifier": "sklearn.tree.DecisionTreeClassifier",
        "DecisionTreeRegressor": "sklearn.tree.DecisionTreeRegressor",
        "DictVectorizer": "sklearn.feature_extraction.DictVectorizer",
        "DictionaryLearning": "sklearn.decomposition.DictionaryLearning",
        "DummyClassifier": "sklearn.dummy.DummyClassifier",
        "DummyRegressor": "sklearn.dummy.DummyRegressor",
        "ElasticNet": "sklearn.linear_model.ElasticNet",
        "ElasticNetCV": "sklearn.linear_model.ElasticNetCV",
        "EllipticEnvelope": "sklearn.covariance.EllipticEnvelope",
        "EmpiricalCovariance": "sklearn.covariance.EmpiricalCovariance",
        "ExtraTreeClassifier": "sklearn.tree.ExtraTreeClassifier",
        "ExtraTreeRegressor": "sklearn.tree.ExtraTreeRegressor",
        "ExtraTreesClassifier": "sklearn.ensemble.ExtraTreesClassifier",
        "ExtraTreesRegressor": "sklearn.ensemble.ExtraTreesRegressor",
        "FactorAnalysis": "sklearn.decomposition.FactorAnalysis",
        "FastICA": "sklearn.decomposition.FastICA",
        "FeatureAgglomeration": "sklearn.cluster.FeatureAgglomeration",
        "FeatureHasher": "sklearn.feature_extraction.FeatureHasher",
        "FeatureUnion": "sklearn.pipeline.FeatureUnion",
        "FixedThresholdClassifier": "sklearn.model_selection.FixedThresholdClassifier",
        "FrozenEstimator": "sklearn.frozen.FrozenEstimator",
        "FunctionTransformer": "sklearn.preprocessing.FunctionTransformer",
        "GammaRegressor": "sklearn.linear_model.GammaRegressor",
        "GaussianMixture": "sklearn.mixture.GaussianMixture",
        "GaussianNB": "sklearn.naive_bayes.GaussianNB",
        "GaussianProcessClassifier": "sklearn.gaussian_process.GaussianProcessClassifier",
        "GaussianProcessRegressor": "sklearn.gaussian_process.GaussianProcessRegressor",
        "GaussianRandomProjection": "sklearn.random_projection.GaussianRandomProjection",
        "GenericUnivariateSelect": "sklearn.feature_selection.GenericUnivariateSelect",
        "GradientBoostingClassifier": "sklearn.ensemble.GradientBoostingClassifier",
        "GradientBoostingRegressor": "sklearn.ensemble.GradientBoostingRegressor",
        "GraphicalLasso": "sklearn.covariance.GraphicalLasso",
        "GraphicalLassoCV": "sklearn.covariance.GraphicalLassoCV",
        "GridSearchCV": "sklearn.model_selection.GridSearchCV",
        "HDBSCAN": "sklearn.cluster.HDBSCAN",
        "HashingVectorizer": "sklearn.feature_extraction.text.HashingVectorizer",
        "HistGradientBoostingClassifier": "sklearn.ensemble.HistGradientBoostingClassifier",
        "HistGradientBoostingRegressor": "sklearn.ensemble.HistGradientBoostingRegressor",
        "HuberRegressor": "sklearn.linear_model.HuberRegressor",
        "IncrementalPCA": "sklearn.decomposition.IncrementalPCA",
        "IsolationForest": "sklearn.ensemble.IsolationForest",
        "Isomap": "sklearn.manifold.Isomap",
        "IsotonicRegression": "sklearn.isotonic.IsotonicRegression",
        "KBinsDiscretizer": "sklearn.preprocessing.KBinsDiscretizer",
        "KMeans": "sklearn.cluster.KMeans",
        "KNNImputer": "sklearn.impute.KNNImputer",
        "KNeighborsClassifier": "sklearn.neighbors.KNeighborsClassifier",
        "KNeighborsRegressor": "sklearn.neighbors.KNeighborsRegressor",
        "KNeighborsTransformer": "sklearn.neighbors.KNeighborsTransformer",
        "KernelCenterer": "sklearn.preprocessing.KernelCenterer",
        "KernelDensity": "sklearn.neighbors.KernelDensity",
        "KernelPCA": "sklearn.decomposition.KernelPCA",
        "KernelRidge": "sklearn.kernel_ridge.KernelRidge",
        "LabelBinarizer": "sklearn.preprocessing.LabelBinarizer",
        "LabelEncoder": "sklearn.preprocessing.LabelEncoder",
        "LabelPropagation": "sklearn.semi_supervised.LabelPropagation",
        "LabelSpreading": "sklearn.semi_supervised.LabelSpreading",
        "Lars": "sklearn.linear_model.Lars",
        "LarsCV": "sklearn.linear_model.LarsCV",
        "Lasso": "sklearn.linear_model.Lasso",
        "LassoCV": "sklearn.linear_model.LassoCV",
        "LassoLars": "sklearn.linear_model.LassoLars",
        "LassoLarsCV": "sklearn.linear_model.LassoLarsCV",
        "LassoLarsIC": "sklearn.linear_model.LassoLarsIC",
        "LatentDirichletAllocation": "sklearn.decomposition.LatentDirichletAllocation",
        "LedoitWolf": "sklearn.covariance.LedoitWolf",
        "LinearDiscriminantAnalysis": "sklearn.discriminant_analysis.LinearDiscriminantAnalysis",
        "LinearRegression": "sklearn.linear_model.LinearRegression",
        "LinearSVC": "sklearn.svm.LinearSVC",
        "LinearSVR": "sklearn.svm.LinearSVR",
        "LocalOutlierFactor": "sklearn.neighbors.LocalOutlierFactor",
        "LocallyLinearEmbedding": "sklearn.manifold.LocallyLinearEmbedding",
        "LogisticRegression": "sklearn.linear_model.LogisticRegression",
        "LogisticRegressionCV": "sklearn.linear_model.LogisticRegressionCV",
        "MDS": "sklearn.manifold.MDS",
        "MLPClassifier": "sklearn.neural_network.MLPClassifier",
        "MLPRegressor": "sklearn.neural_network.MLPRegressor",
        "MaxAbsScaler": "sklearn.preprocessing.MaxAbsScaler",
        "MeanShift": "sklearn.cluster.MeanShift",
        "MinCovDet": "sklearn.covariance.MinCovDet",
        "MinMaxScaler": "sklearn.preprocessing.MinMaxScaler",
        "MiniBatchDictionaryLearning": "sklearn.decomposition.MiniBatchDictionaryLearning",
        "MiniBatchKMeans": "sklearn.cluster.MiniBatchKMeans",
        "MiniBatchNMF": "sklearn.decomposition.MiniBatchNMF",
        "MiniBatchSparsePCA": "sklearn.decomposition.MiniBatchSparsePCA",
        "MissingIndicator": "sklearn.impute.MissingIndicator",
        "MultiLabelBinarizer": "sklearn.preprocessing.MultiLabelBinarizer",
        "MultiOutputClassifier": "sklearn.multioutput.MultiOutputClassifier",
        "MultiOutputRegressor": "sklearn.multioutput.MultiOutputRegressor",
        "MultiTaskElasticNet": "sklearn.linear_model.MultiTaskElasticNet",
        "MultiTaskElasticNetCV": "sklearn.linear_model.MultiTaskElasticNetCV",
        "MultiTaskLasso": "sklearn.linear_model.MultiTaskLasso",
        "MultiTaskLassoCV": "sklearn.linear_model.MultiTaskLassoCV",
        "MultinomialNB": "sklearn.naive_bayes.MultinomialNB",
        "NMF": "sklearn.decomposition.NMF",
        "NearestCentroid": "sklearn.neighbors.NearestCentroid",
        "NearestNeighbors": "sklearn.neighbors.NearestNeighbors",
        "NeighborhoodComponentsAnalysis": "sklearn.neighbors.NeighborhoodComponentsAnalysis",
        "Normalizer": "sklearn.preprocessing.Normalizer",
        "NuSVC": "sklearn.svm.NuSVC",
        "NuSVR": "sklearn.svm.NuSVR",
        "Nystroem": "sklearn.kernel_approximation.Nystroem",
        "OAS": "sklearn.covariance.OAS",
        "OPTICS": "sklearn.cluster.OPTICS",
        "OneClassSVM": "sklearn.svm.OneClassSVM",
        "OneHotEncoder": "sklearn.preprocessing.OneHotEncoder",
        "OneVsOneClassifier": "sklearn.multiclass.OneVsOneClassifier",
        "OneVsRestClassifier": "sklearn.multiclass.OneVsRestClassifier",
        "OrdinalEncoder": "sklearn.preprocessing.OrdinalEncoder",
        "OrthogonalMatchingPursuit": "sklearn.linear_model.OrthogonalMatchingPursuit",
        "OrthogonalMatchingPursuitCV": "sklearn.linear_model.OrthogonalMatchingPursuitCV",
        "OutputCodeClassifier": "sklearn.multiclass.OutputCodeClassifier",
        "PCA": "sklearn.decomposition.PCA",
        "PLSCanonical": "sklearn.cross_decomposition.PLSCanonical",
        "PLSRegression": "sklearn.cross_decomposition.PLSRegression",
        "PLSSVD": "sklearn.cross_decomposition.PLSSVD",
        "PassiveAggressiveClassifier": "sklearn.linear_model.PassiveAggressiveClassifier",
        "PassiveAggressiveRegressor": "sklearn.linear_model.PassiveAggressiveRegressor",
        "PatchExtractor": "sklearn.feature_extraction.image.PatchExtractor",
        "Perceptron": "sklearn.linear_model.Perceptron",
        "Pipeline": "sklearn.pipeline.Pipeline",
        "PoissonRegressor": "sklearn.linear_model.PoissonRegressor",
        "PolynomialCountSketch": "sklearn.kernel_approximation.PolynomialCountSketch",
        "PolynomialFeatures": "sklearn.preprocessing.PolynomialFeatures",
        "PowerTransformer": "sklearn.preprocessing.PowerTransformer",
        "QuadraticDiscriminantAnalysis": "sklearn.discriminant_analysis.QuadraticDiscriminantAnalysis",
        "QuantileRegressor": "sklearn.linear_model.QuantileRegressor",
        "QuantileTransformer": "sklearn.preprocessing.QuantileTransformer",
        "RANSACRegressor": "sklearn.linear_model.RANSACRegressor",
        "RBFSampler": "sklearn.kernel_approximation.RBFSampler",
        "RFE": "sklearn.feature_selection.RFE",
        "RFECV": "sklearn.feature_selection.RFECV",
        "RadiusNeighborsClassifier": "sklearn.neighbors.RadiusNeighborsClassifier",
        "RadiusNeighborsRegressor": "sklearn.neighbors.RadiusNeighborsRegressor",
        "RadiusNeighborsTransformer": "sklearn.neighbors.RadiusNeighborsTransformer",
        "RandomForestClassifier": "sklearn.ensemble.RandomForestClassifier",
        "RandomForestRegressor": "sklearn.ensemble.RandomForestRegressor",
        "RandomTreesEmbedding": "sklearn.ensemble.RandomTreesEmbedding",
        "RandomizedSearchCV": "sklearn.model_selection.RandomizedSearchCV",
        "RegressorChain": "sklearn.multioutput.RegressorChain",
        "Ridge": "sklearn.linear_model.Ridge",
        "RidgeCV": "sklearn.linear_model.RidgeCV",
        "RidgeClassifier": "sklearn.linear_model.RidgeClassifier",
        "RidgeClassifierCV": "sklearn.linear_model.RidgeClassifierCV",
        "RobustScaler": "sklearn.preprocessing.RobustScaler",
        "SGDClassifier": "sklearn.linear_model.SGDClassifier",
        "SGDOneClassSVM": "sklearn.linear_model.SGDOneClassSVM",
        "SGDRegressor": "sklearn.linear_model.SGDRegressor",
        "SVC": "sklearn.svm.SVC",
        "SVR": "sklearn.svm.SVR",
        "SelectFdr": "sklearn.feature_selection.SelectFdr",
        "SelectFpr": "sklearn.feature_selection.SelectFpr",
        "SelectFromModel": "sklearn.feature_selection.SelectFromModel",
        "SelectFwe": "sklearn.feature_selection.SelectFwe",
        "SelectKBest": "sklearn.feature_selection.SelectKBest",
        "SelectPercentile": "sklearn.feature_selection.SelectPercentile",
        "SelfTrainingClassifier": "sklearn.semi_supervised.SelfTrainingClassifier",
        "SequentialFeatureSelector": "sklearn.feature_selection.SequentialFeatureSelector",
        "ShrunkCovariance": "sklearn.covariance.ShrunkCovariance",
        "SimpleImputer": "sklearn.impute.SimpleImputer",
        "SkewedChi2Sampler": "sklearn.kernel_approximation.SkewedChi2Sampler",
        "SparseCoder": "sklearn.decomposition.SparseCoder",
        "SparsePCA": "sklearn.decomposition.SparsePCA",
        "SparseRandomProjection": "sklearn.random_projection.SparseRandomProjection",
        "SpectralBiclustering": "sklearn.cluster.SpectralBiclustering",
        "SpectralClustering": "sklearn.cluster.SpectralClustering",
        "SpectralCoclustering": "sklearn.cluster.SpectralCoclustering",
        "SpectralEmbedding": "sklearn.manifold.SpectralEmbedding",
        "SplineTransformer": "sklearn.preprocessing.SplineTransformer",
        "StackingClassifier": "sklearn.ensemble.StackingClassifier",
        "StackingRegressor": "sklearn.ensemble.StackingRegressor",
        "StandardScaler": "sklearn.preprocessing.StandardScaler",
        "TSNE": "sklearn.manifold.TSNE",
        "TargetEncoder": "sklearn.preprocessing.TargetEncoder",
        "TfidfTransformer": "sklearn.feature_extraction.text.TfidfTransformer",
        "TfidfVectorizer": "sklearn.feature_extraction.text.TfidfVectorizer",
        "TheilSenRegressor": "sklearn.linear_model.TheilSenRegressor",
        "TransformedTargetRegressor": "sklearn.compose.TransformedTargetRegressor",
        "TruncatedSVD": "sklearn.decomposition.TruncatedSVD",
        "TunedThresholdClassifierCV": "sklearn.model_selection.TunedThresholdClassifierCV",
        "TweedieRegressor": "sklearn.linear_model.TweedieRegressor",
        "VarianceThreshold": "sklearn.feature_selection.VarianceThreshold",
        "VotingClassifier": "sklearn.ensemble.VotingClassifier",
        "VotingRegressor": "sklearn.ensemble.VotingRegressor",
    }

    # todo - needs to be generated, for this a new util needs to be written
    # important: polymorphic objects like Pipeline or GridSearchCV
    # should be handled with care, as inheritance etc does not reflect the polymorphism
    # this may need manual curation for start, which should also be automated later
    _type_of_objs = {
        "StackingClassifier": "classifier",
        "VotingClassifier": "classifier",
        "StackingRegressor": "regressor",
        "VotingRegressor": "regressor",
        "Pipeline": ["classifier", "regressor"],
    }

    # todo: this also should be preindexed. can be generated from _type_of_objs
    # important to be mindful of objects with multiple types, e.g., Pipeline
    _objs_by_type = {
        "classifier": [
            "StackingClassifier",
            "VotingClassifier",
        ],
        "regressor": [
            "StackingRegressor",
            "VotingRegressor",
        ],
    }
