# ruff: noqa: E501
"""scikit-lego model package."""

from aiod.models.apis import _ModelPkgSklearnEstimator


class AiodPkg__ScikitLego(_ModelPkgSklearnEstimator):
    _tags = {
        "pkg_id": "__multiple",
        "python_dependencies": "scikit-lego",
        "pkg_pypi_name": "scikit-lego",
        "object_types": ["classifier", "regressor", "transformer", "outlier_detector", "clusterer"],
    }

    _obj_dict = {
        "BayesianGMMClassifier": "sklego.mixture.bayesian_gmm_classifier.BayesianGMMClassifier",
        "BayesianGMMOutlierDetector": "sklego.mixture.bayesian_gmm_detector.BayesianGMMOutlierDetector",
        "BayesianGaussianMixtureNB": "sklego.naive_bayes.BayesianGaussianMixtureNB",
        "BayesianKernelDensityClassifier": "sklego.neighbors.BayesianKernelDensityClassifier",
        "ColumnCapper": "sklego.preprocessing.columncapper.ColumnCapper",
        "ColumnDropper": "sklego.preprocessing.pandastransformers.ColumnDropper",
        "ColumnSelector": "sklego.preprocessing.pandastransformers.ColumnSelector",
        "ConfusionBalancer": "sklego.meta.confusion_balancer.ConfusionBalancer",
        "DeadZoneRegressor": "sklego.linear_model.DeadZoneRegressor",
        "DebugPipeline": "sklego.pipeline.DebugPipeline",
        "DemographicParityClassifier": "sklego.linear_model.DemographicParityClassifier",
        "DictMapper": "sklego.preprocessing.dictmapper.DictMapper",
        "EqualOpportunityClassifier": "sklego.linear_model.EqualOpportunityClassifier",
        "EstimatorTransformer": "sklego.meta.estimator_transformer.EstimatorTransformer",
        "FormulaicTransformer": "sklego.preprocessing.formulaictransformer.FormulaicTransformer",
        "GMMClassifier": "sklego.mixture.gmm_classifier.GMMClassifier",
        "GMMOutlierDetector": "sklego.mixture.gmm_outlier_detector.GMMOutlierDetector",
        "GaussianMixtureNB": "sklego.naive_bayes.GaussianMixtureNB",
        "GroupedClassifier": "sklego.meta.grouped_predictor.GroupedClassifier",
        "GroupedRegressor": "sklego.meta.grouped_predictor.GroupedRegressor",
        "GroupedTransformer": "sklego.meta.grouped_transformer.GroupedTransformer",
        "HierarchicalClassifier": "sklego.meta.hierarchical_predictor.HierarchicalClassifier",
        "HierarchicalRegressor": "sklego.meta.hierarchical_predictor.HierarchicalRegressor",
        "IdentityTransformer": "sklego.preprocessing.identitytransformer.IdentityTransformer",
        "ImbalancedLinearRegression": "sklego.linear_model.ImbalancedLinearRegression",
        "InformationFilter": "sklego.preprocessing.projections.InformationFilter",
        "IntervalEncoder": "sklego.preprocessing.intervalencoder.IntervalEncoder",
        "LADRegression": "sklego.linear_model.LADRegression",
        "LinearEmbedder": "sklego.preprocessing.linearembedder.LinearEmbedder",
        "LowessRegression": "sklego.linear_model.LowessRegression",
        "MaximumRelevanceMinimumRedundancy": "sklego.feature_selection.mrmr.MaximumRelevanceMinimumRedundancy",
        "MonotonicSplineTransformer": "sklego.preprocessing.monotonicspline.MonotonicSplineTransformer",
        "OrdinalClassifier": "sklego.meta.ordinal_classification.OrdinalClassifier",
        "OrthogonalTransformer": "sklego.preprocessing.projections.OrthogonalTransformer",
        "OutlierClassifier": "sklego.meta.outlier_classifier.OutlierClassifier",
        "OutlierRemover": "sklego.preprocessing.outlier_remover.OutlierRemover",
        "PCAOutlierDetection": "sklego.decomposition.pca_reconstruction.PCAOutlierDetection",
        "PandasTypeSelector": "sklego.preprocessing.pandastransformers.PandasTypeSelector",
        "ProbWeightRegression": "sklego.linear_model.ProbWeightRegression",
        "QuantileRegression": "sklego.linear_model.QuantileRegression",
        "RandomAdder": "sklego.preprocessing.randomadder.RandomAdder",
        "RandomRegressor": "sklego.dummy.RandomRegressor",
        "RegressionOutlierDetector": "sklego.meta.regression_outlier_detector.RegressionOutlierDetector",
        "RepeatingBasisFunction": "sklego.preprocessing.repeatingbasis.RepeatingBasisFunction",
        "SubjectiveClassifier": "sklego.meta.subjective_classifier.SubjectiveClassifier",
        "Thresholder": "sklego.meta.thresholder.Thresholder",
        "TypeSelector": "sklego.preprocessing.pandastransformers.TypeSelector",
        "UMAPOutlierDetection": "sklego.decomposition.umap_reconstruction.UMAPOutlierDetection",
        "ZeroInflatedRegressor": "sklego.meta.zero_inflated_regressor.ZeroInflatedRegressor",
    }

    _type_of_objs = {
        "BayesianGMMClassifier": "classifier",
        "BayesianGMMOutlierDetector": "outlier_detector",
        "BayesianGaussianMixtureNB": "classifier",
        "BayesianKernelDensityClassifier": "classifier",
        "ColumnCapper": "transformer",
        "ColumnDropper": "transformer",
        "ColumnSelector": "transformer",
        "ConfusionBalancer": "classifier",
        "DeadZoneRegressor": "regressor",
        "DebugPipeline": ["clusterer", "regressor", "transformer", "classifier", "outlier_detector"],
        "DemographicParityClassifier": "classifier",
        "DictMapper": "transformer",
        "EqualOpportunityClassifier": "classifier",
        "EstimatorTransformer": "transformer",
        "FormulaicTransformer": "transformer",
        "GMMClassifier": "classifier",
        "GMMOutlierDetector": "outlier_detector",
        "GaussianMixtureNB": "classifier",
        "GroupedClassifier": "classifier",
        "GroupedRegressor": "regressor",
        "GroupedTransformer": "transformer",
        "HierarchicalClassifier": "classifier",
        "HierarchicalRegressor": "regressor",
        "IdentityTransformer": "transformer",
        "ImbalancedLinearRegression": "regressor",
        "InformationFilter": "transformer",
        "IntervalEncoder": "transformer",
        "LADRegression": "regressor",
        "LinearEmbedder": "transformer",
        "LowessRegression": "regressor",
        "MaximumRelevanceMinimumRedundancy": "transformer",
        "MonotonicSplineTransformer": "transformer",
        "OrdinalClassifier": "classifier",
        "OrthogonalTransformer": "transformer",
        "OutlierClassifier": "classifier",
        "OutlierRemover": "transformer",
        "PCAOutlierDetection": "outlier_detector",
        "PandasTypeSelector": "transformer",
        "ProbWeightRegression": "regressor",
        "QuantileRegression": "regressor",
        "RandomAdder": "transformer",
        "RandomRegressor": "regressor",
        "RegressionOutlierDetector": "outlier_detector",
        "RepeatingBasisFunction": "transformer",
        "SubjectiveClassifier": "classifier",
        "Thresholder": "classifier",
        "TypeSelector": "transformer",
        "UMAPOutlierDetection": "outlier_detector",
        "ZeroInflatedRegressor": "regressor",
    }

    _objs_by_type = {
        "classifier": [
            "BayesianGMMClassifier",
            "BayesianGaussianMixtureNB",
            "BayesianKernelDensityClassifier",
            "ConfusionBalancer",
            "DebugPipeline",
            "DemographicParityClassifier",
            "EqualOpportunityClassifier",
            "GMMClassifier",
            "GaussianMixtureNB",
            "GroupedClassifier",
            "HierarchicalClassifier",
            "OrdinalClassifier",
            "OutlierClassifier",
            "SubjectiveClassifier",
            "Thresholder",
        ],
        "regressor": [
            "DeadZoneRegressor",
            "DebugPipeline",
            "GroupedRegressor",
            "HierarchicalRegressor",
            "ImbalancedLinearRegression",
            "LADRegression",
            "LowessRegression",
            "ProbWeightRegression",
            "QuantileRegression",
            "RandomRegressor",
            "ZeroInflatedRegressor",
        ],
        "transformer": [
            "ColumnCapper",
            "ColumnDropper",
            "ColumnSelector",
            "DebugPipeline",
            "DictMapper",
            "EstimatorTransformer",
            "FormulaicTransformer",
            "GroupedTransformer",
            "IdentityTransformer",
            "InformationFilter",
            "IntervalEncoder",
            "LinearEmbedder",
            "MaximumRelevanceMinimumRedundancy",
            "MonotonicSplineTransformer",
            "OrthogonalTransformer",
            "OutlierRemover",
            "PandasTypeSelector",
            "RandomAdder",
            "RepeatingBasisFunction",
            "TypeSelector",
        ],
        "outlier_detector": [
            "BayesianGMMOutlierDetector",
            "DebugPipeline",
            "GMMOutlierDetector",
            "PCAOutlierDetection",
            "RegressionOutlierDetector",
            "UMAPOutlierDetection",
        ],
        "clusterer": [
            "DebugPipeline",
        ],
    }
