# ruff: noqa: E501
"""skpro probabilistic estimator and metric index."""

from aiod.models.apis import _ModelPkgSklearnEstimator
from aiod.utils._indexing._preindex_sklearn import _generate_sklearn_objs_by_type


class AiodPkg__skpro(_ModelPkgSklearnEstimator):
    _tags = {
        "pkg_id": "__multiple",
        "python_dependencies": "skpro",
        "pkg_pypi_name": "skpro",
        "object_types": ["metric", "metric_distr", "regressor_proba"],
    }

    # obtained from skpro.registry.all_objects(object_types=["regressor_proba", "metric"])
    # distributions are intentionally excluded for now
    _obj_dict = {
        "AFTFisk": "skpro.survival.aft.AFTFisk",
        "AFTLogNormal": "skpro.survival.aft.AFTLogNormal",
        "AFTWeibull": "skpro.survival.aft.AFTWeibull",
        "ARDRegression": "skpro.regression.linear.ARDRegression",
        "AUCalibration": "skpro.metrics.AUCalibration",
        "AalenAdditive": "skpro.survival.additive.AalenAdditive",
        "BaggingRegressor": "skpro.regression.ensemble.BaggingRegressor",
        "BayesianConjugateLinearRegressor": "skpro.regression.bayesian.BayesianConjugateLinearRegressor",
        "BayesianLinearRegressor": "skpro.regression.bayesian.BayesianLinearRegressor",
        "BayesianRidge": "skpro.regression.linear.BayesianRidge",
        "BootstrapRegressor": "skpro.regression.bootstrap.BootstrapRegressor",
        "CRPS": "skpro.metrics.CRPS",
        "ConcordanceHarrell": "skpro.metrics.survival.ConcordanceHarrell",
        "ConditionUncensored": "skpro.survival.compose.ConditionUncensored",
        "ConstraintViolation": "skpro.metrics.ConstraintViolation",
        "CoxNet": "skpro.survival.coxph.CoxNet",
        "CoxPH": "skpro.survival.coxph.CoxPH",
        "CoxPHSkSurv": "skpro.survival.coxph.CoxPHSkSurv",
        "CoxPHlifelines": "skpro.survival.coxph.CoxPHlifelines",
        "CyclicBoosting": "skpro.regression.cyclic_boosting.CyclicBoosting",
        "DeltaPointRegressor": "skpro.regression.delta.DeltaPointRegressor",
        "DummyProbaRegressor": "skpro.regression.dummy.DummyProbaRegressor",
        "EmpiricalCoverage": "skpro.metrics.EmpiricalCoverage",
        "EnbpiRegressor": "skpro.regression.enbpi.EnbpiRegressor",
        "FitUncensored": "skpro.survival.compose.FitUncensored",
        "GAMRegressor": "skpro.regression.gam.GAMRegressor",
        "GLMRegressor": "skpro.regression.linear.GLMRegressor",
        "GaussianProcess": "skpro.regression.gp.GaussianProcess",
        "GlumRegressor": "skpro.regression.linear.GlumRegressor",
        "GridSearchCV": "skpro.model_selection.GridSearchCV",
        "HistBinnedProbaRegressor": "skpro.regression.binned.HistBinnedProbaRegressor",
        "IntervalWidth": "skpro.metrics.IntervalWidth",
        "LinearizedLogLoss": "skpro.metrics.LinearizedLogLoss",
        "LogLoss": "skpro.metrics.LogLoss",
        "MapieConformalizedQuantileRegressor": "skpro.regression.conformal.MapieConformalizedQuantileRegressor",
        "MapieCrossConformalRegressor": "skpro.regression.conformal.MapieCrossConformalRegressor",
        "MapieJackknifeAfterBootstrapRegressor": "skpro.regression.jackknife.MapieJackknifeAfterBootstrapRegressor",
        "MapieRegressor": "skpro.regression.mapie.MapieRegressor",
        "MapieSplitConformalRegressor": "skpro.regression.conformal.MapieSplitConformalRegressor",
        "MultipleQuantileRegressor": "skpro.regression.multiquantile.MultipleQuantileRegressor",
        "NGBoostRegressor": "skpro.regression.ensemble.NGBoostRegressor",
        "NGBoostSurvival": "skpro.survival.ensemble.NGBoostSurvival",
        "OndilOnlineGamlss": "skpro.regression.ondil.OndilOnlineGamlss",
        "OnlineDontRefit": "skpro.regression.online.OnlineDontRefit",
        "OnlineRefit": "skpro.regression.online.OnlineRefit",
        "OnlineRefitEveryN": "skpro.regression.online.OnlineRefitEveryN",
        "PinballLoss": "skpro.metrics.PinballLoss",
        "SkproPipeline": "skpro.regression.compose.Pipeline",
        "PoissonRegressor": "skpro.regression.linear.PoissonRegressor",
        "RandomizedSearchCV": "skpro.model_selection.RandomizedSearchCV",
        "ResidualDouble": "skpro.regression.residual.ResidualDouble",
        "SPLL": "skpro.metrics.survival.SPLL",
        "SklearnProbaReg": "skpro.regression.adapters.sklearn.SklearnProbaReg",
        "SquaredDistrLoss": "skpro.metrics.SquaredDistrLoss",
        "SurvGradBoostCompSkSurv": "skpro.survival.ensemble.SurvGradBoostCompSkSurv",
        "SurvGradBoostSkSurv": "skpro.survival.ensemble.SurvGradBoostSkSurv",
        "SurvivalForestSkSurv": "skpro.survival.ensemble.SurvivalForestSkSurv",
        "SurvivalForestXtraSkSurv": "skpro.survival.ensemble.SurvivalForestXtraSkSurv",
        "SurvivalTree": "skpro.survival.tree.SurvivalTree",
        "TransformedTargetRegressor": "skpro.regression.compose.TransformedTargetRegressor",
        "XGBoostLSS": "skpro.regression.xgboostlss.XGBoostLSS",
    }

    _type_of_objs = {
        "AFTFisk": "regressor_proba",
        "AFTLogNormal": "regressor_proba",
        "AFTWeibull": "regressor_proba",
        "ARDRegression": "regressor_proba",
        "AUCalibration": ["metric", "metric_distr"],
        "AalenAdditive": "regressor_proba",
        "BaggingRegressor": "regressor_proba",
        "BayesianConjugateLinearRegressor": "regressor_proba",
        "BayesianLinearRegressor": "regressor_proba",
        "BayesianRidge": "regressor_proba",
        "BootstrapRegressor": "regressor_proba",
        "CRPS": ["metric", "metric_distr"],
        "ConcordanceHarrell": ["metric", "metric_distr"],
        "ConditionUncensored": "regressor_proba",
        "ConstraintViolation": "metric",
        "CoxNet": "regressor_proba",
        "CoxPH": "regressor_proba",
        "CoxPHSkSurv": "regressor_proba",
        "CoxPHlifelines": "regressor_proba",
        "CyclicBoosting": "regressor_proba",
        "DeltaPointRegressor": "regressor_proba",
        "DummyProbaRegressor": "regressor_proba",
        "EmpiricalCoverage": "metric",
        "EnbpiRegressor": "regressor_proba",
        "FitUncensored": "regressor_proba",
        "GAMRegressor": "regressor_proba",
        "GLMRegressor": "regressor_proba",
        "GaussianProcess": "regressor_proba",
        "GlumRegressor": "regressor_proba",
        "GridSearchCV": "regressor_proba",
        "HistBinnedProbaRegressor": "regressor_proba",
        "IntervalWidth": "metric",
        "LinearizedLogLoss": ["metric", "metric_distr"],
        "LogLoss": ["metric", "metric_distr"],
        "MapieConformalizedQuantileRegressor": "regressor_proba",
        "MapieCrossConformalRegressor": "regressor_proba",
        "MapieJackknifeAfterBootstrapRegressor": "regressor_proba",
        "MapieRegressor": "regressor_proba",
        "MapieSplitConformalRegressor": "regressor_proba",
        "MultipleQuantileRegressor": "regressor_proba",
        "NGBoostRegressor": "regressor_proba",
        "NGBoostSurvival": "regressor_proba",
        "OndilOnlineGamlss": "regressor_proba",
        "OnlineDontRefit": "regressor_proba",
        "OnlineRefit": "regressor_proba",
        "OnlineRefitEveryN": "regressor_proba",
        "PinballLoss": "metric",
        "SkproPipeline": "regressor_proba",
        "PoissonRegressor": "regressor_proba",
        "RandomizedSearchCV": "regressor_proba",
        "ResidualDouble": "regressor_proba",
        "SPLL": ["metric", "metric_distr"],
        "SklearnProbaReg": "regressor_proba",
        "SquaredDistrLoss": ["metric", "metric_distr"],
        "SurvGradBoostCompSkSurv": "regressor_proba",
        "SurvGradBoostSkSurv": "regressor_proba",
        "SurvivalForestSkSurv": "regressor_proba",
        "SurvivalForestXtraSkSurv": "regressor_proba",
        "SurvivalTree": "regressor_proba",
        "TransformedTargetRegressor": "regressor_proba",
        "XGBoostLSS": "regressor_proba",
    }

    _objs_by_type = _generate_sklearn_objs_by_type(_type_of_objs)