# flake8: noqa: E501
"""sktime estimator index."""

from aiod.models.apis import _ModelPkgSklearnEstimator


class AiodPkg__sktime(_ModelPkgSklearnEstimator):
    _tags = {
        "pkg_id": "__multiple",
        "python_dependencies": "sktime",
        "pkg_pypi_name": "sktime",
        "object_types": [
            "aligner",
            "catalogue",
            "classifier",
            "clusterer",
            "dataset_classification",
            "dataset_forecasting",
            "dataset_regression",
            "detector",
            "early_classifier",
            "estimator",
            "forecaster",
            "global_forecaster",
            "metric_detection",
            "metric_forecasting",
            "metric_forecasting_proba",
            "network",
            "param_est",
            "reconciler",
            "regressor",
            "splitter",
            "transformer",
            "transformer-pairwise",
            "transformer-pairwise-panel",
        ],
    }

    _obj_dict = {
        "ACSF1": "sktime.datasets.classification.acsf1.ACSF1",
        "ADICVTransformer": "sktime.transformations.series.adi_cv.ADICVTransformer",
        "ARARForecaster": "sktime.forecasting.arar._arar_forecaster.ARARForecaster",
        "ARCH": "sktime.forecasting.arch._uarch.ARCH",
        "ARDL": "sktime.forecasting.ardl.ARDL",
        "ARIMA": "sktime.forecasting.arima._pmdarima.ARIMA",
        "ARLagOrderSelector": "sktime.param_est.lag._arlag.ARLagOrderSelector",
        "AUCalibration": "sktime.performance_metrics.forecasting.probabilistic._classes.AUCalibration",
        "AcorrLjungbox": "sktime.param_est.lag._acorrljungbox.AcorrLjungbox",
        "AggrDist": "sktime.dists_kernels.compose_tab_to_panel.AggrDist",
        "Aggregator": "sktime.transformations.hierarchical.aggregate.Aggregator",
        "Airline": "sktime.datasets.forecasting.airline.Airline",
        "AlignerDTW": "sktime.alignment.dtw_python.AlignerDTW",
        "AlignerDTWfromDist": "sktime.alignment.dtw_python.AlignerDTWfromDist",
        "AlignerDtwDtai": "sktime.alignment.dtaidist.AlignerDtwDtai",
        "AlignerDtwNumba": "sktime.alignment.dtw_numba.AlignerDtwNumba",
        "AlignerEditNumba": "sktime.alignment.edit_numba.AlignerEditNumba",
        "AlignerLuckyDtw": "sktime.alignment.lucky.AlignerLuckyDtw",
        "AlignerNaive": "sktime.alignment.naive.AlignerNaive",
        "ArrowHead": "sktime.datasets.classification.arrow_head.ArrowHead",
        "Arsenal": "sktime.classification.kernel_based._arsenal.Arsenal",
        "AutoARIMA": "sktime.forecasting.arima._pmdarima.AutoARIMA",
        "AutoCorrelationTransformer": "sktime.transformations.series.acf.AutoCorrelationTransformer",
        "AutoETS": "sktime.forecasting.ets.AutoETS",
        "AutoEnsembleForecaster": "sktime.forecasting.compose._ensemble.AutoEnsembleForecaster",
        "AutoREG": "sktime.forecasting.auto_reg.AutoREG",
        "AutoTS": "sktime.forecasting.autots.AutoTS",
        "BATS": "sktime.forecasting.bats.BATS",
        "BKFilter": "sktime.transformations.series.bkfilter.BKFilter",
        "BOSSEnsemble": "sktime.classification.dictionary_based._boss.BOSSEnsemble",
        "BOSSVSClassifierPyts": "sktime.classification.dictionary_based._boss_pyts.BOSSVSClassifierPyts",
        "BaggingClassifier": "sktime.classification.ensemble._bagging.BaggingClassifier",
        "BaggingForecaster": "sktime.forecasting.compose._bagging.BaggingForecaster",
        "BasicMotions": "sktime.datasets.classification.basic_motions.BasicMotions",
        "BinarySegmentation": "sktime.detection.bs.BinarySegmentation",
        "Bollinger": "sktime.transformations.series.bollinger.Bollinger",
        "BottomUpReconciler": "sktime.transformations.hierarchical.reconcile._bottom_up.BottomUpReconciler",
        "BoxCoxBiasAdjustedForecaster": "sktime.forecasting.boxcox_bias_adjusted_forecaster.BoxCoxBiasAdjustedForecaster",
        "BoxCoxTransformer": "sktime.transformations.series.boxcox.BoxCoxTransformer",
        "BreakvarHeteroskedasticityTest": "sktime.param_est.stationarity._sm_breakvar.BreakvarHeteroskedasticityTest",
        "CAPA": "sktime.detection.skchange_aseg.capa.CAPA",
        "CFFilter": "sktime.transformations.series.cffilter.CFFilter",
        "CINNForecaster": "sktime.forecasting.conditional_invertible_neural_network.CINNForecaster",
        "CNNClassifier": "sktime.classification.deep_learning.cnn.CNNClassifier",
        "CNNNetwork": "sktime.networks.cnn.CNNNetwork",
        "CNNRegressor": "sktime.regression.deep_learning.cnn.CNNRegressor",
        "CNTCClassifier": "sktime.classification.deep_learning.cntc.CNTCClassifier",
        "CNTCNetwork": "sktime.networks.cntc.CNTCNetwork",
        "CNTCRegressor": "sktime.regression.deep_learning.cntc.CNTCRegressor",
        "CRPS": "sktime.performance_metrics.forecasting.probabilistic._classes.CRPS",
        "CanonicalIntervalForest": "sktime.classification.interval_based._cif.CanonicalIntervalForest",
        "Catch22": "sktime.transformations.panel.catch22.Catch22",
        "Catch22Classifier": "sktime.classification.feature_based._catch22_classifier.Catch22Classifier",
        "Catch22Wrapper": "sktime.transformations.panel.catch22wrapper.Catch22Wrapper",
        "ChronosForecaster": "sktime.forecasting.chronos.ChronosForecaster",
        "CircularBinarySegmentation": "sktime.detection.skchange_aseg.circular_binseg.CircularBinarySegmentation",
        "ClaSPSegmentation": "sktime.detection.clasp.ClaSPSegmentation",
        "ClaSPTransformer": "sktime.transformations.series.clasp.ClaSPTransformer",
        "ClassifierPipeline": "sktime.classification.compose._pipeline.ClassifierPipeline",
        "ClearSky": "sktime.transformations.series.clear_sky.ClearSky",
        "ClusterSegmenter": "sktime.detection.clust.ClusterSegmenter",
        "ClustererAsTransformer": "sktime.clustering.compose._as_transform.ClustererAsTransformer",
        "ClustererPipeline": "sktime.clustering.compose._pipeline.ClustererPipeline",
        "ColumnConcatenator": "sktime.transformations.panel.compose.ColumnConcatenator",
        "ColumnEnsembleClassifier": "sktime.classification.compose._column_ensemble.ColumnEnsembleClassifier",
        "ColumnEnsembleForecaster": "sktime.forecasting.compose._column_ensemble.ColumnEnsembleForecaster",
        "ColumnEnsembleTransformer": "sktime.transformations.compose._column.ColumnEnsembleTransformer",
        "ColumnSelect": "sktime.transformations.series.subset.ColumnSelect",
        "ColumnTransformer": "sktime.transformations.panel.compose.ColumnTransformer",
        "ColumnwiseTransformer": "sktime.transformations.compose._column.ColumnwiseTransformer",
        "CombineTransformers": "sktime.transformations.compose._arithmetic.CombineTransformers",
        "CombinedDistance": "sktime.dists_kernels.algebra.CombinedDistance",
        "ComposableTimeSeriesForestClassifier": "sktime.classification.ensemble._ctsf.ComposableTimeSeriesForestClassifier",
        "ComposableTimeSeriesForestRegressor": "sktime.regression.compose._ensemble.ComposableTimeSeriesForestRegressor",
        "ConditionalDeseasonalizer": "sktime.transformations.series.detrend._deseasonalize.ConditionalDeseasonalizer",
        "ConformalIntervals": "sktime.forecasting.conformal.ConformalIntervals",
        "ConstantPwTrafoPanel": "sktime.dists_kernels.dummy.ConstantPwTrafoPanel",
        "ConstraintViolation": "sktime.performance_metrics.forecasting.probabilistic._classes.ConstraintViolation",
        "ContractableBOSS": "sktime.classification.dictionary_based._cboss.ContractableBOSS",
        "ConvTimeNetClassifier": "sktime.classification.deep_learning.convtimenet.ConvTimeNetClassifier",
        "ConvTimeNetForecaster": "sktime.forecasting.convtimenet.ConvTimeNetForecaster",
        "CosineTransformer": "sktime.transformations.series.cos.CosineTransformer",
        "CountryHolidaysTransformer": "sktime.transformations.series.holiday.country_holidays.CountryHolidaysTransformer",
        "Croston": "sktime.forecasting.croston.Croston",
        "CtwDistTslearn": "sktime.dists_kernels.ctw.CtwDistTslearn",
        "CurveFitForecaster": "sktime.forecasting.trend._curve_fit_forecaster.CurveFitForecaster",
        "CutoffFhSplitter": "sktime.split.cutoff.CutoffFhSplitter",
        "CutoffSplitter": "sktime.split.cutoff.CutoffSplitter",
        "DOBIN": "sktime.transformations.series.dobin.DOBIN",
        "DWTTransformer": "sktime.transformations.panel.dwt.DWTTransformer",
        "DartsLinearRegressionModel": "sktime.forecasting.darts.DartsLinearRegressionModel",
        "DartsRegressionModel": "sktime.forecasting.darts.DartsRegressionModel",
        "DartsXGBModel": "sktime.forecasting.darts.DartsXGBModel",
        "DateTimeFeatures": "sktime.transformations.series.date.DateTimeFeatures",
        "DegreeDayFeatures": "sktime.transformations.series.degree_day.DegreeDayFeatures",
        "DerivativeSlopeTransformer": "sktime.transformations.panel.summarize._extract.DerivativeSlopeTransformer",
        "Deseasonalizer": "sktime.transformations.series.detrend._deseasonalize.Deseasonalizer",
        "DetectionCount": "sktime.performance_metrics.detection._count.DetectionCount",
        "DetectorAsTransformer": "sktime.detection.compose._as_transform.DetectorAsTransformer",
        "DetectorPipeline": "sktime.detection.compose._pipeline.DetectorPipeline",
        "Detrender": "sktime.transformations.series.detrend._detrend.Detrender",
        "Differencer": "sktime.transformations.series.difference.Differencer",
        "DilationMappingTransformer": "sktime.transformations.series.dilation_mapping.DilationMappingTransformer",
        "DirRecTabularRegressionForecaster": "sktime.forecasting.compose._reduce.DirRecTabularRegressionForecaster",
        "DirRecTimeSeriesRegressionForecaster": "sktime.forecasting.compose._reduce.DirRecTimeSeriesRegressionForecaster",
        "DirectReductionForecaster": "sktime.forecasting.compose._reduce.DirectReductionForecaster",
        "DirectTabularRegressionForecaster": "sktime.forecasting.compose._reduce.DirectTabularRegressionForecaster",
        "DirectTimeSeriesRegressionForecaster": "sktime.forecasting.compose._reduce.DirectTimeSeriesRegressionForecaster",
        "DirectedChamfer": "sktime.performance_metrics.detection._chamfer.DirectedChamfer",
        "DirectedHausdorff": "sktime.performance_metrics.detection._hausdorff.DirectedHausdorff",
        "DistFromAligner": "sktime.dists_kernels.compose_from_align.DistFromAligner",
        "DistFromKernel": "sktime.dists_kernels.dist_to_kern.DistFromKernel",
        "DistanceFeatures": "sktime.transformations.panel.compose_distance.DistanceFeatures",
        "DontUpdate": "sktime.forecasting.stream._update.DontUpdate",
        "DoubleMLForecaster": "sktime.forecasting.causal._dmlf.DoubleMLForecaster",
        "DrCIF": "sktime.classification.interval_based._drcif.DrCIF",
        "DropNA": "sktime.transformations.series.dropna.DropNA",
        "DtwDist": "sktime.dists_kernels.dtw._dtw_sktime.DtwDist",
        "DtwDistTslearn": "sktime.dists_kernels.dtw._dtw_tslearn.DtwDistTslearn",
        "DtwDtaidistMultiv": "sktime.dists_kernels.dtw._dtw_dtaidist.DtwDtaidistMultiv",
        "DtwDtaidistUniv": "sktime.dists_kernels.dtw._dtw_dtaidist.DtwDtaidistUniv",
        "DtwPythonDist": "sktime.dists_kernels.dtw._dtw_python.DtwPythonDist",
        "DummyClassificationCatalogue": "sktime.catalogues.classification.dummy._dummy_classification.DummyClassificationCatalogue",
        "DummyClassifier": "sktime.classification.dummy._dummy.DummyClassifier",
        "DummyForecastingCatalogue": "sktime.catalogues.forecasting.dummy._dummy_forecasting.DummyForecastingCatalogue",
        "DummyGlobalForecaster": "sktime.forecasting.dummy_global.DummyGlobalForecaster",
        "DummyRegressor": "sktime.regression.dummy._dummy.DummyRegressor",
        "DummyRegularAnomalies": "sktime.detection.dummy._dummy_regular_an.DummyRegularAnomalies",
        "DummyRegularChangePoints": "sktime.detection.dummy._dummy_regular_cp.DummyRegularChangePoints",
        "DynamicFactor": "sktime.forecasting.dynamic_factor.DynamicFactor",
        "EAgglo": "sktime.detection.eagglo.EAgglo",
        "ESRNNForecaster": "sktime.forecasting.es_rnn.ESRNNForecaster",
        "EditDist": "sktime.dists_kernels.edit_dist.EditDist",
        "ElasticEnsemble": "sktime.classification.distance_based._elastic_ensemble.ElasticEnsemble",
        "ElbowClassPairwise": "sktime.transformations.panel.channel_selection.ElbowClassPairwise",
        "ElbowClassSum": "sktime.transformations.panel.channel_selection.ElbowClassSum",
        "EmpiricalCoverage": "sktime.performance_metrics.forecasting.probabilistic._classes.EmpiricalCoverage",
        "EnbPIForecaster": "sktime.forecasting.enbpi.EnbPIForecaster",
        "EnsembleForecaster": "sktime.forecasting.compose._ensemble.EnsembleForecaster",
        "ExpandingCutoffSplitter": "sktime.split.expandingcutoff.ExpandingCutoffSplitter",
        "ExpandingGreedySplitter": "sktime.split.expandinggreedy.ExpandingGreedySplitter",
        "ExpandingSlidingWindowSplitter": "sktime.split.expandingslidingwindow.ExpandingSlidingWindowSplitter",
        "ExpandingWindowSplitter": "sktime.split.expandingwindow.ExpandingWindowSplitter",
        "ExponentTransformer": "sktime.transformations.series.exponent.ExponentTransformer",
        "ExponentialSmoothing": "sktime.forecasting.exp_smoothing.ExponentialSmoothing",
        "FABBA": "sktime.transformations.series.fabba.FABBA",
        "FCNClassifier": "sktime.classification.deep_learning.fcn.FCNClassifier",
        "FCNNetwork": "sktime.networks.fcn.FCNNetwork",
        "FCNRegressor": "sktime.regression.deep_learning.fcn.FCNRegressor",
        "FallbackForecaster": "sktime.forecasting.compose._fallback.FallbackForecaster",
        "FeatureSelection": "sktime.transformations.series.feature_selection.FeatureSelection",
        "FeatureUnion": "sktime.transformations.compose._featureunion.FeatureUnion",
        "FhPlexForecaster": "sktime.forecasting.compose._fhplex.FhPlexForecaster",
        "Filter": "sktime.transformations.series.filter.Filter",
        "FinancialHolidaysTransformer": "sktime.transformations.series.holiday.financial_holidays.FinancialHolidaysTransformer",
        "FitInTransform": "sktime.transformations.compose._fitintransform.FitInTransform",
        "FittedParamExtractor": "sktime.transformations.panel.summarize._extract.FittedParamExtractor",
        "FixedParams": "sktime.param_est.fixed.FixedParams",
        "FlatDist": "sktime.dists_kernels.compose_tab_to_panel.FlatDist",
        "ForecastByLevel": "sktime.forecasting.compose._grouped.ForecastByLevel",
        "ForecastKnownValues": "sktime.forecasting.dummy.ForecastKnownValues",
        "ForecastX": "sktime.forecasting.compose._pipeline.ForecastX",
        "ForecastingData": "sktime.datasets.forecasting.monash._forecasting_data.ForecastingData",
        "ForecastingGridSearchCV": "sktime.forecasting.model_selection._gridsearch.ForecastingGridSearchCV",
        "ForecastingHorizonSplitter": "sktime.split.fh.ForecastingHorizonSplitter",
        "ForecastingOptCV": "hyperactive.integrations.sktime._forecasting.ForecastingOptCV",
        "ForecastingOptunaSearchCV": "sktime.forecasting.model_selection._optuna.ForecastingOptunaSearchCV",
        "ForecastingPipeline": "sktime.forecasting.compose._pipeline.ForecastingPipeline",
        "ForecastingRandomizedSearchCV": "sktime.forecasting.model_selection._randomsearch.ForecastingRandomizedSearchCV",
        "ForecastingSkoptSearchCV": "sktime.forecasting.model_selection._skopt.ForecastingSkoptSearchCV",
        "FourierFeatures": "sktime.transformations.series.fourier.FourierFeatures",
        "FourierTransform": "sktime.transformations.series.fourier.FourierTransform",
        "FreshPRINCE": "sktime.classification.feature_based._fresh_prince.FreshPRINCE",
        "FunctionParamFitter": "sktime.param_est.compose._func_fitter.FunctionParamFitter",
        "FunctionTransformer": "sktime.transformations.series.func_transform.FunctionTransformer",
        "GAKernel": "sktime.dists_kernels.gak.GAKernel",
        "GMMHMM": "sktime.detection.hmm_learn.gmm.GMMHMM",
        "GRUClassifier": "sktime.classification.deep_learning.gru.GRUClassifier",
        "GRUFCNNClassifier": "sktime.classification.deep_learning.gru.GRUFCNNClassifier",
        "GaussianHMM": "sktime.detection.hmm_learn.gaussian.GaussianHMM",
        "GeometricMeanAbsoluteError": "sktime.performance_metrics.forecasting._gmae.GeometricMeanAbsoluteError",
        "GeometricMeanRelativeAbsoluteError": "sktime.performance_metrics.forecasting._gmrelae.GeometricMeanRelativeAbsoluteError",
        "GeometricMeanRelativeSquaredError": "sktime.performance_metrics.forecasting._gmrelse.GeometricMeanRelativeSquaredError",
        "GeometricMeanSquaredError": "sktime.performance_metrics.forecasting._gmse.GeometricMeanSquaredError",
        "GreedyGaussianSegmentation": "sktime.detection.ggs.GreedyGaussianSegmentation",
        "GreykiteForecaster": "sktime.forecasting.greykite.GreykiteForecaster",
        "GroupbyCategoryForecaster": "sktime.forecasting.compose._grouped.GroupbyCategoryForecaster",
        "GunPoint": "sktime.datasets.classification.gunpoint.GunPoint",
        "HCrystalBallAdapter": "sktime.forecasting.adapters._hcrystalball.HCrystalBallAdapter",
        "HFTransformersForecaster": "sktime.forecasting.hf_transformers_forecaster.HFTransformersForecaster",
        "HIVECOTEV1": "sktime.classification.hybrid._hivecote_v1.HIVECOTEV1",
        "HIVECOTEV2": "sktime.classification.hybrid._hivecote_v2.HIVECOTEV2",
        "HMM": "sktime.detection.hmm.HMM",
        "HOG1DTransformer": "sktime.transformations.panel.hog1d.HOG1DTransformer",
        "HPFilter": "sktime.transformations.series.hpfilter.HPFilter",
        "HampelFilter": "sktime.transformations.series.outlier_detection.HampelFilter",
        "Hidalgo": "sktime.transformations.series.hidalgo.Hidalgo",
        "HierarchicalProphet": "sktime.forecasting.prophetverse.HierarchicalProphet",
        "HierarchicalSalesToydata": "sktime.datasets.forecasting.hierarchical_sales_toydata.HierarchicalSalesToydata",
        "HierarchyEnsembleForecaster": "sktime.forecasting.compose._hierarchy_ensemble.HierarchyEnsembleForecaster",
        "HolidayFeatures": "sktime.transformations.series.holiday._holidayfeats.HolidayFeatures",
        "HurstExponentTransformer": "sktime.transformations.series.hurst.HurstExponentTransformer",
        "Id": "sktime.transformations.compose._id.Id",
        "IgnoreX": "sktime.forecasting.compose._ignore_x.IgnoreX",
        "Imputer": "sktime.transformations.series.impute.Imputer",
        "InceptionTimeClassifier": "sktime.classification.deep_learning.inceptiontime.InceptionTimeClassifier",
        "InceptionTimeNetwork": "sktime.networks.inceptiontime.InceptionTimeNetwork",
        "InceptionTimeRegressor": "sktime.regression.deep_learning.inceptiontime.InceptionTimeRegressor",
        "IndepDist": "sktime.dists_kernels.indep.IndepDist",
        "IndexSubset": "sktime.transformations.series.subset.IndexSubset",
        "IndividualBOSS": "sktime.classification.dictionary_based._boss.IndividualBOSS",
        "IndividualTDE": "sktime.classification.dictionary_based._tde.IndividualTDE",
        "InformationGainSegmentation": "sktime.detection.igts.InformationGainSegmentation",
        "InstanceSplitter": "sktime.split.instance.InstanceSplitter",
        "IntervalSegmenter": "sktime.transformations.panel.segment.IntervalSegmenter",
        "IntervalWidth": "sktime.performance_metrics.forecasting.probabilistic._classes.IntervalWidth",
        "InvertAugmenter": "sktime.transformations.series.augmenter.InvertAugmenter",
        "InvertTransform": "sktime.transformations.compose._invert.InvertTransform",
        "ItalyPowerDemand": "sktime.datasets.classification.italy_power_demand.ItalyPowerDemand",
        "IxToX": "sktime.transformations.compose._ixtox.IxToX",
        "JapaneseVowels": "sktime.datasets.classification.japanese_vowels.JapaneseVowels",
        "JarqueBera": "sktime.param_est.residuals._jarquebera.JarqueBera",
        "JohansenCointegration": "sktime.param_est.cointegration._johansen.JohansenCointegration",
        "KNeighborsTimeSeriesClassifier": "sktime.classification.distance_based._time_series_neighbors.KNeighborsTimeSeriesClassifier",
        "KNeighborsTimeSeriesClassifierPyts": "sktime.classification.distance_based._time_series_neighbors_pyts.KNeighborsTimeSeriesClassifierPyts",
        "KNeighborsTimeSeriesClassifierTslearn": "sktime.classification.distance_based._time_series_neighbors_tslearn.KNeighborsTimeSeriesClassifierTslearn",
        "KNeighborsTimeSeriesRegressor": "sktime.regression.distance_based._time_series_neighbors.KNeighborsTimeSeriesRegressor",
        "KalmanFilterTransformerFP": "sktime.transformations.series.kalman_filter._kalman_filter.KalmanFilterTransformerFP",
        "KalmanFilterTransformerPK": "sktime.transformations.series.kalman_filter._kalman_filter.KalmanFilterTransformerPK",
        "KalmanFilterTransformerSIMD": "sktime.transformations.series.kalman_filter._simdkalman.KalmanFilterTransformerSIMD",
        "KernelFromDist": "sktime.dists_kernels.dist_to_kern.KernelFromDist",
        "KinematicFeatures": "sktime.transformations.series.kinematic.KinematicFeatures",
        "LSTMFCNClassifier": "sktime.classification.deep_learning.lstmfcn.LSTMFCNClassifier",
        "LSTMFCNNetwork": "sktime.networks.lstmfcn.LSTMFCNNetwork",
        "LSTMFCNRegressor": "sktime.regression.deep_learning.lstmfcn.LSTMFCNRegressor",
        "LTSFDLinearForecaster": "sktime.forecasting.ltsf.LTSFDLinearForecaster",
        "LTSFLinearForecaster": "sktime.forecasting.ltsf.LTSFLinearForecaster",
        "LTSFNLinearForecaster": "sktime.forecasting.ltsf.LTSFNLinearForecaster",
        "LTSFTransformerForecaster": "sktime.forecasting.ltsf.LTSFTransformerForecaster",
        "Lag": "sktime.transformations.series.lag.Lag",
        "LcssTslearn": "sktime.dists_kernels.lcss.LcssTslearn",
        "LogLoss": "sktime.performance_metrics.forecasting.probabilistic._classes.LogLoss",
        "LogTransformer": "sktime.transformations.series.boxcox.LogTransformer",
        "Logger": "sktime.transformations.compose._logger.Logger",
        "Longley": "sktime.datasets.forecasting.longley.Longley",
        "LuckyDtwDist": "sktime.dists_kernels.lucky.LuckyDtwDist",
        "Lynx": "sktime.datasets.forecasting.lynx.Lynx",
        "M4CompetitionCatalogueDaily": "sktime.catalogues.forecasting.M4._daily.M4CompetitionCatalogueDaily",
        "M4CompetitionCatalogueHourly": "sktime.catalogues.forecasting.M4._hourly.M4CompetitionCatalogueHourly",
        "M4CompetitionCatalogueMonthly": "sktime.catalogues.forecasting.M4._monthly.M4CompetitionCatalogueMonthly",
        "M4CompetitionCatalogueQuarterly": "sktime.catalogues.forecasting.M4._quarterly.M4CompetitionCatalogueQuarterly",
        "M4CompetitionCatalogueWeekly": "sktime.catalogues.forecasting.M4._weekly.M4CompetitionCatalogueWeekly",
        "M4CompetitionCatalogueYearly": "sktime.catalogues.forecasting.M4._yearly.M4CompetitionCatalogueYearly",
        "M5Dataset": "sktime.datasets.forecasting.m5_competition.M5Dataset",
        "MACNNClassifier": "sktime.classification.deep_learning.macnn.MACNNClassifier",
        "MACNNNetwork": "sktime.networks.macnn.MACNNNetwork",
        "MACNNRegressor": "sktime.regression.deep_learning.macnn.MACNNRegressor",
        "MAPAForecaster": "sktime.forecasting.mapa.MAPAForecaster",
        "MCDCNNClassifier": "sktime.classification.deep_learning.mcdcnn._mcdcnn_tf.MCDCNNClassifier",
        "MCDCNNClassifierTorch": "sktime.classification.deep_learning.mcdcnn._mcdcnn_torch.MCDCNNClassifierTorch",
        "MCDCNNNetwork": "sktime.networks.mcdcnn._mcdcnn_tf.MCDCNNNetwork",
        "MCDCNNRegressor": "sktime.regression.deep_learning.mcdcnn._mcdcnn_tf.MCDCNNRegressor",
        "MCDCNNRegressorTorch": "sktime.regression.deep_learning.mcdcnn._mcdcnn_torch.MCDCNNRegressorTorch",
        "MLPClassifier": "sktime.classification.deep_learning.mlp._mlp_tf.MLPClassifier",
        "MLPClassifierTorch": "sktime.classification.deep_learning.mlp._mlp_torch.MLPClassifierTorch",
        "MLPNetwork": "sktime.networks.mlp._mlp_tf.MLPNetwork",
        "MLPRegressor": "sktime.regression.deep_learning.mlp.MLPRegressor",
        "MOIRAIForecaster": "sktime.forecasting.moirai_forecaster.MOIRAIForecaster",
        "MSTL": "sktime.transformations.series.detrend.mstl.MSTL",
        "MUSE": "sktime.classification.dictionary_based._muse.MUSE",
        "MVCAPA": "sktime.detection.skchange_aseg.mvcapa.MVCAPA",
        "MVTSTransformerClassifier": "sktime.classification.deep_learning.mvts_transformer.MVTSTransformerClassifier",
        "Macroeconomic": "sktime.datasets.forecasting.macroeconomic.Macroeconomic",
        "MatrixProfile": "sktime.transformations.panel.matrix_profile.MatrixProfile",
        "MatrixProfileClassifier": "sktime.classification.feature_based._matrix_profile_classifier.MatrixProfileClassifier",
        "MatrixProfileTransformer": "sktime.transformations.series.matrix_profile.MatrixProfileTransformer",
        "MeanAbsoluteError": "sktime.performance_metrics.forecasting._mae.MeanAbsoluteError",
        "MeanAbsolutePercentageError": "sktime.performance_metrics.forecasting._mape.MeanAbsolutePercentageError",
        "MeanAbsoluteScaledError": "sktime.performance_metrics.forecasting._mase.MeanAbsoluteScaledError",
        "MeanArctangentAbsolutePercentageError": "sktime.performance_metrics.forecasting._maape.MeanArctangentAbsolutePercentageError",
        "MeanAsymmetricError": "sktime.performance_metrics.forecasting._masyme.MeanAsymmetricError",
        "MeanLinexError": "sktime.performance_metrics.forecasting._mlinex.MeanLinexError",
        "MeanRelativeAbsoluteError": "sktime.performance_metrics.forecasting._mrelae.MeanRelativeAbsoluteError",
        "MeanSquaredError": "sktime.performance_metrics.forecasting._mse.MeanSquaredError",
        "MeanSquaredErrorPercentage": "sktime.performance_metrics.forecasting._msep.MeanSquaredErrorPercentage",
        "MeanSquaredLogError": "sktime.performance_metrics.forecasting._msle.MeanSquaredLogError",
        "MeanSquaredPercentageError": "sktime.performance_metrics.forecasting._mspe.MeanSquaredPercentageError",
        "MeanSquaredScaledError": "sktime.performance_metrics.forecasting._msse.MeanSquaredScaledError",
        "MedianAbsoluteError": "sktime.performance_metrics.forecasting._medae.MedianAbsoluteError",
        "MedianAbsolutePercentageError": "sktime.performance_metrics.forecasting._medape.MedianAbsolutePercentageError",
        "MedianAbsoluteScaledError": "sktime.performance_metrics.forecasting._medase.MedianAbsoluteScaledError",
        "MedianRelativeAbsoluteError": "sktime.performance_metrics.forecasting._medrelae.MedianRelativeAbsoluteError",
        "MedianSquaredError": "sktime.performance_metrics.forecasting._medse.MedianSquaredError",
        "MedianSquaredPercentageError": "sktime.performance_metrics.forecasting._medspe.MedianSquaredPercentageError",
        "MedianSquaredScaledError": "sktime.performance_metrics.forecasting._medsse.MedianSquaredScaledError",
        "Merger": "sktime.transformations.merger.Merger",
        "MiddleOutReconciler": "sktime.transformations.hierarchical.reconcile._middle_out.MiddleOutReconciler",
        "MiniRocket": "sktime.transformations.panel.rocket._minirocket.MiniRocket",
        "MiniRocketMultivariate": "sktime.transformations.panel.rocket._minirocket_multivariate.MiniRocketMultivariate",
        "MiniRocketMultivariateVariable": "sktime.transformations.panel.rocket._minirocket_multivariate_variable.MiniRocketMultivariateVariable",
        "MomentFMClassifier": "sktime.classification.foundation_models.momentfm.MomentFMClassifier",
        "MomentFMForecaster": "sktime.forecasting.hf_momentfm_forecaster.MomentFMForecaster",
        "MovingBlockBootstrapTransformer": "sktime.transformations.bootstrap._mbb.MovingBlockBootstrapTransformer",
        "MovingWindow": "sktime.detection.skchange_cp.moving_window.MovingWindow",
        "MrSEQL": "sktime.classification.shapelet_based._mrseql.MrSEQL",
        "MrSQM": "sktime.classification.shapelet_based._mrsqm.MrSQM",
        "MultiRocket": "sktime.transformations.panel.rocket._multirocket.MultiRocket",
        "MultiRocketMultivariate": "sktime.transformations.panel.rocket._multirocket_multivariate.MultiRocketMultivariate",
        "MultioutputTabularRegressionForecaster": "sktime.forecasting.compose._reduce.MultioutputTabularRegressionForecaster",
        "MultioutputTimeSeriesRegressionForecaster": "sktime.forecasting.compose._reduce.MultioutputTimeSeriesRegressionForecaster",
        "MultiplexClassifier": "sktime.classification.compose._multiplexer.MultiplexClassifier",
        "MultiplexForecaster": "sktime.forecasting.compose._multiplexer.MultiplexForecaster",
        "MultiplexRegressor": "sktime.regression.compose._multiplexer.MultiplexRegressor",
        "MultiplexTransformer": "sktime.transformations.compose._multiplex.MultiplexTransformer",
        "NaiveForecaster": "sktime.forecasting.naive._naive.NaiveForecaster",
        "NaiveVariance": "sktime.forecasting.naive._naive.NaiveVariance",
        "NeuralForecastDilatedRNN": "sktime.forecasting.neuralforecast.NeuralForecastDilatedRNN",
        "NeuralForecastGRU": "sktime.forecasting.neuralforecast.NeuralForecastGRU",
        "NeuralForecastLSTM": "sktime.forecasting.neuralforecast.NeuralForecastLSTM",
        "NeuralForecastRNN": "sktime.forecasting.neuralforecast.NeuralForecastRNN",
        "NeuralForecastTCN": "sktime.forecasting.neuralforecast.NeuralForecastTCN",
        "NonNegativeOptimalReconciler": "sktime.transformations.hierarchical.reconcile._optimal.NonNegativeOptimalReconciler",
        "OSULeaf": "sktime.datasets.classification.osuleaf.OSULeaf",
        "OnlineEnsembleForecaster": "sktime.forecasting.online_learning._online_ensemble.OnlineEnsembleForecaster",
        "OptimalReconciler": "sktime.transformations.hierarchical.reconcile._optimal.OptimalReconciler",
        "OptionalPassthrough": "sktime.transformations.compose._optional.OptionalPassthrough",
        "OverallWeightedAverage": "sktime.performance_metrics.forecasting._owa.OverallWeightedAverage",
        "PAA": "sktime.transformations.series.paa.PAA",
        "PAAlegacy": "sktime.transformations.panel.dictionary_based._paa.PAAlegacy",
        "PBS": "sktime.datasets.forecasting.pbs.PBS",
        "PCATransformer": "sktime.transformations.panel.pca.PCATransformer",
        "PELT": "sktime.detection.skchange_cp.pelt.PELT",
        "PLAID": "sktime.datasets.classification.plaid.PLAID",
        "PaddingTransformer": "sktime.transformations.panel.padder.PaddingTransformer",
        "PandasTransformAdaptor": "sktime.transformations.series.adapt.PandasTransformAdaptor",
        "ParamFitterPipeline": "sktime.param_est.compose._pipeline.ParamFitterPipeline",
        "PartialAutoCorrelationTransformer": "sktime.transformations.series.acf.PartialAutoCorrelationTransformer",
        "PatchTSTForecaster": "sktime.forecasting.patch_tst.PatchTSTForecaster",
        "PeakTimeFeature": "sktime.transformations.series.peak.PeakTimeFeature",
        "Permute": "sktime.forecasting.compose._pipeline.Permute",
        "PinballLoss": "sktime.performance_metrics.forecasting.probabilistic._classes.PinballLoss",
        "SktimePipeline": "sktime.pipeline.pipeline.Pipeline",
        "PlateauFinder": "sktime.transformations.panel.summarize._extract.PlateauFinder",
        "PluginParamsForecaster": "sktime.param_est.plugin._forecaster.PluginParamsForecaster",
        "PluginParamsTransformer": "sktime.param_est.plugin._transformer.PluginParamsTransformer",
        "PoissonHMM": "sktime.detection.hmm_learn.poisson.PoissonHMM",
        "PolynomialTrendForecaster": "sktime.forecasting.trend._polynomial_trend_forecaster.PolynomialTrendForecaster",
        "ProbabilityThresholdEarlyClassifier": "sktime.classification.early_classification._probability_threshold.ProbabilityThresholdEarlyClassifier",
        "Prophet": "sktime.forecasting.fbprophet.Prophet",
        "ProphetPiecewiseLinearTrendForecaster": "sktime.forecasting.trend._pwl_trend_forecaster.ProphetPiecewiseLinearTrendForecaster",
        "Prophetverse": "sktime.forecasting.prophetverse.Prophetverse",
        "ProximityForest": "sktime.classification.distance_based._proximity_forest.ProximityForest",
        "ProximityStump": "sktime.classification.distance_based._proximity_forest.ProximityStump",
        "ProximityTree": "sktime.classification.distance_based._proximity_forest.ProximityTree",
        "PwTrafoPanelPipeline": "sktime.dists_kernels.compose.PwTrafoPanelPipeline",
        "PyKANForecaster": "sktime.forecasting.pykan_forecaster.PyKANForecaster",
        "PyODDetector": "sktime.detection.adapters._pyod.PyODDetector",
        "PytorchForecastingDeepAR": "sktime.forecasting.pytorchforecasting.PytorchForecastingDeepAR",
        "PytorchForecastingNBeats": "sktime.forecasting.pytorchforecasting.PytorchForecastingNBeats",
        "PytorchForecastingNHiTS": "sktime.forecasting.pytorchforecasting.PytorchForecastingNHiTS",
        "PytorchForecastingTFT": "sktime.forecasting.pytorchforecasting.PytorchForecastingTFT",
        "RBFForecaster": "sktime.forecasting.rbf_forecaster.RBFForecaster",
        "RBFTransformer": "sktime.transformations.series.basisfunction.RBFTransformer",
        "RNNNetwork": "sktime.networks.rnn._rnn_tf.RNNNetwork",
        "RandIndex": "sktime.performance_metrics.detection._randindex.RandIndex",
        "RandomIntervalClassifier": "sktime.classification.feature_based._random_interval_classifier.RandomIntervalClassifier",
        "RandomIntervalFeatureExtractor": "sktime.transformations.panel.summarize._extract.RandomIntervalFeatureExtractor",
        "RandomIntervalSegmenter": "sktime.transformations.panel.segment.RandomIntervalSegmenter",
        "RandomIntervalSpectralEnsemble": "sktime.classification.interval_based._rise.RandomIntervalSpectralEnsemble",
        "RandomIntervals": "sktime.transformations.panel.random_intervals.RandomIntervals",
        "RandomSamplesAugmenter": "sktime.transformations.series.augmenter.RandomSamplesAugmenter",
        "RandomShapeletTransform": "sktime.transformations.panel.shapelet_transform._shapelet_transform.RandomShapeletTransform",
        "Reconciler": "sktime.transformations.hierarchical.reconcile._reconcile.Reconciler",
        "ReconcilerForecaster": "sktime.forecasting.reconcile.ReconcilerForecaster",
        "RecursiveReductionForecaster": "sktime.forecasting.compose._reduce.RecursiveReductionForecaster",
        "RecursiveTabularRegressionForecaster": "sktime.forecasting.compose._reduce.RecursiveTabularRegressionForecaster",
        "RecursiveTimeSeriesRegressionForecaster": "sktime.forecasting.compose._reduce.RecursiveTimeSeriesRegressionForecaster",
        "ReducerTransform": "sktime.transformations.series.lag.ReducerTransform",
        "RegressorPipeline": "sktime.regression.compose._pipeline.RegressorPipeline",
        "RelativeLoss": "sktime.performance_metrics.forecasting._rell.RelativeLoss",
        "Repeat": "sktime.split.compose._repeat.Repeat",
        "RepeatBootstrapTransformer": "sktime.transformations.bootstrap._repeat.RepeatBootstrapTransformer",
        "ResNetClassifier": "sktime.classification.deep_learning.resnet.ResNetClassifier",
        "ResNetNetwork": "sktime.networks.resnet.ResNetNetwork",
        "ResNetRegressor": "sktime.regression.deep_learning.resnet.ResNetRegressor",
        "ResidualBoostingForecaster": "sktime.forecasting.residual_booster.ResidualBoostingForecaster",
        "ReverseAugmenter": "sktime.transformations.series.augmenter.ReverseAugmenter",
        "Rocket": "sktime.transformations.panel.rocket._rocket.Rocket",
        "RocketClassifier": "sktime.classification.kernel_based._rocket_classifier.RocketClassifier",
        "RocketPyts": "sktime.transformations.panel.rocket._rocket_pyts.RocketPyts",
        "RocketRegressor": "sktime.regression.kernel_based._rocket_regressor.RocketRegressor",
        "SARIMAX": "sktime.forecasting.sarimax.SARIMAX",
        "SAX": "sktime.transformations.series.sax.SAX",
        "SAXlegacy": "sktime.transformations.panel.dictionary_based._sax.SAXlegacy",
        "SCINetForecaster": "sktime.forecasting.scinet.SCINetForecaster",
        "SFA": "sktime.transformations.panel.dictionary_based._sfa.SFA",
        "SFAFast": "sktime.transformations.panel.dictionary_based._sfa_fast.SFAFast",
        "STDBSCAN": "sktime.clustering.spatio_temporal._st_dbscan.STDBSCAN",
        "STLBootstrapTransformer": "sktime.transformations.bootstrap._mbb.STLBootstrapTransformer",
        "STLForecaster": "sktime.forecasting.trend._stl_forecaster.STLForecaster",
        "STLTransformer": "sktime.transformations.series.detrend._deseasonalize.STLTransformer",
        "STRAY": "sktime.detection.stray.STRAY",
        "SameLocSplitter": "sktime.split.sameloc.SameLocSplitter",
        "ScaledAsinhTransformer": "sktime.transformations.series.scaledasinh.ScaledAsinhTransformer",
        "ScaledLogitTransformer": "sktime.transformations.series.scaledlogit.ScaledLogitTransformer",
        "ScipyDist": "sktime.dists_kernels.scipy_dist.ScipyDist",
        "SeasonalDummiesOneHot": "sktime.transformations.series.dummies.SeasonalDummiesOneHot",
        "SeasonalityACF": "sktime.param_est.seasonality.SeasonalityACF",
        "SeasonalityACFqstat": "sktime.param_est.seasonality.SeasonalityACFqstat",
        "SeasonalityPeriodogram": "sktime.param_est.seasonality.SeasonalityPeriodogram",
        "SeededBinarySegmentation": "sktime.detection.skchange_cp.seeded_binseg.SeededBinarySegmentation",
        "ShampooSales": "sktime.datasets.forecasting.shampoo_sales.ShampooSales",
        "ShapeDTW": "sktime.classification.distance_based._shape_dtw.ShapeDTW",
        "ShapeletLearningClassifierPyts": "sktime.classification.shapelet_based._learning_pyts.ShapeletLearningClassifierPyts",
        "ShapeletLearningClassifierTslearn": "sktime.classification.shapelet_based._learning_tslearn.ShapeletLearningClassifierTslearn",
        "ShapeletTransform": "sktime.transformations.panel.shapelet_transform._shapelet_transform.ShapeletTransform",
        "ShapeletTransformClassifier": "sktime.classification.shapelet_based._stc.ShapeletTransformClassifier",
        "ShapeletTransformPyts": "sktime.transformations.panel.shapelet_transform._shapelet_transform_pyts.ShapeletTransformPyts",
        "SignatureClassifier": "sktime.classification.feature_based._signature_classifier.SignatureClassifier",
        "SignatureKernel": "sktime.dists_kernels.signature_kernel.SignatureKernel",
        "SignatureMoments": "sktime.transformations.series.signature.SignatureMoments",
        "SignatureTransformer": "sktime.transformations.panel.signature_based._signature_method.SignatureTransformer",
        "SimpleRNNClassifier": "sktime.classification.deep_learning.rnn._rnn_tf.SimpleRNNClassifier",
        "SimpleRNNClassifierTorch": "sktime.classification.deep_learning.rnn._rnn_torch.SimpleRNNClassifierTorch",
        "SimpleRNNRegressor": "sktime.regression.deep_learning.rnn._rnn_tf.SimpleRNNRegressor",
        "SimpleRNNRegressorTorch": "sktime.regression.deep_learning.rnn._rnn_torch.SimpleRNNRegressorTorch",
        "SingleWindowSplitter": "sktime.split.singlewindow.SingleWindowSplitter",
        "SkforecastAutoreg": "sktime.forecasting.compose._skforecast_reduce.SkforecastAutoreg",
        "SkforecastRecursive": "sktime.forecasting.compose._skforecast_reduce.SkforecastRecursive",
        "SklearnClassifierPipeline": "sktime.classification.compose._pipeline.SklearnClassifierPipeline",
        "SklearnClustererPipeline": "sktime.clustering.compose._pipeline.SklearnClustererPipeline",
        "SklearnRegressorPipeline": "sktime.regression.compose._pipeline.SklearnRegressorPipeline",
        "SlidingGreedySplitter": "sktime.split.slidinggreedy.SlidingGreedySplitter",
        "SlidingWindowSegmenter": "sktime.transformations.panel.segment.SlidingWindowSegmenter",
        "SlidingWindowSplitter": "sktime.split.slidingwindow.SlidingWindowSplitter",
        "SlopeTransformer": "sktime.transformations.panel.slope.SlopeTransformer",
        "SoftDtwDistTslearn": "sktime.dists_kernels.dtw._dtw_tslearn.SoftDtwDistTslearn",
        "Solar": "sktime.datasets.forecasting.solar.Solar",
        "SplineTrendForecaster": "sktime.forecasting.trend._spline_trend_forecaster.SplineTrendForecaster",
        "SplitterBootstrapTransformer": "sktime.transformations.bootstrap._splitterboot.SplitterBootstrapTransformer",
        "SplitterSummarizer": "sktime.transformations.series.summarize.SplitterSummarizer",
        "SqrtTransformer": "sktime.transformations.series.exponent.SqrtTransformer",
        "SquaredDistrLoss": "sktime.performance_metrics.forecasting.probabilistic._classes.SquaredDistrLoss",
        "SquaringResiduals": "sktime.forecasting.squaring_residuals.SquaringResiduals",
        "SqueezeHierarchy": "sktime.transformations.hierarchical.squeeze_hierarchy.SqueezeHierarchy",
        "StackingForecaster": "sktime.forecasting.compose._stack.StackingForecaster",
        "StatThresholdAnomaliser": "sktime.detection.skchange_aseg.statthreshold.StatThresholdAnomaliser",
        "StationarityADF": "sktime.param_est.stationarity._statsmodels.StationarityADF",
        "StationarityADFArch": "sktime.param_est.stationarity._arch.StationarityADFArch",
        "StationarityDFGLS": "sktime.param_est.stationarity._arch.StationarityDFGLS",
        "StationarityKPSS": "sktime.param_est.stationarity._statsmodels.StationarityKPSS",
        "StationarityKPSSArch": "sktime.param_est.stationarity._arch.StationarityKPSSArch",
        "StationarityPhillipsPerron": "sktime.param_est.stationarity._arch.StationarityPhillipsPerron",
        "StationarityVarianceRatio": "sktime.param_est.stationarity._arch.StationarityVarianceRatio",
        "StationarityZivotAndrews": "sktime.param_est.stationarity._arch.StationarityZivotAndrews",
        "StatsForecastADIDA": "sktime.forecasting.statsforecast.StatsForecastADIDA",
        "StatsForecastARCH": "sktime.forecasting.arch._statsforecast_arch.StatsForecastARCH",
        "StatsForecastAutoARIMA": "sktime.forecasting.statsforecast.StatsForecastAutoARIMA",
        "StatsForecastAutoCES": "sktime.forecasting.statsforecast.StatsForecastAutoCES",
        "StatsForecastAutoETS": "sktime.forecasting.statsforecast.StatsForecastAutoETS",
        "StatsForecastAutoTBATS": "sktime.forecasting.statsforecast.StatsForecastAutoTBATS",
        "StatsForecastAutoTheta": "sktime.forecasting.statsforecast.StatsForecastAutoTheta",
        "StatsForecastGARCH": "sktime.forecasting.arch._statsforecast_arch.StatsForecastGARCH",
        "StatsForecastMSTL": "sktime.forecasting.statsforecast.StatsForecastMSTL",
        "StatsModelsARIMA": "sktime.forecasting.arima._statsmodels.StatsModelsARIMA",
        "SubLOF": "sktime.detection.lof.SubLOF",
        "SubsequenceExtractionTransformer": "sktime.transformations.series.subsequence_extraction.SubsequenceExtractionTransformer",
        "SummaryClassifier": "sktime.classification.feature_based._summary_classifier.SummaryClassifier",
        "SummaryTransformer": "sktime.transformations.series.summarize.SummaryTransformer",
        "SupervisedIntervals": "sktime.transformations.panel.supervised_intervals.SupervisedIntervals",
        "SupervisedTimeSeriesForest": "sktime.classification.interval_based._stsf.SupervisedTimeSeriesForest",
        "TBATS": "sktime.forecasting.tbats.TBATS",
        "TEASER": "sktime.classification.early_classification._teaser.TEASER",
        "TSB": "sktime.forecasting.tsb.TSB",
        "TSBootstrapAdapter": "sktime.transformations.bootstrap._tsbootstrap.TSBootstrapAdapter",
        "TSCGridSearchCV": "sktime.classification.model_selection._tune.TSCGridSearchCV",
        "TSCOptCV": "hyperactive.integrations.sktime._classification.TSCOptCV",
        "TSFELTransformer": "sktime.transformations.series.tsfel._tsfel.TSFELTransformer",
        "TSFeaturesTransformer": "sktime.transformations.panel.tsfeatures.TSFeaturesTransformer",
        "TSFreshClassifier": "sktime.classification.feature_based._tsfresh_classifier.TSFreshClassifier",
        "TSFreshFeatureExtractor": "sktime.transformations.panel.tsfresh.TSFreshFeatureExtractor",
        "TSFreshRelevantFeatureExtractor": "sktime.transformations.panel.tsfresh.TSFreshRelevantFeatureExtractor",
        "TSInterpolator": "sktime.transformations.panel.interpolate.TSInterpolator",
        "TSRGridSearchCV": "sktime.regression.model_selection._tune.TSRGridSearchCV",
        "TabularToSeriesAdaptor": "sktime.transformations.series.adapt.TabularToSeriesAdaptor",
        "Tabularizer": "sktime.transformations.panel.reduce.Tabularizer",
        "TapNetClassifier": "sktime.classification.deep_learning.tapnet.TapNetClassifier",
        "TapNetNetwork": "sktime.networks.tapnet.TapNetNetwork",
        "TapNetRegressor": "sktime.regression.deep_learning.tapnet.TapNetRegressor",
        "Tecator": "sktime.datasets.regression.tecator.Tecator",
        "TemporalDictionaryEnsemble": "sktime.classification.dictionary_based._tde.TemporalDictionaryEnsemble",
        "TemporalTrainTestSplitter": "sktime.split.temporal_train_test_split.TemporalTrainTestSplitter",
        "TemporianTransformer": "sktime.transformations.series.temporian.TemporianTransformer",
        "TestPlusTrainSplitter": "sktime.split.testplustrain.TestPlusTrainSplitter",
        "ThetaForecaster": "sktime.forecasting.theta.ThetaForecaster",
        "ThetaLinesTransformer": "sktime.transformations.series.theta.ThetaLinesTransformer",
        "ThetaModularForecaster": "sktime.forecasting.theta.ThetaModularForecaster",
        "ThresholdDetector": "sktime.detection.naive._threshold.ThresholdDetector",
        "TiRexForecaster": "sktime.forecasting.tirex.TiRexForecaster",
        "TimeBinAggregate": "sktime.transformations.series.binning.TimeBinAggregate",
        "TimeBinner": "sktime.transformations.panel.reduce.TimeBinner",
        "TimeLLMForecaster": "sktime.forecasting.time_llm.TimeLLMForecaster",
        "TimeMoEForecaster": "sktime.forecasting.timemoe.TimeMoEForecaster",
        "TimeSeriesAUPRC": "sktime.performance_metrics.detection._ts_auprc.TimeSeriesAUPRC",
        "TimeSeriesDBSCAN": "sktime.clustering.dbscan.TimeSeriesDBSCAN",
        "TimeSeriesForestClassifier": "sktime.classification.interval_based._tsf.TimeSeriesForestClassifier",
        "TimeSeriesForestRegressor": "sktime.regression.interval_based._tsf.TimeSeriesForestRegressor",
        "TimeSeriesKMeans": "sktime.clustering.k_means._k_means.TimeSeriesKMeans",
        "TimeSeriesKMeansTslearn": "sktime.clustering.k_means._k_means_tslearn.TimeSeriesKMeansTslearn",
        "TimeSeriesKMedoids": "sktime.clustering.k_medoids.TimeSeriesKMedoids",
        "TimeSeriesKShapes": "sktime.clustering.k_shapes.TimeSeriesKShapes",
        "TimeSeriesKernelKMeans": "sktime.clustering.kernel_k_means.TimeSeriesKernelKMeans",
        "TimeSeriesKvisibility": "sktime.clustering.kvisibility.TimeSeriesKvisibility",
        "TimeSeriesSVC": "sktime.classification.kernel_based._svc.TimeSeriesSVC",
        "TimeSeriesSVCTslearn": "sktime.classification.kernel_based._svc_tslearn.TimeSeriesSVCTslearn",
        "TimeSeriesSVRTslearn": "sktime.regression.kernel_based._svr_tslearn.TimeSeriesSVRTslearn",
        "TimeSince": "sktime.transformations.series.time_since.TimeSince",
        "TimesFMForecaster": "sktime.forecasting.timesfm_forecaster.TimesFMForecaster",
        "TinyTimeMixerForecaster": "sktime.forecasting.ttm.TinyTimeMixerForecaster",
        "TopdownReconciler": "sktime.transformations.hierarchical.reconcile._topdown.TopdownReconciler",
        "TotoForecaster": "sktime.forecasting.toto.TotoForecaster",
        "TransformByLevel": "sktime.transformations.compose._grouped.TransformByLevel",
        "TransformIf": "sktime.transformations.compose._transformif.TransformIf",
        "TransformSelectForecaster": "sktime.forecasting.compose._transform_select_forecaster.TransformSelectForecaster",
        "TransformedTargetForecaster": "sktime.forecasting.compose._pipeline.TransformedTargetForecaster",
        "TransformerPipeline": "sktime.transformations.compose._pipeline.TransformerPipeline",
        "TrendForecaster": "sktime.forecasting.trend._trend_forecaster.TrendForecaster",
        "TruncationTransformer": "sktime.transformations.panel.truncation.TruncationTransformer",
        "UCRUEADataset": "sktime.datasets.classification.ucr_uea_archive._ucr_uea_datasets.UCRUEADataset",
        "USChange": "sktime.datasets.forecasting.uschange.USChange",
        "UnobservedComponents": "sktime.forecasting.structural.UnobservedComponents",
        "UpdateEvery": "sktime.forecasting.stream._update.UpdateEvery",
        "UpdateRefitsEvery": "sktime.forecasting.stream._update.UpdateRefitsEvery",
        "VAR": "sktime.forecasting.var.VAR",
        "VARMAX": "sktime.forecasting.varmax.VARMAX",
        "VARReduce": "sktime.forecasting.var_reduce.VARReduce",
        "VECM": "sktime.forecasting.vecm.VECM",
        "VmdTransformer": "sktime.transformations.series.vmd.VmdTransformer",
        "WEASEL": "sktime.classification.dictionary_based._weasel.WEASEL",
        "WeightedEnsembleClassifier": "sktime.classification.ensemble._weighted.WeightedEnsembleClassifier",
        "WhiteNoiseAugmenter": "sktime.transformations.series.augmenter.WhiteNoiseAugmenter",
        "WindowSegmenter": "sktime.detection.wclust.WindowSegmenter",
        "WindowSummarizer": "sktime.transformations.series.summarize.WindowSummarizer",
        "WindowedF1Score": "sktime.performance_metrics.detection._f1score.WindowedF1Score",
        "YfromX": "sktime.forecasting.compose._reduce.YfromX",
        "YtoX": "sktime.transformations.compose._ytox.YtoX",
        "ZeroAnomalies": "sktime.detection.dummy._zero_an.ZeroAnomalies",
        "ZeroChangePoints": "sktime.detection.dummy._zero_cp.ZeroChangePoints",
        "ZeroSegments": "sktime.detection.dummy._zero_seg.ZeroSegments",
    }

    _type_of_objs = {
        "ACSF1": "dataset_classification",
        "ADICVTransformer": "transformer",
        "ARARForecaster": "forecaster",
        "ARCH": "forecaster",
        "ARDL": "forecaster",
        "ARIMA": "forecaster",
        "ARLagOrderSelector": "param_est",
        "AUCalibration": "metric_forecasting_proba",
        "AcorrLjungbox": "param_est",
        "AggrDist": "transformer-pairwise-panel",
        "Aggregator": "transformer",
        "Airline": "dataset_forecasting",
        "AlignerDTW": "aligner",
        "AlignerDTWfromDist": "aligner",
        "AlignerDtwDtai": "aligner",
        "AlignerDtwNumba": "aligner",
        "AlignerEditNumba": "aligner",
        "AlignerLuckyDtw": "aligner",
        "AlignerNaive": "aligner",
        "ArrowHead": "dataset_classification",
        "Arsenal": "classifier",
        "AutoARIMA": "forecaster",
        "AutoCorrelationTransformer": "transformer",
        "AutoETS": "forecaster",
        "AutoEnsembleForecaster": "forecaster",
        "AutoREG": "forecaster",
        "AutoTS": "forecaster",
        "BATS": "forecaster",
        "BKFilter": "transformer",
        "BOSSEnsemble": "classifier",
        "BOSSVSClassifierPyts": "classifier",
        "BaggingClassifier": "classifier",
        "BaggingForecaster": "forecaster",
        "BasicMotions": "dataset_classification",
        "BinarySegmentation": "detector",
        "Bollinger": "transformer",
        "BottomUpReconciler": "reconciler",
        "BoxCoxBiasAdjustedForecaster": "forecaster",
        "BoxCoxTransformer": "transformer",
        "BreakvarHeteroskedasticityTest": "param_est",
        "CAPA": "detector",
        "CFFilter": "transformer",
        "CINNForecaster": "forecaster",
        "CNNClassifier": "classifier",
        "CNNNetwork": "network",
        "CNNRegressor": "regressor",
        "CNTCClassifier": "classifier",
        "CNTCNetwork": "network",
        "CNTCRegressor": "regressor",
        "CRPS": "metric_forecasting_proba",
        "CanonicalIntervalForest": "classifier",
        "Catch22": "transformer",
        "Catch22Classifier": "classifier",
        "Catch22Wrapper": "transformer",
        "ChronosForecaster": "forecaster",
        "CircularBinarySegmentation": "detector",
        "ClaSPSegmentation": "detector",
        "ClaSPTransformer": "transformer",
        "ClassifierPipeline": "classifier",
        "ClearSky": "transformer",
        "ClusterSegmenter": "detector",
        "ClustererAsTransformer": "transformer",
        "ClustererPipeline": "clusterer",
        "ColumnConcatenator": "transformer",
        "ColumnEnsembleClassifier": "classifier",
        "ColumnEnsembleForecaster": "forecaster",
        "ColumnEnsembleTransformer": "transformer",
        "ColumnSelect": "transformer",
        "ColumnTransformer": "transformer",
        "ColumnwiseTransformer": "transformer",
        "CombineTransformers": "transformer",
        "CombinedDistance": "transformer-pairwise-panel",
        "ComposableTimeSeriesForestClassifier": "classifier",
        "ComposableTimeSeriesForestRegressor": "regressor",
        "ConditionalDeseasonalizer": "transformer",
        "ConformalIntervals": "forecaster",
        "ConstantPwTrafoPanel": "transformer-pairwise-panel",
        "ConstraintViolation": "metric_forecasting_proba",
        "ContractableBOSS": "classifier",
        "ConvTimeNetClassifier": "classifier",
        "ConvTimeNetForecaster": "forecaster",
        "CosineTransformer": "transformer",
        "CountryHolidaysTransformer": "transformer",
        "Croston": "forecaster",
        "CtwDistTslearn": "transformer-pairwise-panel",
        "CurveFitForecaster": "forecaster",
        "CutoffFhSplitter": "splitter",
        "CutoffSplitter": "splitter",
        "DOBIN": "transformer",
        "DWTTransformer": "transformer",
        "DartsLinearRegressionModel": "forecaster",
        "DartsRegressionModel": "forecaster",
        "DartsXGBModel": "forecaster",
        "DateTimeFeatures": "transformer",
        "DegreeDayFeatures": "transformer",
        "DerivativeSlopeTransformer": "transformer",
        "Deseasonalizer": "transformer",
        "DetectionCount": "metric_detection",
        "DetectorAsTransformer": "transformer",
        "DetectorPipeline": "detector",
        "Detrender": "transformer",
        "Differencer": "transformer",
        "DilationMappingTransformer": "transformer",
        "DirRecTabularRegressionForecaster": "forecaster",
        "DirRecTimeSeriesRegressionForecaster": "forecaster",
        "DirectReductionForecaster": "forecaster",
        "DirectTabularRegressionForecaster": "forecaster",
        "DirectTimeSeriesRegressionForecaster": "forecaster",
        "DirectedChamfer": "metric_detection",
        "DirectedHausdorff": "metric_detection",
        "DistFromAligner": "transformer-pairwise-panel",
        "DistFromKernel": "transformer-pairwise-panel",
        "DistanceFeatures": "transformer",
        "DontUpdate": "forecaster",
        "DoubleMLForecaster": "forecaster",
        "DrCIF": "classifier",
        "DropNA": "transformer",
        "DtwDist": "transformer-pairwise-panel",
        "DtwDistTslearn": "transformer-pairwise-panel",
        "DtwDtaidistMultiv": "transformer-pairwise-panel",
        "DtwDtaidistUniv": "transformer-pairwise-panel",
        "DtwPythonDist": "transformer-pairwise-panel",
        "DummyClassificationCatalogue": "catalogue",
        "DummyClassifier": "classifier",
        "DummyForecastingCatalogue": "catalogue",
        "DummyGlobalForecaster": "forecaster",
        "DummyRegressor": "regressor",
        "DummyRegularAnomalies": "detector",
        "DummyRegularChangePoints": "detector",
        "DynamicFactor": "forecaster",
        "EAgglo": "transformer",
        "ESRNNForecaster": "forecaster",
        "EditDist": "transformer-pairwise-panel",
        "ElasticEnsemble": "classifier",
        "ElbowClassPairwise": "transformer",
        "ElbowClassSum": "transformer",
        "EmpiricalCoverage": "metric_forecasting_proba",
        "EnbPIForecaster": "forecaster",
        "EnsembleForecaster": "forecaster",
        "ExpandingCutoffSplitter": "splitter",
        "ExpandingGreedySplitter": "splitter",
        "ExpandingSlidingWindowSplitter": "splitter",
        "ExpandingWindowSplitter": "splitter",
        "ExponentTransformer": "transformer",
        "ExponentialSmoothing": "forecaster",
        "FABBA": "transformer",
        "FCNClassifier": "classifier",
        "FCNNetwork": "network",
        "FCNRegressor": "regressor",
        "FallbackForecaster": "forecaster",
        "FeatureSelection": "transformer",
        "FeatureUnion": "transformer",
        "FhPlexForecaster": "forecaster",
        "Filter": "transformer",
        "FinancialHolidaysTransformer": "transformer",
        "FitInTransform": "transformer",
        "FittedParamExtractor": "transformer",
        "FixedParams": "param_est",
        "FlatDist": "transformer-pairwise-panel",
        "ForecastByLevel": "forecaster",
        "ForecastKnownValues": "forecaster",
        "ForecastX": "forecaster",
        "ForecastingData": "dataset_forecasting",
        "ForecastingGridSearchCV": "forecaster",
        "ForecastingHorizonSplitter": "splitter",
        "ForecastingOptCV": "forecaster",
        "ForecastingOptunaSearchCV": "forecaster",
        "ForecastingPipeline": "forecaster",
        "ForecastingRandomizedSearchCV": "forecaster",
        "ForecastingSkoptSearchCV": "forecaster",
        "FourierFeatures": "transformer",
        "FourierTransform": "transformer",
        "FreshPRINCE": "classifier",
        "FunctionParamFitter": "param_est",
        "FunctionTransformer": "transformer",
        "GAKernel": "transformer-pairwise-panel",
        "GMMHMM": "detector",
        "GRUClassifier": "classifier",
        "GRUFCNNClassifier": "classifier",
        "GaussianHMM": "detector",
        "GeometricMeanAbsoluteError": "metric_forecasting",
        "GeometricMeanRelativeAbsoluteError": "metric_forecasting",
        "GeometricMeanRelativeSquaredError": "metric_forecasting",
        "GeometricMeanSquaredError": "metric_forecasting",
        "GreedyGaussianSegmentation": "detector",
        "GreykiteForecaster": "forecaster",
        "GroupbyCategoryForecaster": "forecaster",
        "GunPoint": "dataset_classification",
        "HCrystalBallAdapter": "forecaster",
        "HFTransformersForecaster": "forecaster",
        "HIVECOTEV1": "classifier",
        "HIVECOTEV2": "classifier",
        "HMM": "detector",
        "HOG1DTransformer": "transformer",
        "HPFilter": "transformer",
        "HampelFilter": "transformer",
        "Hidalgo": "transformer",
        "HierarchicalProphet": "forecaster",
        "HierarchicalSalesToydata": "dataset_forecasting",
        "HierarchyEnsembleForecaster": "forecaster",
        "HolidayFeatures": "transformer",
        "HurstExponentTransformer": "transformer",
        "Id": "transformer",
        "IgnoreX": "forecaster",
        "Imputer": "transformer",
        "InceptionTimeClassifier": "classifier",
        "InceptionTimeNetwork": "network",
        "InceptionTimeRegressor": "regressor",
        "IndepDist": "transformer-pairwise-panel",
        "IndexSubset": "transformer",
        "IndividualBOSS": "classifier",
        "IndividualTDE": "classifier",
        "InformationGainSegmentation": "estimator",
        "InstanceSplitter": "splitter",
        "IntervalSegmenter": "transformer",
        "IntervalWidth": "metric_forecasting_proba",
        "InvertAugmenter": "transformer",
        "InvertTransform": "transformer",
        "ItalyPowerDemand": "dataset_classification",
        "IxToX": "transformer",
        "JapaneseVowels": "dataset_classification",
        "JarqueBera": "param_est",
        "JohansenCointegration": "param_est",
        "KNeighborsTimeSeriesClassifier": "classifier",
        "KNeighborsTimeSeriesClassifierPyts": "classifier",
        "KNeighborsTimeSeriesClassifierTslearn": "classifier",
        "KNeighborsTimeSeriesRegressor": "regressor",
        "KalmanFilterTransformerFP": "transformer",
        "KalmanFilterTransformerPK": "transformer",
        "KalmanFilterTransformerSIMD": "transformer",
        "KernelFromDist": "transformer-pairwise-panel",
        "KinematicFeatures": "transformer",
        "LSTMFCNClassifier": "classifier",
        "LSTMFCNNetwork": "network",
        "LSTMFCNRegressor": "regressor",
        "LTSFDLinearForecaster": "forecaster",
        "LTSFLinearForecaster": "forecaster",
        "LTSFNLinearForecaster": "forecaster",
        "LTSFTransformerForecaster": "forecaster",
        "Lag": "transformer",
        "LcssTslearn": "transformer-pairwise-panel",
        "LogLoss": "metric_forecasting_proba",
        "LogTransformer": "transformer",
        "Logger": "transformer",
        "Longley": "dataset_forecasting",
        "LuckyDtwDist": "transformer-pairwise-panel",
        "Lynx": "dataset_forecasting",
        "M4CompetitionCatalogueDaily": "catalogue",
        "M4CompetitionCatalogueHourly": "catalogue",
        "M4CompetitionCatalogueMonthly": "catalogue",
        "M4CompetitionCatalogueQuarterly": "catalogue",
        "M4CompetitionCatalogueWeekly": "catalogue",
        "M4CompetitionCatalogueYearly": "catalogue",
        "M5Dataset": "dataset_forecasting",
        "MACNNClassifier": "classifier",
        "MACNNNetwork": "network",
        "MACNNRegressor": "regressor",
        "MAPAForecaster": "forecaster",
        "MCDCNNClassifier": "classifier",
        "MCDCNNClassifierTorch": "classifier",
        "MCDCNNNetwork": "network",
        "MCDCNNRegressor": "regressor",
        "MCDCNNRegressorTorch": "regressor",
        "MLPClassifier": "classifier",
        "MLPClassifierTorch": "classifier",
        "MLPNetwork": "network",
        "MLPRegressor": "regressor",
        "MOIRAIForecaster": "global_forecaster",
        "MSTL": "transformer",
        "MUSE": "classifier",
        "MVCAPA": "detector",
        "MVTSTransformerClassifier": "classifier",
        "Macroeconomic": "dataset_forecasting",
        "MatrixProfile": "transformer",
        "MatrixProfileClassifier": "classifier",
        "MatrixProfileTransformer": "transformer",
        "MeanAbsoluteError": "metric_forecasting",
        "MeanAbsolutePercentageError": "metric_forecasting",
        "MeanAbsoluteScaledError": "metric_forecasting",
        "MeanArctangentAbsolutePercentageError": "metric_forecasting",
        "MeanAsymmetricError": "metric_forecasting",
        "MeanLinexError": "metric_forecasting",
        "MeanRelativeAbsoluteError": "metric_forecasting",
        "MeanSquaredError": "metric_forecasting",
        "MeanSquaredErrorPercentage": "metric_forecasting",
        "MeanSquaredLogError": "metric_forecasting",
        "MeanSquaredPercentageError": "metric_forecasting",
        "MeanSquaredScaledError": "metric_forecasting",
        "MedianAbsoluteError": "metric_forecasting",
        "MedianAbsolutePercentageError": "metric_forecasting",
        "MedianAbsoluteScaledError": "metric_forecasting",
        "MedianRelativeAbsoluteError": "metric_forecasting",
        "MedianSquaredError": "metric_forecasting",
        "MedianSquaredPercentageError": "metric_forecasting",
        "MedianSquaredScaledError": "metric_forecasting",
        "Merger": "transformer",
        "MiddleOutReconciler": "reconciler",
        "MiniRocket": "transformer",
        "MiniRocketMultivariate": "transformer",
        "MiniRocketMultivariateVariable": "transformer",
        "MomentFMClassifier": "classifier",
        "MomentFMForecaster": "global_forecaster",
        "MovingBlockBootstrapTransformer": "transformer",
        "MovingWindow": "detector",
        "MrSEQL": "classifier",
        "MrSQM": "classifier",
        "MultiRocket": "transformer",
        "MultiRocketMultivariate": "transformer",
        "MultioutputTabularRegressionForecaster": "forecaster",
        "MultioutputTimeSeriesRegressionForecaster": "forecaster",
        "MultiplexClassifier": "classifier",
        "MultiplexForecaster": "forecaster",
        "MultiplexRegressor": "regressor",
        "MultiplexTransformer": "transformer",
        "NaiveForecaster": "forecaster",
        "NaiveVariance": "forecaster",
        "NeuralForecastDilatedRNN": "global_forecaster",
        "NeuralForecastGRU": "global_forecaster",
        "NeuralForecastLSTM": "global_forecaster",
        "NeuralForecastRNN": "global_forecaster",
        "NeuralForecastTCN": "global_forecaster",
        "NonNegativeOptimalReconciler": "reconciler",
        "OSULeaf": "dataset_classification",
        "OnlineEnsembleForecaster": "forecaster",
        "OptimalReconciler": "reconciler",
        "OptionalPassthrough": "transformer",
        "OverallWeightedAverage": "metric_forecasting",
        "PAA": "transformer",
        "PAAlegacy": "transformer",
        "PBS": "dataset_forecasting",
        "PCATransformer": "transformer",
        "PELT": "detector",
        "PLAID": "dataset_classification",
        "PaddingTransformer": "transformer",
        "PandasTransformAdaptor": "transformer",
        "ParamFitterPipeline": "param_est",
        "PartialAutoCorrelationTransformer": "transformer",
        "PatchTSTForecaster": "global_forecaster",
        "PeakTimeFeature": "transformer",
        "Permute": "forecaster",
        "PinballLoss": "metric_forecasting_proba",
        "Pipeline": "estimator",
        "PlateauFinder": "transformer",
        "PluginParamsForecaster": "forecaster",
        "PluginParamsTransformer": "transformer",
        "PoissonHMM": "detector",
        "PolynomialTrendForecaster": "forecaster",
        "ProbabilityThresholdEarlyClassifier": "classifier",
        "Prophet": "forecaster",
        "ProphetPiecewiseLinearTrendForecaster": "forecaster",
        "Prophetverse": "forecaster",
        "ProximityForest": "classifier",
        "ProximityStump": "classifier",
        "ProximityTree": "classifier",
        "PwTrafoPanelPipeline": "transformer-pairwise-panel",
        "PyKANForecaster": "forecaster",
        "PyODDetector": "detector",
        "PytorchForecastingDeepAR": "global_forecaster",
        "PytorchForecastingNBeats": "global_forecaster",
        "PytorchForecastingNHiTS": "global_forecaster",
        "PytorchForecastingTFT": "global_forecaster",
        "RBFForecaster": "forecaster",
        "RBFTransformer": "transformer",
        "RNNNetwork": "network",
        "RandIndex": "metric_detection",
        "RandomIntervalClassifier": "classifier",
        "RandomIntervalFeatureExtractor": "transformer",
        "RandomIntervalSegmenter": "transformer",
        "RandomIntervalSpectralEnsemble": "classifier",
        "RandomIntervals": "transformer",
        "RandomSamplesAugmenter": "transformer",
        "RandomShapeletTransform": "transformer",
        "Reconciler": "transformer",
        "ReconcilerForecaster": "forecaster",
        "RecursiveReductionForecaster": "forecaster",
        "RecursiveTabularRegressionForecaster": "forecaster",
        "RecursiveTimeSeriesRegressionForecaster": "forecaster",
        "ReducerTransform": "transformer",
        "RegressorPipeline": "regressor",
        "RelativeLoss": "metric_forecasting",
        "Repeat": "splitter",
        "RepeatBootstrapTransformer": "transformer",
        "ResNetClassifier": "classifier",
        "ResNetNetwork": "network",
        "ResNetRegressor": "regressor",
        "ResidualBoostingForecaster": "forecaster",
        "ReverseAugmenter": "transformer",
        "Rocket": "transformer",
        "RocketClassifier": "classifier",
        "RocketPyts": "transformer",
        "RocketRegressor": "regressor",
        "SARIMAX": "forecaster",
        "SAX": "transformer",
        "SAXlegacy": "transformer",
        "SCINetForecaster": "forecaster",
        "SFA": "transformer",
        "SFAFast": "transformer",
        "STDBSCAN": "clusterer",
        "STLBootstrapTransformer": "transformer",
        "STLForecaster": "forecaster",
        "STLTransformer": "transformer",
        "STRAY": "transformer",
        "SameLocSplitter": "splitter",
        "ScaledAsinhTransformer": "transformer",
        "ScaledLogitTransformer": "transformer",
        "ScipyDist": "transformer-pairwise",
        "SeasonalDummiesOneHot": "transformer",
        "SeasonalityACF": "param_est",
        "SeasonalityACFqstat": "param_est",
        "SeasonalityPeriodogram": "param_est",
        "SeededBinarySegmentation": "detector",
        "ShampooSales": "dataset_forecasting",
        "ShapeDTW": "classifier",
        "ShapeletLearningClassifierPyts": "classifier",
        "ShapeletLearningClassifierTslearn": "classifier",
        "ShapeletTransform": "transformer",
        "ShapeletTransformClassifier": "classifier",
        "ShapeletTransformPyts": "transformer",
        "SignatureClassifier": "classifier",
        "SignatureKernel": "transformer-pairwise-panel",
        "SignatureMoments": "transformer",
        "SignatureTransformer": "transformer",
        "SimpleRNNClassifier": "classifier",
        "SimpleRNNClassifierTorch": "classifier",
        "SimpleRNNRegressor": "regressor",
        "SimpleRNNRegressorTorch": "regressor",
        "SingleWindowSplitter": "splitter",
        "SkforecastAutoreg": "forecaster",
        "SkforecastRecursive": "forecaster",
        "SklearnClassifierPipeline": "classifier",
        "SklearnClustererPipeline": "clusterer",
        "SklearnRegressorPipeline": "regressor",
        "SlidingGreedySplitter": "splitter",
        "SlidingWindowSegmenter": "transformer",
        "SlidingWindowSplitter": "splitter",
        "SlopeTransformer": "transformer",
        "SoftDtwDistTslearn": "transformer-pairwise-panel",
        "Solar": "dataset_forecasting",
        "SplineTrendForecaster": "forecaster",
        "SplitterBootstrapTransformer": "transformer",
        "SplitterSummarizer": "transformer",
        "SqrtTransformer": "transformer",
        "SquaredDistrLoss": "metric_forecasting_proba",
        "SquaringResiduals": "forecaster",
        "SqueezeHierarchy": "transformer",
        "StackingForecaster": "forecaster",
        "StatThresholdAnomaliser": "detector",
        "StationarityADF": "param_est",
        "StationarityADFArch": "param_est",
        "StationarityDFGLS": "param_est",
        "StationarityKPSS": "param_est",
        "StationarityKPSSArch": "param_est",
        "StationarityPhillipsPerron": "param_est",
        "StationarityVarianceRatio": "param_est",
        "StationarityZivotAndrews": "param_est",
        "StatsForecastADIDA": "forecaster",
        "StatsForecastARCH": "forecaster",
        "StatsForecastAutoARIMA": "forecaster",
        "StatsForecastAutoCES": "forecaster",
        "StatsForecastAutoETS": "forecaster",
        "StatsForecastAutoTBATS": "forecaster",
        "StatsForecastAutoTheta": "forecaster",
        "StatsForecastGARCH": "forecaster",
        "StatsForecastMSTL": "forecaster",
        "StatsModelsARIMA": "forecaster",
        "SubLOF": "detector",
        "SubsequenceExtractionTransformer": "transformer",
        "SummaryClassifier": "classifier",
        "SummaryTransformer": "transformer",
        "SupervisedIntervals": "transformer",
        "SupervisedTimeSeriesForest": "classifier",
        "TBATS": "forecaster",
        "TEASER": "early_classifier",
        "TSB": "forecaster",
        "TSBootstrapAdapter": "transformer",
        "TSCGridSearchCV": "classifier",
        "TSCOptCV": "classifier",
        "TSFELTransformer": "transformer",
        "TSFeaturesTransformer": "transformer",
        "TSFreshClassifier": "classifier",
        "TSFreshFeatureExtractor": "transformer",
        "TSFreshRelevantFeatureExtractor": "transformer",
        "TSInterpolator": "transformer",
        "TSRGridSearchCV": "regressor",
        "TabularToSeriesAdaptor": "transformer",
        "Tabularizer": "transformer",
        "TapNetClassifier": "classifier",
        "TapNetNetwork": "network",
        "TapNetRegressor": "regressor",
        "Tecator": "dataset_regression",
        "TemporalDictionaryEnsemble": "classifier",
        "TemporalTrainTestSplitter": "splitter",
        "TemporianTransformer": "transformer",
        "TestPlusTrainSplitter": "splitter",
        "ThetaForecaster": "forecaster",
        "ThetaLinesTransformer": "transformer",
        "ThetaModularForecaster": "forecaster",
        "ThresholdDetector": "detector",
        "TiRexForecaster": "forecaster",
        "TimeBinAggregate": "transformer",
        "TimeBinner": "transformer",
        "TimeLLMForecaster": "forecaster",
        "TimeMoEForecaster": "global_forecaster",
        "TimeSeriesAUPRC": "metric_detection",
        "TimeSeriesDBSCAN": "clusterer",
        "TimeSeriesForestClassifier": "classifier",
        "TimeSeriesForestRegressor": "regressor",
        "TimeSeriesKMeans": "clusterer",
        "TimeSeriesKMeansTslearn": "clusterer",
        "TimeSeriesKMedoids": "clusterer",
        "TimeSeriesKShapes": "clusterer",
        "TimeSeriesKernelKMeans": "clusterer",
        "TimeSeriesKvisibility": "clusterer",
        "TimeSeriesSVC": "classifier",
        "TimeSeriesSVCTslearn": "classifier",
        "TimeSeriesSVRTslearn": "regressor",
        "TimeSince": "transformer",
        "TimesFMForecaster": "global_forecaster",
        "TinyTimeMixerForecaster": "global_forecaster",
        "TopdownReconciler": "reconciler",
        "TotoForecaster": "forecaster",
        "TransformByLevel": "transformer",
        "TransformIf": "transformer",
        "TransformSelectForecaster": "forecaster",
        "TransformedTargetForecaster": "forecaster",
        "TransformerPipeline": "transformer",
        "TrendForecaster": "forecaster",
        "TruncationTransformer": "transformer",
        "UCRUEADataset": "dataset_classification",
        "USChange": "dataset_forecasting",
        "UnobservedComponents": "forecaster",
        "UpdateEvery": "forecaster",
        "UpdateRefitsEvery": "forecaster",
        "VAR": "forecaster",
        "VARMAX": "forecaster",
        "VARReduce": "forecaster",
        "VECM": "forecaster",
        "VmdTransformer": "transformer",
        "WEASEL": "classifier",
        "WeightedEnsembleClassifier": "classifier",
        "WhiteNoiseAugmenter": "transformer",
        "WindowSegmenter": "detector",
        "WindowSummarizer": "transformer",
        "WindowedF1Score": "metric_detection",
        "YfromX": "forecaster",
        "YtoX": "transformer",
        "ZeroAnomalies": "detector",
        "ZeroChangePoints": "detector",
        "ZeroSegments": "detector",
    }

    _objs_by_type = {
        "dataset_classification": [
            "ACSF1",
            "ArrowHead",
            "BasicMotions",
            "GunPoint",
            "ItalyPowerDemand",
            "JapaneseVowels",
            "OSULeaf",
            "PLAID",
            "UCRUEADataset",
        ],
        "transformer": [
            "ADICVTransformer",
            "Aggregator",
            "AutoCorrelationTransformer",
            "BKFilter",
            "Bollinger",
            "BoxCoxTransformer",
            "CFFilter",
            "Catch22",
            "Catch22Wrapper",
            "ClaSPTransformer",
            "ClearSky",
            "ClustererAsTransformer",
            "ColumnConcatenator",
            "ColumnEnsembleTransformer",
            "ColumnSelect",
            "ColumnTransformer",
            "ColumnwiseTransformer",
            "CombineTransformers",
            "ConditionalDeseasonalizer",
            "CosineTransformer",
            "CountryHolidaysTransformer",
            "DOBIN",
            "DWTTransformer",
            "DateTimeFeatures",
            "DegreeDayFeatures",
            "DerivativeSlopeTransformer",
            "Deseasonalizer",
            "DetectorAsTransformer",
            "Detrender",
            "Differencer",
            "DilationMappingTransformer",
            "DistanceFeatures",
            "DropNA",
            "EAgglo",
            "ElbowClassPairwise",
            "ElbowClassSum",
            "ExponentTransformer",
            "FABBA",
            "FeatureSelection",
            "FeatureUnion",
            "Filter",
            "FinancialHolidaysTransformer",
            "FitInTransform",
            "FittedParamExtractor",
            "FourierFeatures",
            "FourierTransform",
            "FunctionTransformer",
            "HOG1DTransformer",
            "HPFilter",
            "HampelFilter",
            "Hidalgo",
            "HolidayFeatures",
            "HurstExponentTransformer",
            "Id",
            "Imputer",
            "IndexSubset",
            "IntervalSegmenter",
            "InvertAugmenter",
            "InvertTransform",
            "IxToX",
            "KalmanFilterTransformerFP",
            "KalmanFilterTransformerPK",
            "KalmanFilterTransformerSIMD",
            "KinematicFeatures",
            "Lag",
            "LogTransformer",
            "Logger",
            "MSTL",
            "MatrixProfile",
            "MatrixProfileTransformer",
            "Merger",
            "MiniRocket",
            "MiniRocketMultivariate",
            "MiniRocketMultivariateVariable",
            "MovingBlockBootstrapTransformer",
            "MultiRocket",
            "MultiRocketMultivariate",
            "MultiplexTransformer",
            "OptionalPassthrough",
            "PAA",
            "PAAlegacy",
            "PCATransformer",
            "PaddingTransformer",
            "PandasTransformAdaptor",
            "PartialAutoCorrelationTransformer",
            "PeakTimeFeature",
            "PlateauFinder",
            "PluginParamsTransformer",
            "RBFTransformer",
            "RandomIntervalFeatureExtractor",
            "RandomIntervalSegmenter",
            "RandomIntervals",
            "RandomSamplesAugmenter",
            "RandomShapeletTransform",
            "Reconciler",
            "ReducerTransform",
            "RepeatBootstrapTransformer",
            "ReverseAugmenter",
            "Rocket",
            "RocketPyts",
            "SAX",
            "SAXlegacy",
            "SFA",
            "SFAFast",
            "STLBootstrapTransformer",
            "STLTransformer",
            "STRAY",
            "ScaledAsinhTransformer",
            "ScaledLogitTransformer",
            "SeasonalDummiesOneHot",
            "ShapeletTransform",
            "ShapeletTransformPyts",
            "SignatureMoments",
            "SignatureTransformer",
            "SlidingWindowSegmenter",
            "SlopeTransformer",
            "SplitterBootstrapTransformer",
            "SplitterSummarizer",
            "SqrtTransformer",
            "SqueezeHierarchy",
            "SubsequenceExtractionTransformer",
            "SummaryTransformer",
            "SupervisedIntervals",
            "TSBootstrapAdapter",
            "TSFELTransformer",
            "TSFeaturesTransformer",
            "TSFreshFeatureExtractor",
            "TSFreshRelevantFeatureExtractor",
            "TSInterpolator",
            "TabularToSeriesAdaptor",
            "Tabularizer",
            "TemporianTransformer",
            "ThetaLinesTransformer",
            "TimeBinAggregate",
            "TimeBinner",
            "TimeSince",
            "TransformByLevel",
            "TransformIf",
            "TransformerPipeline",
            "TruncationTransformer",
            "VmdTransformer",
            "WhiteNoiseAugmenter",
            "WindowSummarizer",
            "YtoX",
        ],
        "forecaster": [
            "ARARForecaster",
            "ARCH",
            "ARDL",
            "ARIMA",
            "AutoARIMA",
            "AutoETS",
            "AutoEnsembleForecaster",
            "AutoREG",
            "AutoTS",
            "BATS",
            "BaggingForecaster",
            "BoxCoxBiasAdjustedForecaster",
            "CINNForecaster",
            "ChronosForecaster",
            "ColumnEnsembleForecaster",
            "ConformalIntervals",
            "ConvTimeNetForecaster",
            "Croston",
            "CurveFitForecaster",
            "DartsLinearRegressionModel",
            "DartsRegressionModel",
            "DartsXGBModel",
            "DirRecTabularRegressionForecaster",
            "DirRecTimeSeriesRegressionForecaster",
            "DirectReductionForecaster",
            "DirectTabularRegressionForecaster",
            "DirectTimeSeriesRegressionForecaster",
            "DontUpdate",
            "DoubleMLForecaster",
            "DummyGlobalForecaster",
            "DynamicFactor",
            "ESRNNForecaster",
            "EnbPIForecaster",
            "EnsembleForecaster",
            "ExponentialSmoothing",
            "FallbackForecaster",
            "FhPlexForecaster",
            "ForecastByLevel",
            "ForecastKnownValues",
            "ForecastX",
            "ForecastingGridSearchCV",
            "ForecastingOptCV",
            "ForecastingOptunaSearchCV",
            "ForecastingPipeline",
            "ForecastingRandomizedSearchCV",
            "ForecastingSkoptSearchCV",
            "GreykiteForecaster",
            "GroupbyCategoryForecaster",
            "HCrystalBallAdapter",
            "HFTransformersForecaster",
            "HierarchicalProphet",
            "HierarchyEnsembleForecaster",
            "IgnoreX",
            "LTSFDLinearForecaster",
            "LTSFLinearForecaster",
            "LTSFNLinearForecaster",
            "LTSFTransformerForecaster",
            "MAPAForecaster",
            "MultioutputTabularRegressionForecaster",
            "MultioutputTimeSeriesRegressionForecaster",
            "MultiplexForecaster",
            "NaiveForecaster",
            "NaiveVariance",
            "OnlineEnsembleForecaster",
            "Permute",
            "PluginParamsForecaster",
            "PolynomialTrendForecaster",
            "Prophet",
            "ProphetPiecewiseLinearTrendForecaster",
            "Prophetverse",
            "PyKANForecaster",
            "RBFForecaster",
            "ReconcilerForecaster",
            "RecursiveReductionForecaster",
            "RecursiveTabularRegressionForecaster",
            "RecursiveTimeSeriesRegressionForecaster",
            "ResidualBoostingForecaster",
            "SARIMAX",
            "SCINetForecaster",
            "STLForecaster",
            "SkforecastAutoreg",
            "SkforecastRecursive",
            "SplineTrendForecaster",
            "SquaringResiduals",
            "StackingForecaster",
            "StatsForecastADIDA",
            "StatsForecastARCH",
            "StatsForecastAutoARIMA",
            "StatsForecastAutoCES",
            "StatsForecastAutoETS",
            "StatsForecastAutoTBATS",
            "StatsForecastAutoTheta",
            "StatsForecastGARCH",
            "StatsForecastMSTL",
            "StatsModelsARIMA",
            "TBATS",
            "TSB",
            "ThetaForecaster",
            "ThetaModularForecaster",
            "TiRexForecaster",
            "TimeLLMForecaster",
            "TotoForecaster",
            "TransformSelectForecaster",
            "TransformedTargetForecaster",
            "TrendForecaster",
            "UnobservedComponents",
            "UpdateEvery",
            "UpdateRefitsEvery",
            "VAR",
            "VARMAX",
            "VARReduce",
            "VECM",
            "YfromX",
        ],
        "param_est": [
            "ARLagOrderSelector",
            "AcorrLjungbox",
            "BreakvarHeteroskedasticityTest",
            "FixedParams",
            "FunctionParamFitter",
            "JarqueBera",
            "JohansenCointegration",
            "ParamFitterPipeline",
            "SeasonalityACF",
            "SeasonalityACFqstat",
            "SeasonalityPeriodogram",
            "StationarityADF",
            "StationarityADFArch",
            "StationarityDFGLS",
            "StationarityKPSS",
            "StationarityKPSSArch",
            "StationarityPhillipsPerron",
            "StationarityVarianceRatio",
            "StationarityZivotAndrews",
        ],
        "metric_forecasting_proba": [
            "AUCalibration",
            "CRPS",
            "ConstraintViolation",
            "EmpiricalCoverage",
            "IntervalWidth",
            "LogLoss",
            "PinballLoss",
            "SquaredDistrLoss",
        ],
        "transformer-pairwise-panel": [
            "AggrDist",
            "CombinedDistance",
            "ConstantPwTrafoPanel",
            "CtwDistTslearn",
            "DistFromAligner",
            "DistFromKernel",
            "DtwDist",
            "DtwDistTslearn",
            "DtwDtaidistMultiv",
            "DtwDtaidistUniv",
            "DtwPythonDist",
            "EditDist",
            "FlatDist",
            "GAKernel",
            "IndepDist",
            "KernelFromDist",
            "LcssTslearn",
            "LuckyDtwDist",
            "PwTrafoPanelPipeline",
            "SignatureKernel",
            "SoftDtwDistTslearn",
        ],
        "dataset_forecasting": [
            "Airline",
            "ForecastingData",
            "HierarchicalSalesToydata",
            "Longley",
            "Lynx",
            "M5Dataset",
            "Macroeconomic",
            "PBS",
            "ShampooSales",
            "Solar",
            "USChange",
        ],
        "aligner": [
            "AlignerDTW",
            "AlignerDTWfromDist",
            "AlignerDtwDtai",
            "AlignerDtwNumba",
            "AlignerEditNumba",
            "AlignerLuckyDtw",
            "AlignerNaive",
        ],
        "classifier": [
            "Arsenal",
            "BOSSEnsemble",
            "BOSSVSClassifierPyts",
            "BaggingClassifier",
            "CNNClassifier",
            "CNTCClassifier",
            "CanonicalIntervalForest",
            "Catch22Classifier",
            "ClassifierPipeline",
            "ColumnEnsembleClassifier",
            "ComposableTimeSeriesForestClassifier",
            "ContractableBOSS",
            "ConvTimeNetClassifier",
            "DrCIF",
            "DummyClassifier",
            "ElasticEnsemble",
            "FCNClassifier",
            "FreshPRINCE",
            "GRUClassifier",
            "GRUFCNNClassifier",
            "HIVECOTEV1",
            "HIVECOTEV2",
            "InceptionTimeClassifier",
            "IndividualBOSS",
            "IndividualTDE",
            "KNeighborsTimeSeriesClassifier",
            "KNeighborsTimeSeriesClassifierPyts",
            "KNeighborsTimeSeriesClassifierTslearn",
            "LSTMFCNClassifier",
            "MACNNClassifier",
            "MCDCNNClassifier",
            "MCDCNNClassifierTorch",
            "MLPClassifier",
            "MLPClassifierTorch",
            "MUSE",
            "MVTSTransformerClassifier",
            "MatrixProfileClassifier",
            "MomentFMClassifier",
            "MrSEQL",
            "MrSQM",
            "MultiplexClassifier",
            "ProbabilityThresholdEarlyClassifier",
            "ProximityForest",
            "ProximityStump",
            "ProximityTree",
            "RandomIntervalClassifier",
            "RandomIntervalSpectralEnsemble",
            "ResNetClassifier",
            "RocketClassifier",
            "ShapeDTW",
            "ShapeletLearningClassifierPyts",
            "ShapeletLearningClassifierTslearn",
            "ShapeletTransformClassifier",
            "SignatureClassifier",
            "SimpleRNNClassifier",
            "SimpleRNNClassifierTorch",
            "SklearnClassifierPipeline",
            "SummaryClassifier",
            "SupervisedTimeSeriesForest",
            "TSCGridSearchCV",
            "TSCOptCV",
            "TSFreshClassifier",
            "TapNetClassifier",
            "TemporalDictionaryEnsemble",
            "TimeSeriesForestClassifier",
            "TimeSeriesSVC",
            "TimeSeriesSVCTslearn",
            "WEASEL",
            "WeightedEnsembleClassifier",
        ],
        "detector": [
            "BinarySegmentation",
            "CAPA",
            "CircularBinarySegmentation",
            "ClaSPSegmentation",
            "ClusterSegmenter",
            "DetectorPipeline",
            "DummyRegularAnomalies",
            "DummyRegularChangePoints",
            "GMMHMM",
            "GaussianHMM",
            "GreedyGaussianSegmentation",
            "HMM",
            "MVCAPA",
            "MovingWindow",
            "PELT",
            "PoissonHMM",
            "PyODDetector",
            "SeededBinarySegmentation",
            "StatThresholdAnomaliser",
            "SubLOF",
            "ThresholdDetector",
            "WindowSegmenter",
            "ZeroAnomalies",
            "ZeroChangePoints",
            "ZeroSegments",
        ],
        "reconciler": [
            "BottomUpReconciler",
            "MiddleOutReconciler",
            "NonNegativeOptimalReconciler",
            "OptimalReconciler",
            "TopdownReconciler",
        ],
        "network": [
            "CNNNetwork",
            "CNTCNetwork",
            "FCNNetwork",
            "InceptionTimeNetwork",
            "LSTMFCNNetwork",
            "MACNNNetwork",
            "MCDCNNNetwork",
            "MLPNetwork",
            "RNNNetwork",
            "ResNetNetwork",
            "TapNetNetwork",
        ],
        "regressor": [
            "CNNRegressor",
            "CNTCRegressor",
            "ComposableTimeSeriesForestRegressor",
            "DummyRegressor",
            "FCNRegressor",
            "InceptionTimeRegressor",
            "KNeighborsTimeSeriesRegressor",
            "LSTMFCNRegressor",
            "MACNNRegressor",
            "MCDCNNRegressor",
            "MCDCNNRegressorTorch",
            "MLPRegressor",
            "MultiplexRegressor",
            "RegressorPipeline",
            "ResNetRegressor",
            "RocketRegressor",
            "SimpleRNNRegressor",
            "SimpleRNNRegressorTorch",
            "SklearnRegressorPipeline",
            "TSRGridSearchCV",
            "TapNetRegressor",
            "TimeSeriesForestRegressor",
            "TimeSeriesSVRTslearn",
        ],
        "clusterer": [
            "ClustererPipeline",
            "STDBSCAN",
            "SklearnClustererPipeline",
            "TimeSeriesDBSCAN",
            "TimeSeriesKMeans",
            "TimeSeriesKMeansTslearn",
            "TimeSeriesKMedoids",
            "TimeSeriesKShapes",
            "TimeSeriesKernelKMeans",
            "TimeSeriesKvisibility",
        ],
        "splitter": [
            "CutoffFhSplitter",
            "CutoffSplitter",
            "ExpandingCutoffSplitter",
            "ExpandingGreedySplitter",
            "ExpandingSlidingWindowSplitter",
            "ExpandingWindowSplitter",
            "ForecastingHorizonSplitter",
            "InstanceSplitter",
            "Repeat",
            "SameLocSplitter",
            "SingleWindowSplitter",
            "SlidingGreedySplitter",
            "SlidingWindowSplitter",
            "TemporalTrainTestSplitter",
            "TestPlusTrainSplitter",
        ],
        "metric_detection": [
            "DetectionCount",
            "DirectedChamfer",
            "DirectedHausdorff",
            "RandIndex",
            "TimeSeriesAUPRC",
            "WindowedF1Score",
        ],
        "catalogue": [
            "DummyClassificationCatalogue",
            "DummyForecastingCatalogue",
            "M4CompetitionCatalogueDaily",
            "M4CompetitionCatalogueHourly",
            "M4CompetitionCatalogueMonthly",
            "M4CompetitionCatalogueQuarterly",
            "M4CompetitionCatalogueWeekly",
            "M4CompetitionCatalogueYearly",
        ],
        "metric_forecasting": [
            "GeometricMeanAbsoluteError",
            "GeometricMeanRelativeAbsoluteError",
            "GeometricMeanRelativeSquaredError",
            "GeometricMeanSquaredError",
            "MeanAbsoluteError",
            "MeanAbsolutePercentageError",
            "MeanAbsoluteScaledError",
            "MeanArctangentAbsolutePercentageError",
            "MeanAsymmetricError",
            "MeanLinexError",
            "MeanRelativeAbsoluteError",
            "MeanSquaredError",
            "MeanSquaredErrorPercentage",
            "MeanSquaredLogError",
            "MeanSquaredPercentageError",
            "MeanSquaredScaledError",
            "MedianAbsoluteError",
            "MedianAbsolutePercentageError",
            "MedianAbsoluteScaledError",
            "MedianRelativeAbsoluteError",
            "MedianSquaredError",
            "MedianSquaredPercentageError",
            "MedianSquaredScaledError",
            "OverallWeightedAverage",
            "RelativeLoss",
        ],
        "estimator": ["InformationGainSegmentation", "Pipeline"],
        "global_forecaster": [
            "MOIRAIForecaster",
            "MomentFMForecaster",
            "NeuralForecastDilatedRNN",
            "NeuralForecastGRU",
            "NeuralForecastLSTM",
            "NeuralForecastRNN",
            "NeuralForecastTCN",
            "PatchTSTForecaster",
            "PytorchForecastingDeepAR",
            "PytorchForecastingNBeats",
            "PytorchForecastingNHiTS",
            "PytorchForecastingTFT",
            "TimeMoEForecaster",
            "TimesFMForecaster",
            "TinyTimeMixerForecaster",
        ],
        "transformer-pairwise": ["ScipyDist"],
        "early_classifier": ["TEASER"],
        "dataset_regression": ["Tecator"],
    }
